# Generated by Django 5.2.17 on 2026-08-28 23:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('code', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('skill', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking')], max_length=16)),
                ('title', models.CharField(max_length=120)),
                ('part_number', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('strategy', models.JSONField(default=list)),
                ('common_mistakes', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['skill', 'part_number'],
            },
        ),
        migrations.CreateModel(
            name='TestFormatVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=False)),
                ('verified_on', models.DateField()),
                ('official_source_urls', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-verified_on', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('topic', models.CharField(max_length=120)),
                ('difficulty', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('estimated_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('source_type', models.CharField(choices=[('human_authored', 'Human authored'), ('ai_generated', 'AI-generated draft')], default='human_authored', max_length=20)),
                ('provenance', models.TextField(help_text='How this original material was created and checked.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_content', to=settings.AUTH_USER_MODEL)),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_items', to='content.tasktype')),
            ],
            options={
                'ordering': ['task_type__part_number', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('instructions', models.TextField()),
                ('stimulus', models.JSONField(help_text='Structured original email, prose, notice, or table content.')),
                ('learning_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='content.contentitem')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_content_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['item', '-version'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('stem', models.TextField()),
                ('skill_focus', models.CharField(choices=[('gist', 'Gist'), ('detail', 'Detail'), ('inference', 'Inference'), ('vocabulary', 'Vocabulary in context'), ('purpose', 'Purpose')], max_length=16)),
                ('evidence', models.TextField()),
                ('explanation', models.TextField()),
                ('content_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.contentversion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='content.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='tasktype',
            name='format_versions',
            field=models.ManyToManyField(blank=True, related_name='task_types', to='content.testformatversion'),
        ),
        migrations.AddConstraint(
            model_name='contentversion',
            constraint=models.UniqueConstraint(fields=('item', 'version'), name='content_unique_item_version'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('content_version', 'order'), name='content_unique_question_order'),
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='content_unique_choice_order'),
        ),
        migrations.AddConstraint(
            model_name='tasktype',
            constraint=models.UniqueConstraint(fields=('skill', 'part_number'), name='content_unique_skill_part'),
        ),
    ]
