# Generated by Django 5.2.17 on 2026-08-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testformatversion',
            name='component_order',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='testformatversion',
            name='component_timings',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='testformatversion',
            name='task_structure',
            field=models.JSONField(default=list),
        ),
    ]
