# Generated by Django 5.2.17 on 2026-08-29 12:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0004_remove_assessmentsession_assessments_only_practice_has_deadline_and_more'),
        ('content', '0002_testformatversion_component_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format_snapshot', models.JSONField()),
                ('scope', models.CharField(default='compact_task_family_mock', max_length=40)),
                ('state', models.CharField(choices=[('ready', 'Ready'), ('active', 'Active'), ('between_sections', 'Between sections'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='ready', max_length=20)),
                ('current_order', models.PositiveSmallIntegerField(default=0)),
                ('current_section', models.CharField(blank=True, choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking')], max_length=16)),
                ('section_started_at', models.DateTimeField(blank=True, null=True)),
                ('section_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('format_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mock_attempts', to='content.testformatversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('section', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking')], max_length=16)),
                ('task_type', models.CharField(max_length=64)),
                ('snapshot', models.JSONField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('current', 'Current'), ('submitted', 'Submitted'), ('skipped', 'Skipped')], default='pending', max_length=12)),
                ('is_simulated_unscored', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='mocks.mockattempt')),
                ('content_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mock_tasks', to='content.contentversion')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mock_task', to='assessments.assessmentsession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='mockattempt',
            index=models.Index(fields=['user', 'state', '-created_at'], name='mocks_mocka_user_id_0d2122_idx'),
        ),
        migrations.AddConstraint(
            model_name='mocktask',
            constraint=models.UniqueConstraint(fields=('attempt', 'order'), name='mocks_unique_attempt_task_order'),
        ),
        migrations.AddConstraint(
            model_name='mocktask',
            constraint=models.UniqueConstraint(fields=('attempt', 'task_type'), name='mocks_unique_attempt_task_type'),
        ),
    ]
