# Generated by Django 5.2.17 on 2026-09-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0002_full_length_mock_assembly'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockattempt',
            name='section_log',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
