"""Second variant of full-part Reading simulation sets.

Each set is an entire official Reading part (one email, table, information
article, or viewpoints passage at the full official question count) and is a
second, distinct scenario from ``reading_official_parts.py`` so that repeated
full-length mocks can rotate to fresh content. Reading parts carry no audio.

All text and questions are original to this repository and follow the same
item shape as ``reading_seed_data_v2.py``.
"""
# ruff: noqa: E501


def c(text, correct, explanation):
    return {"text": text, "is_correct": correct, "explanation": explanation}


READING_OFFICIAL_SETS_V2 = [
    {
        "slug": "library-office-move-email",
        "task_type": "reading_correspondence",
        "title": "Library Office Move Email",
        "topic": "Workplace communication",
        "difficulty": 2,
        "estimated_level": 7,
        "instructions": "Read the email and answer the questions.",
        "stimulus": {
            "type": "email",
            "from": "Maplewood Library Facilities Office",
            "to": "All branch staff",
            "subject": "Administration office move to the Harbour Building",
            "body": "Dear colleagues,\n\nAs you know, the administration offices move to the Harbour Building on the weekend of February 21 and 22, and both buildings will be closed to the public that Saturday and Sunday while the move takes place. Please do not schedule meetings in either building on those dates.\n\nClear your desk and label every box by Thursday, February 19, at 5 p.m. Labels are available at the reception desk on each floor; write your name, your new floor, and a short list of the contents. Do not pack anything marked 'corporate files'. The records team moves those separately, and they must stay in the locked cabinet until pickup.\n\nLeave desktop computers and monitors in place; the moving crew disconnects and relocates them. Laptops are different: back up your files to the shared drive by Wednesday, February 18, and carry your laptop with you on the move day.\n\nParking: old-building permits expire on February 20. The Harbour Building has 120 staff spaces on a first-come, first-served basis. If you need a reserved spot, join the waitlist through the HR portal by February 14.\n\nTransport: a free shuttle runs between the two buildings for the first two weeks of March, every 15 minutes during rush hours and every 30 minutes at other times. During move week, February 23 to 27, the shuttle runs all day between 7 a.m. and 7 p.m.\n\nMail and phones: incoming mail addressed to the old building is forwarded daily until March 6. Your phone number does not change, and the switchboard redirects calls during the move.\n\nWe will hold a town hall on Thursday, February 12, at 10 a.m. in the main meeting room to answer questions. Please bring your moving checklist.\n\nThank you for making this a smooth transition.\n\nThe Facilities Office",
        },
        "learning_notes": "Note which actions are optional versus required, and check dates and deadlines against each instruction.",
        "questions": [
            {"stem": "What is the main purpose of the email?", "skill_focus": "gist", "evidence": "the administration offices move to the Harbour Building ... Clear your desk and label every box", "explanation": "The email tells staff about the move and the steps they must take before it.", "choices": [c("To announce a pay increase", False, "No pay change is mentioned."), c("To explain the office move and the steps staff must take", True, "The move, packing rules, parking, and shuttle are all covered."), c("To cancel all library programs", False, "Programs are not discussed."), c("To advertise parking at the new building", False, "Parking is one detail among several.")]},
            {"stem": "Why should staff not book meetings on February 21 and 22?", "skill_focus": "inference", "evidence": "both buildings will be closed to the public that Saturday and Sunday while the move takes place", "explanation": "The move happens that weekend, so the buildings are unavailable for meetings.", "choices": [c("Because the buildings are closed for the move that weekend", True, "The closure is the stated reason."), c("Because the town hall is held then", False, "The town hall is on Thursday, February 12."), c("Because it is a statutory holiday", False, "No holiday is mentioned."), c("Because the parking lot is full", False, "Parking is separate from meeting availability.")]},
            {"stem": "What must staff do by Thursday, February 19, at 5 p.m.?", "skill_focus": "detail", "evidence": "Clear your desk and label every box by Thursday, February 19, at 5 p.m.", "explanation": "Desks must be cleared and boxes labelled by that deadline.", "choices": [c("Clear their desks and label every box", True, "This is the stated deadline task."), c("Join the parking waitlist", False, "The waitlist deadline is February 14."), c("Back up files to the shared drive", False, "The backup is due by Wednesday, February 18."), c("Return their laptops", False, "Laptops are carried to the new building.")]},
            {"stem": "What does the email say about boxes marked 'corporate files'?", "skill_focus": "detail", "evidence": "Do not pack anything marked 'corporate files'. The records team moves those separately", "explanation": "Staff must leave corporate-files boxes for the records team.", "choices": [c("Staff must pack them first", False, "Staff are told not to pack them."), c("The records team moves them separately", True, "This is stated directly."), c("They are thrown away", False, "They are moved, not discarded."), c("They stay at the old building", False, "The records team relocates them.")]},
            {"stem": "What must staff do with desktop computers?", "skill_focus": "detail", "evidence": "Leave desktop computers and monitors in place; the moving crew disconnects and relocates them", "explanation": "Desktops stay put and the crew handles them.", "choices": [c("Disconnect and carry them themselves", False, "The crew does the disconnecting."), c("Leave them in place for the crew to relocate", True, "This is the stated instruction."), c("Sell them before the move", False, "No sale is mentioned."), c("Back them up and take them home", False, "Backup-and-carry applies to laptops.")]},
            {"stem": "What does the email say to do with laptops before the move?", "skill_focus": "detail", "evidence": "back up your files to the shared drive by Wednesday, February 18, and carry your laptop with you", "explanation": "Laptops are backed up and then carried by staff on move day.", "choices": [c("Back them up and carry them personally", True, "Both steps are stated."), c("Leave them on the desk for the crew", False, "Crew handling applies to desktops."), c("Mail them to the new building", False, "No mailing is suggested."), c("Lock them in the cabinet", False, "The cabinet is for corporate files.")]},
            {"stem": "When do the old-building parking permits expire?", "skill_focus": "detail", "evidence": "old-building permits expire on February 20", "explanation": "The old permits stop working on February 20.", "choices": [c("February 14", False, "That is the waitlist deadline."), c("February 19", False, "That is the packing deadline."), c("February 20", True, "This is the stated expiry."), c("March 6", False, "March 6 is the mail-forwarding end date.")]},
            {"stem": "How can a staff member get a reserved parking space?", "skill_focus": "detail", "evidence": "join the waitlist through the HR portal by February 14", "explanation": "Reserved spaces go through the HR portal waitlist.", "choices": [c("By emailing the shuttle driver", False, "The shuttle is separate from parking."), c("By joining the HR portal waitlist by February 14", True, "This is the stated process."), c("By arriving early on February 21", False, "Spaces are reserved in advance."), c("By paying the Facilities Office", False, "No payment is mentioned.")]},
            {"stem": "How often does the shuttle run during rush hours?", "skill_focus": "detail", "evidence": "every 15 minutes during rush hours and every 30 minutes at other times", "explanation": "The rush-hour interval is 15 minutes.", "choices": [c("Every 10 minutes", False, "That is not the stated interval."), c("Every 15 minutes", True, "This matches the text."), c("Every 30 minutes", False, "30 minutes is the off-peak interval."), c("Once in the morning and once at night", False, "The shuttle runs continuously.")]},
            {"stem": "Until when is mail to the old building forwarded?", "skill_focus": "detail", "evidence": "incoming mail addressed to the old building is forwarded daily until March 6", "explanation": "Forwarding continues until March 6.", "choices": [c("Until February 20", False, "That is when parking permits expire."), c("Until March 6", True, "This is the stated end date."), c("For two weeks of March only", False, "It is daily forwarding to a date, not a two-week shuttle window."), c("For one month after the move", False, "The email gives a specific date.")]},
            {"stem": "What is happening on Thursday, February 12, at 10 a.m.?", "skill_focus": "detail", "evidence": "We will hold a town hall on Thursday, February 12, at 10 a.m. in the main meeting room", "explanation": "The town hall answers staff questions about the move.", "choices": [c("The move begins", False, "The move is on the weekend of February 21."), c("A town hall to answer questions", True, "This is the stated event."), c("Parking permits expire", False, "They expire on February 20."), c("The shuttle service ends", False, "The shuttle runs in March.")]},
        ],
    },
    {
        "slug": "harbour-sports-rental-prices",
        "task_type": "reading_apply_diagram",
        "title": "Harbour Sports Rental Prices",
        "topic": "Recreation rentals",
        "difficulty": 2,
        "estimated_level": 7,
        "instructions": "Use the table and notes to answer the questions.",
        "stimulus": {
            "type": "table",
            "title": "Harbour Sports daily rental prices",
            "columns": ["Item", "Member daily", "Public daily", "Deposit", "Max rental days"],
            "rows": [
                ["Canoe (seats 3)", "$14", "$20", "$25", "3"],
                ["Kayak (single)", "$12", "$18", "$20", "3"],
                ["Stand-up paddleboard", "$10", "$15", "$15", "2"],
                ["Pedal boat", "$16", "$24", "$30", "1"],
                ["Standard bicycle", "$8", "$12", "$10", "7"],
                ["Electric bicycle", "$15", "$22", "$25", "3"],
            ],
            "notes": "Rentals are open to anyone with government photo ID, and you may reserve online up to 7 days in advance. Every rental includes the required safety gear: a life jacket with any boat and a helmet with any bicycle. A double kayak is charged as a canoe at the canoe rate plus $6. Children under 12 may ride as passengers but cannot operate pedal boats. If the rental office closes the water due to weather before noon, you get a full refund.",
        },
        "learning_notes": "Read across the chosen row, then apply the notes about booking, gear, the double-kayak surcharge, and refunds.",
        "questions": [
            {"stem": "What is the table mainly for?", "skill_focus": "gist", "evidence": "columns compare member and public daily rates, deposits, and maximum rental days", "explanation": "The table lets renters compare prices and rental terms across items.", "choices": [c("Comparing the cost and terms of renting equipment", True, "Rates, deposits, and day limits are all shown."), c("Reporting daily weather at the harbour", False, "Weather appears only in the refund note."), c("Listing items for sale", False, "The items are rented, not sold."), c("Scheduling lifeguard shifts", False, "No shifts are shown.")]},
            {"stem": "How much does a member pay to rent a canoe for one day?", "skill_focus": "detail", "evidence": "Canoe (seats 3) ... Member daily $14", "explanation": "The member daily rate for a canoe is $14.", "choices": [c("$14", True, "This matches the canoe row."), c("$20", False, "$20 is the public rate."), c("$25", False, "$25 is the canoe deposit."), c("$12", False, "$12 is the member kayak rate.")]},
            {"stem": "Which item requires the largest deposit?", "skill_focus": "detail", "evidence": "Pedal boat ... Deposit $30", "explanation": "The pedal boat carries the $30 deposit, the highest shown.", "choices": [c("Canoe", False, "Its deposit is $25."), c("Stand-up paddleboard", False, "Its deposit is $15."), c("Pedal boat", True, "Its deposit is $30."), c("Electric bicycle", False, "Its deposit is $25.")]},
            {"stem": "For how many days may a standard bicycle be rented at most?", "skill_focus": "detail", "evidence": "Standard bicycle ... Max rental days 7", "explanation": "The standard bicycle can be kept up to seven days.", "choices": [c("2 days", False, "Two is the paddleboard limit."), c("3 days", False, "Three applies to canoes and single kayaks."), c("7 days", True, "This matches the standard bicycle."), c("Unlimited", False, "A maximum is stated.")]},
            {"stem": "How much more does a public renter pay than a member for an electric bicycle per day?", "skill_focus": "detail", "evidence": "Electric bicycle ... Member daily $15, Public daily $22", "explanation": "The public rate is $7 above the member rate.", "choices": [c("$7", True, "$22 minus $15 is $7."), c("$10", False, "The deposit is $25."), c("$12", False, "$12 is the member single-kayak rate."), c("$25", False, "$25 is the electric-bike deposit.")]},
            {"stem": "How far ahead can a renter reserve equipment online?", "skill_focus": "detail", "evidence": "you may reserve online up to 7 days in advance", "explanation": "Online reservations open up to a week ahead.", "choices": [c("Up to 7 days in advance", True, "This is the stated limit."), c("Up to 3 days in advance", False, "Three days is a rental term, not a booking window."), c("Only on the same day", False, "Advance booking is allowed."), c("Up to 2 weeks in advance", False, "The window is seven days.")]},
            {"stem": "What safety gear is included with a bicycle rental?", "skill_focus": "detail", "evidence": "a helmet with any bicycle", "explanation": "Helmets come with every bicycle rental.", "choices": [c("A life jacket", False, "Life jackets go with boats."), c("A helmet", True, "This is included with bicycles."), c("A padlock", False, "No padlock is mentioned."), c("A repair kit", False, "No kit is mentioned.")]},
            {"stem": "How much does a member pay to rent a double kayak for one day?", "skill_focus": "inference", "evidence": "A double kayak is charged as a canoe at the canoe rate plus $6", "explanation": "The canoe member rate is $14, so a double kayak is $14 plus $6, or $20.", "choices": [c("$14", False, "That is the plain canoe rate before the surcharge."), c("$20", True, "$14 canoe member rate plus the $6 surcharge."), c("$26", False, "That is the public double-kayak price."), c("$32", False, "That price is not indicated.")]},
        ],
    },
    {
        "slug": "single-stream-recycling-program",
        "task_type": "reading_information",
        "title": "Single-Stream Recycling Program",
        "topic": "Waste and the environment",
        "difficulty": 2,
        "estimated_level": 7,
        "instructions": "Read the information and answer the questions.",
        "stimulus": {
            "type": "article",
            "title": "Maplewood's new single-stream recycling program",
            "sections": [
                {"heading": "Overview", "body": "Starting March 1, Maplewood moves to single-stream recycling: paper, metal cans, and plastic containers are collected together in one blue cart. Weekly pickup dates do not change. The service is free for households that use the standard 240-litre cart; an extra second cart costs $3 per month."},
                {"heading": "What goes in the blue cart", "body": "Flatten cardboard boxes and set them inside the cart, not beside it. Rinse cans and containers, and you may leave the lids on plastic bottles. Paper, newspapers, and magazines can go in loose."},
                {"heading": "What stays out", "body": "Plastic bags and soft plastic wrap must not go in the cart; take them to the drop-off bins at participating grocery stores. Ceramics, window glass, and broken glass are not accepted. Batteries and electronics are hazardous and belong at the depot, never in the cart."},
                {"heading": "Contamination", "body": "A cart with more than 10 percent wrong items is tagged and left unemptied. Remove the wrong items and set the cart out again on your next scheduled pickup. Three tags in one year bring a written warning and a possible $75 fine."},
                {"heading": "Drop-off and bulky items", "body": "Take electronics to the Household Hazardous Waste depot on the first Saturday of each month from 9 a.m. to 1 p.m. Oversized cardboard is free to drop off at the transfer station if it is flattened and tied."},
                {"heading": "Apartment buildings", "body": "Buildings over six units switch to larger shared carts, and each building posts its own schedule in the lobby. A separate pilot collects organic food scraps weekly from these buildings, beginning in April."},
            ],
        },
        "learning_notes": "Distinguish what belongs in the cart from what must go to the depot or stores, and apply the contamination rule to the tagged-cart situation.",
        "questions": [
            {"stem": "What is the main purpose of the article?", "skill_focus": "gist", "evidence": "Maplewood moves to single-stream recycling ... What goes in the blue cart ... What stays out", "explanation": "The article explains the new recycling system and its rules.", "choices": [c("To advertise recycling bins for sale", False, "No bins are sold."), c("To explain a new single-stream recycling program", True, "The change and its rules organize the article."), c("To announce a garbage fee increase", False, "The standard cart is free."), c("To report a fire at the depot", False, "No such incident is mentioned.")]},
            {"stem": "What changes on March 1?", "skill_focus": "detail", "evidence": "Starting March 1, Maplewood moves to single-stream recycling", "explanation": "From that date, recyclables are collected together in one cart.", "choices": [c("Pickup day moves to Saturday", False, "Weekly pickup dates do not change."), c("Materials are collected together in one cart", True, "This is the single-stream change."), c("Recycling becomes pay-per-bag", False, "The standard cart stays free."), c("Glass collection stops", False, "The article says what glass is not accepted, not that glass pickup stops.")]},
            {"stem": "Which item is correctly placed in the blue cart?", "skill_focus": "detail", "evidence": "Flatten cardboard boxes and set them inside the cart ... Rinse cans and containers", "explanation": "Flattened cardboard and rinsed cans belong in the cart.", "choices": [c("A plastic bag full of cans", False, "Plastic bags must not go in the cart."), c("A battery", False, "Batteries are hazardous and go to the depot."), c("Flattened cardboard", True, "Flattened boxes go inside the cart."), c("A ceramic mug", False, "Ceramics are not accepted.")]},
            {"stem": "What should a resident do to containers before recycling them?", "skill_focus": "detail", "evidence": "Rinse cans and containers", "explanation": "Containers should be rinsed before going in the cart.", "choices": [c("Rinse them", True, "Rinsing is the stated step."), c("Remove all labels", False, "Label removal is not required."), c("Crush them flat", False, "Flattening is for cardboard."), c("Put them in a plastic bag", False, "Plastic bags are not allowed.")]},
            {"stem": "Where must plastic bags be taken?", "skill_focus": "detail", "evidence": "take them to the drop-off bins at participating grocery stores", "explanation": "Plastic bags go to grocery-store drop-off bins, not the cart.", "choices": [c("Into the blue cart", False, "They are banned from the cart."), c("To drop-off bins at participating grocery stores", True, "This is the stated location."), c("To the transfer station", False, "Oversized cardboard goes there."), c("To the Household Hazardous Waste depot", False, "Electronics go there.")]},
            {"stem": "What happens if a cart is more than 10 percent wrong items?", "skill_focus": "detail", "evidence": "A cart with more than 10 percent wrong items is tagged and left unemptied", "explanation": "The cart is tagged and not collected that day.", "choices": [c("It is emptied and fined", False, "It is not emptied at all."), c("It is tagged and left unemptied", True, "This is the stated rule."), c("It is collected the same day", False, "It stays until the next pickup."), c("The resident loses recycling service", False, "The resident can correct and reuse the cart.")]},
            {"stem": "What follows three tags in one year?", "skill_focus": "detail", "evidence": "Three tags in one year bring a written warning and a possible $75 fine", "explanation": "Three tags lead to a written warning and a possible fine.", "choices": [c("Immediate removal of the cart", False, "No removal is described."), c("A written warning and a possible $75 fine", True, "This is the stated consequence."), c("Free pickup for a month", False, "No reward is offered."), c("A visit from a recycling coach", False, "No coaching visit is mentioned.")]},
            {"stem": "When can residents drop off electronics at the depot?", "skill_focus": "detail", "evidence": "Take electronics to the Household Hazardous Waste depot on the first Saturday of each month from 9 a.m. to 1 p.m.", "explanation": "Electronics drop-off happens the first Saturday of each month.", "choices": [c("Every Saturday from 9 a.m. to 1 p.m.", False, "Only the first Saturday is offered."), c("The first Saturday of each month, 9 a.m. to 1 p.m.", True, "This matches the text."), c("Weekdays after 5 p.m.", False, "No weekday hours are given."), c("The last Sunday of each month", False, "It is the first Saturday.")]},
            {"stem": "What does the April pilot add for apartment buildings?", "skill_focus": "detail", "evidence": "A separate pilot collects organic food scraps weekly from these buildings, beginning in April", "explanation": "The pilot adds weekly organic-scrap collection for larger buildings.", "choices": [c("Weekly organic food-scrap collection", True, "This is the April pilot."), c("A second blue cart", False, "Second carts are a household option."), c("Daily garbage pickup", False, "No change to garbage is mentioned."), c("Free recycling bins", False, "No free bins are offered.")]},
        ],
    },
    {
        "slug": "red-light-camera-debate",
        "task_type": "reading_viewpoints",
        "title": "Should the City Install Red-Light Cameras?",
        "topic": "Traffic safety and privacy",
        "difficulty": 3,
        "estimated_level": 8,
        "instructions": "Compare the viewpoints and answer the questions.",
        "stimulus": {
            "type": "viewpoints",
            "title": "Should Maplewood install red-light cameras at its busiest intersections?",
            "background": "The city proposes installing red-light cameras at the twenty intersections with the most collisions. The cameras photograph and fine vehicles that run red lights.",
            "speakers": [
                {"name": "Mara Chen", "position": "Traffic safety advocate", "body": "I support the cameras. Where they have been used, side-impact collisions at monitored intersections fell by about a quarter, because the cameras deter drivers from racing the yellow light. A camera also enforces the law around the clock without an officer having to stop traffic to do it."},
                {"name": "Devon Watts", "position": "Delivery driver", "body": "I oppose the cameras as they are planned. Cameras make some drivers brake suddenly to avoid a ticket, which can cause rear-end crashes right behind the intersection. The city should fix the real problem by lengthening the yellow light at those corners instead of issuing fines."},
                {"name": "Priya Nair", "position": "Civil liberties researcher", "body": "Cameras can improve safety, but only if the program protects drivers' rights. I would support a pilot that pairs the cameras with clear warning signs, deletes the photos within days when no violation is found, and uses independent audits so enforcement does not unfairly target any group."},
            ],
        },
        "learning_notes": "Compare each speaker's predicted outcome and note which safeguards Priya ties to her support of a pilot.",
        "questions": [
            {"stem": "What is the speakers' main disagreement?", "skill_focus": "gist", "evidence": "Mara and Priya weigh safety gains; Devon worries cameras cause rear-end crashes and fines instead of fixing the cause.", "explanation": "They differ over whether red-light cameras are the right way to make intersections safer.", "choices": [c("Whether red lights are long enough", False, "Yellow-light length is only Devon's proposal."), c("Whether red-light cameras improve safety enough to justify them", True, "The speakers weigh safety against costs and risks."), c("Whether drivers should pay fines", False, "Fines are a detail of Devon's objection."), c("Whether intersections need lights", False, "All accept the lights exist.")]},
            {"stem": "What drop does Mara cite from cities that use the cameras?", "skill_focus": "detail", "evidence": "side-impact collisions at monitored intersections fell by about a quarter", "explanation": "Mara reports side-impact crashes falling by about a quarter.", "choices": [c("Rear-end crashes rose by half", False, "That is Devon's worry, not Mara's figure."), c("Side-impact collisions fell by about a quarter", True, "This is the study result she cites."), c("Speeds doubled", False, "No speed increase is claimed."), c("Traffic fines tripled", False, "She does not discuss revenue.")]},
            {"stem": "How does Mara say the cameras enforce the law?", "skill_focus": "detail", "evidence": "A camera also enforces the law around the clock without an officer having to stop traffic", "explanation": "The cameras work at all hours without halting traffic for enforcement.", "choices": [c("Only when an officer is present", False, "She says the opposite."), c("Around the clock without stopping traffic", True, "This is her stated point."), c("Only during rush hours", False, "No such limit is given."), c("By slowing every vehicle to a stop", False, "That would be stopping traffic.")]},
            {"stem": "Why does Devon oppose the cameras?", "skill_focus": "detail", "evidence": "Cameras make some drivers brake suddenly to avoid a ticket, which can cause rear-end crashes", "explanation": "He worries that ticket avoidance creates rear-end collisions.", "choices": [c("He believes cameras are illegal", False, "Legality is not his argument."), c("He thinks they cause rear-end crashes from sudden braking", True, "This is his stated concern."), c("He wants more red-light tickets", False, "He wants fewer fines."), c("He doubts cameras photograph anything", False, "He assumes they work.")]},
            {"stem": "What does Devon say is the real problem to fix?", "skill_focus": "detail", "evidence": "The city should fix the real problem by lengthening the yellow light at those corners", "explanation": "Devon proposes longer yellow lights instead of fines.", "choices": [c("Drivers who are distracted", False, "Distraction is not his point."), c("Yellow lights that are too short", True, "Lengthening the yellow is his fix."), c("Poor road signs", False, "Signage is Priya's concern."), c("Narrow lanes", False, "Lane width is not discussed.")]},
            {"stem": "Under what condition would Priya support the cameras?", "skill_focus": "detail", "evidence": "I would support a pilot that pairs the cameras with clear warning signs ... and uses independent audits", "explanation": "Priya supports only a pilot that includes safeguards for drivers.", "choices": [c("A pilot with signs, short photo retention, and independent audits", True, "These are her stated safeguards."), c("Cameras at every intersection with no limits", False, "She favours a limited pilot."), c("Cameras only at night", False, "Time of day is not a condition."), c("A complete ban on camera fines", False, "She does not oppose all camera enforcement.")]},
            {"stem": "Which concern does Priya raise that the others do not?", "skill_focus": "inference", "evidence": "independent audits so enforcement does not unfairly target any group", "explanation": "Priya alone worries that enforcement might be biased against particular groups.", "choices": [c("That enforcement might unfairly target some groups", True, "This is her unique concern."), c("That the cameras might not catch anyone", False, "That is not her worry."), c("That traffic would increase", False, "No one raises that."), c("That the fines are too high", False, "She does not discuss fine amounts.")]},
            {"stem": "How many intersections would the proposal cover?", "skill_focus": "detail", "evidence": "installing red-light cameras at the twenty intersections with the most collisions", "explanation": "The proposal targets the twenty worst intersections for collisions.", "choices": [c("All intersections in the city", False, "The plan is limited."), c("Twenty intersections with the most collisions", True, "This matches the background."), c("Ten intersections downtown", False, "No downtown limit is stated."), c("Only school zones", False, "School zones are not specified.")]},
            {"stem": "In Mara's argument, the word 'deter' most nearly means", "skill_focus": "vocabulary", "evidence": "the cameras deter drivers from racing the yellow light", "explanation": "Deter means to discourage people from doing something.", "choices": [c("reward", False, "Cameras do not reward."), c("discourage", True, "The cameras make drivers less willing to race the light."), c("delay", False, "Delay is not the meaning."), c("record", False, "Recording is what the camera does, not what deter means.")]},
            {"stem": "What can be inferred about Devon's view of fines?", "skill_focus": "inference", "evidence": "instead of issuing fines ... lengthening the yellow light at those corners", "explanation": "Devon prefers fixing signal timing over punishing drivers with fines.", "choices": [c("He prefers fixing signal timing over fining drivers", True, "His alternative replaces fines with longer yellow lights."), c("He wants higher fines to slow drivers", False, "He wants fewer fines."), c("He believes fines should fund cameras", False, "No funding link is made."), c("He thinks fines are the main cause of crashes", False, "He blames sudden braking, not the fines themselves.")]},
        ],
    },
]
