"""Official-size Reading parts for full-length mock simulations.

Each set is one complete official CELPIP-General Reading part: a single email,
table, information text, or viewpoints passage with the full official question
count (Part 1 correspondence 11, Part 2 apply a diagram/table 8, Part 3
information 9, Part 4 viewpoints 10). A full-length mock should use each of
these as one part rather than splicing several unrelated short sets together.

All scenarios, texts, questions, and explanations in this module are original
to this repository. The shape of each item matches ``reading_seed_data_v2.py``
so the existing seeding command can consume it unchanged.
"""


def c(text, correct, explanation):
    return {"text": text, "is_correct": correct, "explanation": explanation}


READING_OFFICIAL_SETS = [
    {
        "slug": "pool-renovation-relocation-email",
        "task_type": "reading_correspondence",
        "title": "Pool Renovation and Relocation Email",
        "topic": "Community recreation",
        "difficulty": 2,
        "estimated_level": 7,
        "instructions": "Read the email and answer the questions.",
        "stimulus": {
            "type": "email",
            "from": "Cedar Falls Leisure Centre",
            "to": "Alex Morgan",
            "subject": "Pool closure and temporary relocation",
            "body": "Dear Alex,\n\nStarting Monday, September 7, the main indoor pool will close for six weeks while crews replace the filtration system and add a new accessible ramp. During the closure, lane swimming and your aqua fitness classes move to the Westside pool, about ten minutes away by car.\n\nYour membership stays active, and to help cover the added travel each member will receive two free day passes, valid until December 31. On your first visit to Westside, bring your membership card to the front desk so the staff can register you there. Lane reservations at Westside open every Friday at 9 a.m. for the following week, and you may book up to two lanes per day.\n\nAqua fitness schedules shift by one hour later at Westside; the updated timetable is posted at both centres and in the centre's app. Private lessons already booked for September will be rescheduled automatically, and you will receive the new times within five business days. If you would prefer a refund for those lessons instead, reply to this email by August 30.\n\nThe poolside café will stay open, and the gym and studios are unaffected.\n\nWe apologize for the disruption and hope to see you at Westside soon.\n\nSincerely,\nThe Cedar Falls Leisure Centre Team",
        },
        "learning_notes": "Separate the automatic arrangements from the optional actions Alex must take (first-visit registration, refund reply).",
        "questions": [
            {"stem": "What is the main purpose of the email?", "skill_focus": "gist", "evidence": "the main indoor pool will close ... lane swimming and your aqua fitness classes move to the Westside pool", "explanation": "The email tells Alex about the closure and how swimming continues during it.", "choices": [c("To announce that the centre is closing permanently", False, "Only the pool closes, and only temporarily."), c("To explain a pool closure and how swimming will continue", True, "The closure, relocation, and arrangements are all covered."), c("To request payment for a membership renewal", False, "No payment is requested."), c("To advertise the poolside café menu", False, "The café is only mentioned in passing.")]},
            {"stem": "Why is the main indoor pool closing?", "skill_focus": "detail", "evidence": "crews replace the filtration system and add a new accessible ramp", "explanation": "The closure allows renovation work on the filtration system and accessibility.", "choices": [c("For routine staff training", False, "No training is mentioned."), c("To replace the filtration system and add an accessible ramp", True, "These are the stated renovation tasks."), c("To expand the poolside café", False, "The café stays open, not expanded."), c("To repair the parking lot", False, "The work is inside the pool.")]},
            {"stem": "How long will the pool be closed?", "skill_focus": "detail", "evidence": "will close for six weeks", "explanation": "The closure lasts six weeks.", "choices": [c("Three weeks", False, "That is shorter than stated."), c("Four weeks", False, "The email says six weeks."), c("Six weeks", True, "This matches the text."), c("Until December 31", False, "December 31 is the pass expiry, not the reopening.")]},
            {"stem": "Where will lane swimming and aqua fitness take place during the closure?", "skill_focus": "detail", "evidence": "lane swimming and your aqua fitness classes move to the Westside pool", "explanation": "Both activities are relocated to the Westside pool.", "choices": [c("At the poolside café", False, "The café is not a swimming location."), c("At the gym", False, "The gym is unaffected and separate."), c("At the Westside pool", True, "This is stated directly."), c("In the studios", False, "The studios are unaffected by the move.")]},
            {"stem": "What does each member receive to help with the added travel?", "skill_focus": "detail", "evidence": "to help cover the added travel each member will receive two free day passes, valid until December 31", "explanation": "Members are given two free day passes as compensation for travelling further.", "choices": [c("A free parking permit", False, "No parking permit is offered."), c("Two free day passes valid until December 31", True, "This matches the stated offer."), c("A discount on the next membership year", False, "No membership discount is mentioned."), c("A café voucher", False, "No voucher is offered.")]},
            {"stem": "What must Alex do on the first visit to Westside?", "skill_focus": "detail", "evidence": "bring your membership card to the front desk so the staff can register you there", "explanation": "Bringing the card allows the staff to register Alex at Westside.", "choices": [c("Book two lanes online in advance", False, "Lane booking is separate and not a first-visit requirement."), c("Bring the membership card to the front desk to register", True, "This is the stated first-visit step."), c("Pay a relocation fee", False, "No fee is mentioned."), c("Complete a swimming test", False, "No test is required.")]},
            {"stem": "When can members book lane reservations at Westside?", "skill_focus": "detail", "evidence": "Lane reservations at Westside open every Friday at 9 a.m. for the following week", "explanation": "Reservations open weekly on Friday morning for the next week.", "choices": [c("Every Friday at 9 a.m. for the following week", True, "This matches the reservation rule."), c("Daily after 5 p.m.", False, "The email gives a weekly opening, not a daily one."), c("Every Monday at 7 a.m.", False, "The opening day is Friday."), c("Once per month on the first day", False, "Reservations open weekly.")]},
            {"stem": "What happens to private lessons already booked for September?", "skill_focus": "detail", "evidence": "Private lessons already booked for September will be rescheduled automatically", "explanation": "The centre reschedules those lessons without requiring action.", "choices": [c("They are cancelled and refunded automatically", False, "Only the refund option requires a reply."), c("They are rescheduled automatically with new times", True, "This is stated directly."), c("They continue at the main pool", False, "The main pool is closed."), c("Members must rebook them online", False, "No member action is required for the default.")]},
            {"stem": "Why does the centre offer members free day passes?", "skill_focus": "inference", "evidence": "to help cover the added travel each member will receive two free day passes", "explanation": "Members must travel to another pool, so the passes repay the extra inconvenience.", "choices": [c("To repay members for the extra travel the closure causes", True, "The passes are explicitly tied to the added travel."), c("To reward members who renew early", False, "No renewal link is mentioned."), c("To advertise the Westside café", False, "The passes are for swimming access."), c("To replace lost membership cards", False, "Cards are not replaced by passes.")]},
            {"stem": "What must Alex do by August 30 to receive a refund for the private lessons?", "skill_focus": "detail", "evidence": "If you would prefer a refund for those lessons instead, reply to this email by August 30", "explanation": "The refund requires replying to the email before the deadline.", "choices": [c("Return the membership card", False, "No return is requested."), c("Reply to the email", True, "This is the stated action."), c("Visit the front desk", False, "The refund request is by email reply."), c("Call the poolside café", False, "The café is not involved in bookings.")]},
            {"stem": "In the email, the word 'unaffected' most nearly means", "skill_focus": "vocabulary", "evidence": "the gym and studios are unaffected", "explanation": "Unaffected means not changed by the pool work.", "choices": [c("closed temporarily", False, "Unaffected means the opposite of closed for work."), c("not changed", True, "The gym and studios continue as before."), c("newly opened", False, "Nothing is being newly opened."), c("slightly delayed", False, "Delay is not the meaning here.")]},
        ],
    },
    {
        "slug": "community-garden-plot-registration",
        "task_type": "reading_apply_diagram",
        "title": "Community Garden Plot Registration",
        "topic": "Community gardening",
        "difficulty": 2,
        "estimated_level": 7,
        "instructions": "Use the table to answer the questions.",
        "stimulus": {
            "type": "table",
            "title": "Maplewood community garden plots",
            "columns": ["Plot type", "Annual fee", "Water", "Good for", "Notes"],
            "rows": [
                ["Plot A (3 m x 2 m)", "$30", "Shared tap", "Beginners", "No raised beds; no shed"],
                ["Plot B (3 m x 6 m)", "$55", "Hose on site", "Small families", "Up to two gardeners"],
                ["Plot C (3 m x 12 m)", "$90", "Hose on site", "Experienced growers", "Two-year waitlist"],
                ["Raised beds (1 m x 2 m)", "$25", "Shared tap", "Gardeners with limited mobility", "Fully accessible; eight beds"],
            ],
            "notes": "Open to Maplewood ward residents. Registration opens online on March 1. Pay the annual fee within 10 days of receiving your offer to keep the plot. Tools are shared; a seasonal locker costs $10. Plots must be planted, and produce may be grown for personal use only.",
        },
        "learning_notes": "Read the chosen row across all columns, then apply the notes about deadlines, lockers, and use rules.",
        "questions": [
            {"stem": "Which plot type is described as suitable for a first-time gardener?", "skill_focus": "detail", "evidence": "Plot A ... Good for: Beginners", "explanation": "Plot A is the option matched to beginners.", "choices": [c("Plot A", True, "The table lists Plot A as good for beginners."), c("Plot B", False, "Plot B is for small families."), c("Plot C", False, "Plot C suits experienced growers."), c("Raised beds", False, "Raised beds are for gardeners with limited mobility.")]},
            {"stem": "How many gardeners may share a Plot B?", "skill_focus": "detail", "evidence": "Plot B ... Up to two gardeners", "explanation": "Plot B allows up to two gardeners.", "choices": [c("One", False, "Two are allowed."), c("Two", True, "This is stated in the Plot B notes."), c("Four", False, "The limit is two."), c("No limit", False, "A limit is stated.")]},
            {"stem": "Which plot type currently has a two-year waitlist?", "skill_focus": "detail", "evidence": "Plot C ... Two-year waitlist", "explanation": "Plot C is the only option with the stated waitlist.", "choices": [c("Plot A", False, "Plot A has no waitlist noted."), c("Plot B", False, "Plot B has no waitlist noted."), c("Plot C", True, "This matches the Plot C row."), c("Raised beds", False, "Raised beds have no waitlist noted.")]},
            {"stem": "Which option is fully accessible?", "skill_focus": "detail", "evidence": "Raised beds ... Fully accessible", "explanation": "The raised beds are described as fully accessible.", "choices": [c("Plot A", False, "Plot A is not marked accessible."), c("Plot B", False, "Plot B is not marked accessible."), c("Plot C", False, "Plot C is not marked accessible."), c("Raised beds", True, "This is stated directly.")]},
            {"stem": "Which plot would best suit a gardener who finds bending down difficult?", "skill_focus": "inference", "evidence": "Raised beds ... Fully accessible; good for gardeners with limited mobility", "explanation": "Raised beds raise the growing surface, so a gardener who avoids bending is better served there.", "choices": [c("Plot A", False, "Plot A is a ground-level plot."), c("Plot C", False, "Plot C is a large ground-level plot."), c("Raised beds", True, "Raised beds are the accessible option."), c("Any plot equally", False, "The table distinguishes the raised beds by accessibility.")]},
            {"stem": "By when must the annual fee be paid after an offer?", "skill_focus": "detail", "evidence": "Pay the annual fee within 10 days of receiving your offer to keep the plot", "explanation": "The fee is due within 10 days of the offer.", "choices": [c("Immediately on March 1", False, "March 1 is when registration opens."), c("Within 10 days of receiving the offer", True, "This is the stated deadline."), c("By the end of the season", False, "Payment is required much sooner."), c("Within one month", False, "The window is 10 days.")]},
            {"stem": "How much does a seasonal locker cost?", "skill_focus": "detail", "evidence": "a seasonal locker costs $10", "explanation": "The locker fee is $10 per season.", "choices": [c("$10", True, "This is stated in the notes."), c("$25", False, "$25 is the raised-bed fee."), c("$55", False, "$55 is Plot B's annual fee."), c("No charge", False, "A fee is stated.")]},
            {"stem": "What rule applies to produce grown in the plots?", "skill_focus": "detail", "evidence": "produce may be grown for personal use only", "explanation": "Growers may use the produce for themselves, not for sale.", "choices": [c("It must be shared with neighbours", False, "No sharing rule is stated."), c("It may be grown for personal use only", True, "This is the stated rule."), c("It must be donated to a food bank", False, "No donation requirement appears."), c("It may be sold at a market", False, "Selling is not allowed.")]},
        ],
    },
    {
        "slug": "lakeside-beach-safety-notice",
        "task_type": "reading_information",
        "title": "Lakeside Beach Safety Notice",
        "topic": "Public health and safety",
        "difficulty": 2,
        "estimated_level": 7,
        "instructions": "Read the information and answer the questions.",
        "stimulus": {
            "type": "article",
            "title": "Lakeside Beach water quality and safety",
            "sections": [
                {"heading": "Overview", "body": "This summer, Lakeside Beach is open daily from 10 a.m. to 8 p.m., and swimming is free. The city tests the water every day at three points along the beach and posts the results on signs and in the city app."},
                {"heading": "Testing and closures", "body": "An advisory is posted when bacteria levels rise above the guideline. During an advisory, swimming is discouraged, especially for children, older adults, and people with weakened immune systems. The beach is closed to swimming only when an advisory lasts more than three days or when a serious pollution event occurs, such as a sewage overflow."},
                {"heading": "Warning flags", "body": "Green flag: beach open. Yellow flag: advisory in effect, swim at your own risk. Red flag: beach closed. Purple flag: dangerous marine life reported, stay out of the water."},
                {"heading": "Safety rules", "body": "Swim between the marked buoys, where lifeguards are on duty from noon to 7 p.m. Glass containers and alcohol are not allowed on the sand. Children under 12 must stay within arm's reach of an adult."},
                {"heading": "Keeping it clean", "body": "Bring a refillable water bottle; the beach has filling stations. Take your garbage with you or use the bins near the boardwalk. Keep dogs on a leash and away from the swimming areas between 10 a.m. and 6 p.m."},
                {"heading": "Health advice", "body": "Shower after swimming and dry your ears. If you ingest lake water and develop a fever or stomach illness within 48 hours, see a doctor and mention that you visited the beach."},
            ],
        },
        "learning_notes": "Match each flag and rule to the condition it signals, and separate routine advice from closure conditions.",
        "questions": [
            {"stem": "What is the main purpose of the notice?", "skill_focus": "gist", "evidence": "The sections cover water testing, warning flags, safety rules, and health advice.", "explanation": "The notice explains how the beach keeps swimmers informed and safe.", "choices": [c("To advertise beach rentals", False, "No rentals are offered."), c("To explain water testing, warning flags, and safety rules", True, "These topics organize the notice."), c("To report a recent sewage overflow", False, "Overflow is only an example of a closure trigger."), c("To announce the beach is closing permanently", False, "The beach is open daily.")]},
            {"stem": "How often is the beach water tested?", "skill_focus": "detail", "evidence": "The city tests the water every day at three points along the beach", "explanation": "Testing happens daily at three locations.", "choices": [c("Once a week", False, "Testing is daily."), c("Every day at three points", True, "This is stated directly."), c("Only during advisories", False, "Advisories result from the tests, not the other way around."), c("Every hour", False, "Testing is daily, not hourly.")]},
            {"stem": "Which group is singled out as needing extra care during an advisory?", "skill_focus": "detail", "evidence": "swimming is discouraged, especially for children, older adults, and people with weakened immune systems", "explanation": "The notice names these groups as more at risk.", "choices": [c("Teenagers in training", False, "No such group is named."), c("Children, older adults, and people with weakened immune systems", True, "These groups are listed as especially at risk."), c("Trained lifeguards", False, "Lifeguards supervise rather than needing extra care."), c("Dog owners", False, "Dog owners are covered by a separate leash rule.")]},
            {"stem": "When is the beach closed to swimming?", "skill_focus": "detail", "evidence": "closed to swimming only when an advisory lasts more than three days or when a serious pollution event occurs", "explanation": "Closure requires either a long advisory or a serious pollution event.", "choices": [c("Whenever an advisory is posted", False, "A short advisory only discourages swimming."), c("After any overnight storm", False, "Storms are not a closure trigger."), c("When an advisory lasts over three days or a serious pollution event occurs", True, "Both triggers are listed."), c("When lifeguards go off duty", False, "Hours affect supervision, not closure.")]},
            {"stem": "What does a red flag mean at the beach?", "skill_focus": "detail", "evidence": "Red flag: beach closed", "explanation": "The red flag signals the beach is closed.", "choices": [c("Beach open", False, "Green is open."), c("Advisory in effect", False, "Yellow is the advisory."), c("Beach closed", True, "This is what red signals."), c("Dangerous marine life", False, "Purple signals marine life.")]},
            {"stem": "Where are lifeguards on duty?", "skill_focus": "detail", "evidence": "Swim between the marked buoys, where lifeguards are on duty from noon to 7 p.m.", "explanation": "Lifeguards patrol the buoyed swimming area.", "choices": [c("Along the whole shoreline", False, "The notice ties lifeguards to the buoyed area."), c("Between the marked buoys from noon to 7 p.m.", True, "This matches the text."), c("At the filling stations", False, "Filling stations are for water, not lifeguards."), c("Near the boardwalk bins", False, "The boardwalk is a waste area.")]},
            {"stem": "Why are swimmers told to stay between the buoys?", "skill_focus": "inference", "evidence": "Swim between the marked buoys, where lifeguards are on duty", "explanation": "The buoyed zone is the area that lifeguards can watch.", "choices": [c("Because the buoys mark the patrolled swimming area", True, "Lifeguard coverage is the stated reason."), c("Because the sand is closed", False, "The sand has its own rules."), c("Because dogs swim there", False, "Dogs are kept away from swimming areas."), c("Because the water is shallowest there", False, "Depth is not mentioned.")]},
            {"stem": "What rule applies to children under 12?", "skill_focus": "detail", "evidence": "Children under 12 must stay within arm's reach of an adult", "explanation": "Young children must remain close to an adult.", "choices": [c("They must wear a life jacket", False, "No life-jacket rule is stated."), c("They must stay within arm's reach of an adult", True, "This is the stated rule."), c("They may swim only before noon", False, "No time rule for children appears."), c("They must stay on the boardwalk", False, "The rule concerns the water.")]},
            {"stem": "In the notice, the word 'ingested' most nearly means", "skill_focus": "vocabulary", "evidence": "If you swallow lake water ... within 48 hours", "explanation": "Ingested refers to taking the water into the body by swallowing.", "choices": [c("swallowed", True, "This matches the health advice."), c("touched", False, "Skin contact is not what is described."), c("smelled", False, "Smelling is unrelated."), c("heard", False, "Hearing is unrelated.")]},
        ],
    },
    {
        "slug": "gas-lawn-equipment-ban-debate",
        "task_type": "reading_viewpoints",
        "title": "Should Gas Lawn Equipment Be Banned?",
        "topic": "Environment and health",
        "difficulty": 3,
        "estimated_level": 8,
        "instructions": "Compare the viewpoints and answer the questions.",
        "stimulus": {
            "type": "viewpoints",
            "title": "Should Maplewood phase out gas-powered lawn equipment?",
            "background": "The town is considering a bylaw that would phase out gas-powered leaf blowers and mowers over three years to cut noise and emissions.",
            "speakers": [
                {"name": "Ana Ribeiro", "position": "Resident and parent", "body": "I support the phase-out. Gas leaf blowers are loud enough to interrupt sleep and schoolwork in our neighbourhood, and their exhaust hangs around yards where children play. Battery tools are quieter and cleaner, and three years is enough time for everyone to switch."},
                {"name": "Marcus Bell", "position": "Landscaping company owner", "body": "I oppose a forced ban. Switching our whole fleet to battery would be very expensive, and the batteries do not yet last through a full day of large commercial jobs. My service prices would have to rise. The town should offer rebates and let businesses choose for themselves instead."},
                {"name": "Dr. Lena Park", "position": "Family physician", "body": "I support the phase-out as a health measure. The small engines in these tools release fine particles and fumes that are linked to asthma, and I see patients who live near landscaped areas worsen every summer. A gradual ban is like past limits on smoking and vehicle idling: it protects people's lungs."},
            ],
        },
        "learning_notes": "Separate each speaker's predicted cost or benefit and connect their role to their argument.",
        "questions": [
            {"stem": "What is the speakers' main disagreement?", "skill_focus": "gist", "evidence": "Ana and Dr. Park weigh noise, emissions, and health; Marcus weighs cost and choice.", "explanation": "They disagree about whether the public benefits justify forcing businesses to switch equipment.", "choices": [c("Whether gas mowers are powerful enough", False, "Power is not disputed."), c("Whether a forced phase-out is worth its cost to businesses", True, "The speakers weigh health and noise against cost and choice."), c("Whether lawns need cutting", False, "All accept lawns are maintained."), c("Whether battery tools exist", False, "Battery tools are discussed as available.")]},
            {"stem": "Why does Ana support the phase-out?", "skill_focus": "detail", "evidence": "loud enough to interrupt sleep and schoolwork ... exhaust hangs around yards where children play", "explanation": "Ana objects to the noise and exhaust that affect her neighbourhood.", "choices": [c("Gas tools are too expensive", False, "Cost is Marcus's concern."), c("The noise and exhaust disturb children and daily life", True, "Both are stated reasons."), c("She owns a battery company", False, "No business interest is mentioned."), c("She wants lawns removed", False, "She wants quieter tools, not no lawns.")]},
            {"stem": "Why does Marcus oppose the phase-out?", "skill_focus": "detail", "evidence": "Switching our whole fleet to battery would be very expensive, and the batteries do not yet last through a full day", "explanation": "Marcus cites the upfront cost and limited battery life for commercial work.", "choices": [c("He dislikes quieter tools", False, "He does not object to quieter tools."), c("Battery equipment is expensive and batteries run out on big jobs", True, "Both reasons are explicit."), c("He wants more gas-powered jobs", False, "He wants choice, not more gas work."), c("He doubts gas tools harm health", False, "He does not address the health claim directly.")]},
            {"stem": "What health concern does Dr. Park raise?", "skill_focus": "detail", "evidence": "fine particles and fumes that are linked to asthma", "explanation": "She ties the engine emissions to asthma, especially in nearby residents.", "choices": [c("Skin irritation from grass", False, "No skin issue is mentioned."), c("Fine particles and fumes linked to asthma", True, "This is her stated concern."), c("Hearing loss in users only", False, "She focuses on nearby residents' lungs."), c("Injuries from the equipment", False, "No injury concern is raised.")]},
            {"stem": "Over how long would the phase-out happen?", "skill_focus": "detail", "evidence": "phase out gas-powered leaf blowers and mowers over three years", "explanation": "The proposed bylaw would take effect gradually over three years.", "choices": [c("Immediately", False, "The plan is gradual."), c("One year", False, "The plan spans three years."), c("Three years", True, "This matches the background."), c("Five years", False, "That is longer than proposed.")]},
            {"stem": "What can be inferred from Ana's mention of schoolwork?", "skill_focus": "inference", "evidence": "loud enough to interrupt sleep and schoolwork in our neighbourhood", "explanation": "She implies the daytime noise reaches homes where people study and rest.", "choices": [c("Lawn work happens near homes where people study", True, "The noise interrupting schoolwork must reach homes."), c("Her children attend school at the beach", False, "No location detail supports this."), c("Gas tools are used indoors", False, "The tools are used on lawns."), c("Schools are closed in summer", False, "Schoolwork could be done at home.")]},
            {"stem": "What can be inferred about Marcus's preferred solution?", "skill_focus": "inference", "evidence": "The town should offer rebates and let businesses choose for themselves instead", "explanation": "Marcus wants encouragement through rebates rather than a forced rule.", "choices": [c("He wants incentives and free choice, not a ban", True, "Rebates plus choice is his stated preference."), c("He wants the town to ban battery tools", False, "He uses battery tools as the alternative."), c("He wants higher gas prices", False, "He does not propose pricing gas."), c("He wants to close his business", False, "He wants to keep working affordably.")]},
            {"stem": "Why does Dr. Park compare the phase-out to past limits on smoking and idling?", "skill_focus": "inference", "evidence": "A gradual ban is like past limits on smoking and vehicle idling: it protects people's lungs", "explanation": "She sees these earlier restrictions as health protections that were eventually accepted.", "choices": [c("To argue the ban protects public health like earlier limits", True, "She frames the phase-out as a proven kind of health rule."), c("To claim gas tools are as dangerous as smoking indoors", False, "She compares the type of remedy, not the risk level."), c("To suggest the town ignore the ban", False, "She supports the ban."), c("To show lawn care is a new activity", False, "The comparison is about public-health rules.")]},
            {"stem": "What does Marcus claim would happen to his prices if the ban passed?", "skill_focus": "detail", "evidence": "My service prices would have to rise", "explanation": "Marcus says higher equipment costs would be passed on to customers.", "choices": [c("They would stay the same", False, "He expects them to rise."), c("They would have to rise", True, "This is his stated prediction."), c("They would fall as fuel costs drop", False, "He predicts the opposite."), c("He would stop charging", False, "No such claim appears.")]},
            {"stem": "In the debate, a three-year 'phase-out' most nearly means", "skill_focus": "vocabulary", "evidence": "phase out gas-powered leaf blowers and mowers over three years", "explanation": "A phase-out gradually ends the use of the equipment over the period.", "choices": [c("stopping use gradually over that period", True, "A phase-out removes something step by step."), c("banning the equipment immediately", False, "The plan is gradual, not immediate."), c("reducing the price of the equipment", False, "Cost is not part of the meaning."), c("encouraging more gas use", False, "The direction is away from gas.")]},
        ],
    },
]
