"""Expanded original Reading content for the full practice bank.

All scenarios, texts, questions, and explanations in this module are original to
this repository. The shape of each item matches ``backend/apps/content/seed_data.py``
so the existing seeding and validation commands can consume it unchanged.
"""


def c(text, correct, explanation):
    return {"text": text, "is_correct": correct, "explanation": explanation}


READING_SETS = [
    {
        "slug": "community-centre-membership-freeze",
        "task_type": "reading_correspondence",
        "title": "Community Centre Membership Freeze",
        "topic": "Community recreation",
        "difficulty": 2,
        "estimated_level": 7,
        "instructions": "Read the email and answer the questions.",
        "stimulus": {
            "type": "email",
            "from": "Riverside Community Centre",
            "to": "Alex Morgan",
            "subject": "Your membership freeze request",
            "body": "Dear Alex,\n\nWe have approved your request to freeze your annual membership for up to six months while you recover from knee surgery. Your account will be paused on October 1, so no charges or expiry time will run from that date.\n\nTo keep your spot, complete the online freeze form before September 28. You will still receive one guest pass per month, but you must collect it at the front desk. On your return, email us at membership@riverside.ca at least five business days before your first visit so we can reactivate your card.\n\nClasses already booked are cancelled automatically, and any refunds will appear on your original payment method within ten business days.\n\nBest wishes for your recovery,\nThe Membership Team",
        },
        "learning_notes": "Distinguish the approval from the actions Alex must complete before and after the freeze.",
        "questions": [
            {"stem": "What is the main purpose of the email?", "skill_focus": "gist", "evidence": "We have approved your request ... To keep your spot, complete the online freeze form", "explanation": "The email confirms the approval and explains the steps to freeze and later reactivate the membership.", "choices": [c("To advertise a new exercise program", False, "No program is advertised."), c("To confirm the membership freeze and explain the process", True, "Approval, the form deadline, guest passes, and reactivation are all covered."), c("To request payment for knee surgery", False, "The surgery is only context for the request."), c("To cancel the community centre entirely", False, "Only the membership is paused.")]},
            {"stem": "What must Alex do by September 28?", "skill_focus": "detail", "evidence": "complete the online freeze form before September 28", "explanation": "The form is the required action to keep the membership spot.", "choices": [c("Complete the online freeze form", True, "This is stated as the requirement for keeping the spot."), c("Book the first class after recovery", False, "No return date is known yet."), c("Collect the monthly guest pass", False, "The pass is an ongoing benefit, not a deadline task."), c("Pay a small reactivation fee", False, "No reactivation fee is mentioned.")]},
            {"stem": "Why must Alex notify the centre before returning?", "skill_focus": "inference", "evidence": "email us ... at least five business days before your first visit so we can reactivate your card", "explanation": "The centre needs advance notice to prepare the card for access.", "choices": [c("To reserve a private changing room", False, "No room reservation is mentioned."), c("To get the membership card ready in time", True, "The stated reason is to reactivate the card."), c("To extend the freeze for another six months", False, "The notice concerns returning, not extending."), c("To request a refund for missed classes", False, "Refunds are automatic and unrelated to the notice.")]},
            {"stem": "What happens to classes that were already booked?", "skill_focus": "detail", "evidence": "Classes already booked are cancelled automatically", "explanation": "The centre handles the cancellations without additional action.", "choices": [c("They remain active until Alex returns", False, "The email says they are cancelled."), c("They are cancelled automatically", True, "This is stated directly."), c("Alex must cancel each one by phone", False, "No manual cancellation is required."), c("They are moved to a later month", False, "No rescheduling is offered.")]},
        ],
    },
    {
        "slug": "school-museum-trip-consent",
        "task_type": "reading_correspondence",
        "title": "School Museum Trip Consent",
        "topic": "Education and family",
        "difficulty": 1,
        "estimated_level": 6,
        "instructions": "Read the email and answer the questions.",
        "stimulus": {
            "type": "email",
            "from": "Maple Grove Elementary School",
            "to": "Parents and guardians",
            "subject": "Museum trip permission reminder",
            "body": "Dear families,\n\nGrade 5 students will visit the Provincial Museum on Friday, November 14. Buses leave at 8:45 a.m. and return by 2:30 p.m.\n\nTo allow your child to attend, please sign the online permission form and pay the $12 admission fee by Tuesday, November 4. The fee covers museum entry and a guided workshop; lunch is not provided, so send a bagged lunch and a water bottle.\n\nStudents must wear a school shirt and comfortable walking shoes. The museum is indoors, but we will walk two blocks from the bus drop-off, so check the forecast for rain. If you can volunteer as a group supervisor, indicate this on the form; all volunteers need a current police record check on file.\n\nFor questions, contact the school office.\n\nThank you,\nMaple Grove staff",
        },
        "learning_notes": "Track deadlines, what the fee includes, and what each family still needs to provide.",
        "questions": [
            {"stem": "Why was the email sent?", "skill_focus": "purpose", "evidence": "please sign the online permission form and pay the $12 admission fee by Tuesday, November 4", "explanation": "The message tells families how to allow their child to participate.", "choices": [c("To report a school closure", False, "No closure is mentioned."), c("To explain the permission, payment, and preparation for the trip", True, "All three practical areas are covered."), c("To hire museum tour guides", False, "The school is not hiring."), c("To cancel the November trip", False, "The trip is still planned.")]},
            {"stem": "What does the $12 fee include?", "skill_focus": "detail", "evidence": "The fee covers museum entry and a guided workshop", "explanation": "Entry and the workshop are both covered by the fee.", "choices": [c("Bus travel and a water bottle", False, "Neither is included in the stated fee."), c("Museum entry and a guided workshop", True, "Both are listed as covered."), c("A bagged lunch and school shirt", False, "Lunch is not provided."), c("A museum souvenir and a rain jacket", False, "No souvenir or rain jacket is mentioned.")]},
            {"stem": "Why do volunteers need a police record check?", "skill_focus": "inference", "evidence": "all volunteers need a current police record check on file", "explanation": "The school requires a background check before adults supervise students.", "choices": [c("To receive a discount on admission", False, "The record check is not tied to a discount."), c("To prove they can drive the bus", False, "The record check does not concern driving."), c("To meet the school's child-safety requirements", True, "The check is a standard safeguard for adults working with children."), c("To reserve a museum seat", False, "No seat reservation is connected to the check.")]},
            {"stem": "What should students bring on the trip?", "skill_focus": "detail", "evidence": "send a bagged lunch and a water bottle", "explanation": "Families must provide food because lunch is not included.", "choices": [c("A bagged lunch and a water bottle", True, "Both are requested."), c("A school shirt and museum ticket", False, "The fee covers admission; the shirt is worn, not brought separately."), c("A police record check and a signed form", False, "Those apply to volunteers and permission."), c("A laptop and headphones", False, "No electronic items are requested.")]},
        ],
    },
    {
        "slug": "online-bank-statement-change",
        "task_type": "reading_correspondence",
        "title": "Online Bank Statement Change",
        "topic": "Personal finance",
        "difficulty": 1,
        "estimated_level": 5,
        "instructions": "Read the email and answer the questions.",
        "stimulus": {
            "type": "email",
            "from": "North Shore Credit Union",
            "to": "Sam Whitfield",
            "subject": "Your statement delivery is changing",
            "body": "Dear Sam,\n\nStarting next month, your monthly account statement will be sent only to your secure online inbox. Paper statements will be discontinued to reduce waste and mailing costs.\n\nIf you prefer paper, log in and update your delivery preference by September 30. Paper statements cost $2 per month and are mailed to the address we have on file. You can also download any statement from the last seven years at no charge.\n\nFor members who rely on mailed statements for immigration or proof of address, we can issue a free official statement letter once per calendar year. To request one, book a branch appointment.\n\nYour automatic deposits and payments are unaffected.\n\nSincerely,\nNorth Shore Credit Union",
        },
        "learning_notes": "Separate the default change from the optional paper route and the special official-letter exception.",
        "questions": [
            {"stem": "What change is being made to Sam's statements?", "skill_focus": "gist", "evidence": "your monthly account statement will be sent only to your secure online inbox", "explanation": "The credit union is making online delivery the new default.", "choices": [c("Monthly statements will no longer be produced", False, "They are still produced and available online."), c("Statements will be sent online instead of on paper", True, "This is the central change."), c("Automatic payments will stop", False, "The email says payments are unaffected."), c("The account number will change", False, "No account-number change is mentioned.")]},
            {"stem": "What must Sam do by September 30 to keep paper statements?", "skill_focus": "detail", "evidence": "log in and update your delivery preference by September 30", "explanation": "Changing the preference is the only required action to continue paper delivery.", "choices": [c("Pay a $2 fee in advance", False, "The fee is charged monthly for the paper option, not as an advance."), c("Update the delivery preference", True, "This is the explicit deadline action."), c("Book a branch appointment", False, "An appointment is only for a special official letter."), c("Close the online account", False, "The online account remains the default.")]},
            {"stem": "For which members is the free official letter most useful?", "skill_focus": "inference", "evidence": "members who rely on mailed statements for immigration or proof of address", "explanation": "Those members need a recognized paper record of their account and address.", "choices": [c("Members who want an extra account card", False, "No card is discussed."), c("Members who need official proof of account or address", True, "The letter supports immigration and address verification."), c("Members who prefer to pay by cheque", False, "Cheque preference is not mentioned."), c("Members under eighteen", False, "Age is not part of the exception.")]},
            {"stem": "How far back can statements be downloaded at no charge?", "skill_focus": "detail", "evidence": "download any statement from the last seven years at no charge", "explanation": "Seven years of statements are available online.", "choices": [c("One year", False, "That is too short."), c("Three years", False, "The email says seven."), c("Seven years", True, "This matches the text."), c("Ten years", False, "That is beyond the stated range.")]},
        ],
    },
    {
        "slug": "tenant-parking-permit-renewal",
        "task_type": "reading_correspondence",
        "title": "Tenant Parking Permit Renewal",
        "topic": "Housing and tenancy",
        "difficulty": 2,
        "estimated_level": 7,
        "instructions": "Read the email and answer the questions.",
        "stimulus": {
            "type": "email",
            "from": "Cedar Gate Property Management",
            "to": "All residents",
            "subject": "Annual parking permit renewal",
            "body": "Dear residents,\n\nAll current parking permits expire at the end of this month. Renewal is open now through November 20. To renew, upload your vehicle registration and proof of insurance in the resident portal.\n\nEach unit may register one vehicle for the included permit. A second vehicle may be added for $35 per month, subject to space. Visitor parking remains limited to three consecutive nights; longer stays require a temporary permit from the office.\n\nUnderground spaces will be cleaned and line-painted from November 24 to November 27. Vehicles left in the garage during those dates may be towed at the owner's expense, so please use the outdoor lot or arrange alternative parking.\n\nContact the management office with any questions.\n\nCedar Gate Property Management",
        },
        "learning_notes": "Match each rule to the correct vehicle, permit, or visitor situation.",
        "questions": [
            {"stem": "What must residents upload to renew a permit?", "skill_focus": "detail", "evidence": "upload your vehicle registration and proof of insurance", "explanation": "Both documents are required for renewal.", "choices": [c("A recent photo and a utility bill", False, "Those documents are not requested."), c("Vehicle registration and proof of insurance", True, "Both are stated directly."), c("A lease and a parking ticket", False, "No lease or ticket is required."), c("A driver's licence and a bank statement", False, "Neither is mentioned as a renewal document.")]},
            {"stem": "What is true about a second vehicle?", "skill_focus": "detail", "evidence": "A second vehicle may be added for $35 per month, subject to space", "explanation": "A second vehicle is possible only if space allows and carries a monthly fee.", "choices": [c("It is always free", False, "There is a $35 monthly fee."), c("It may be added for $35 monthly if space is available", True, "This captures both the fee and the space condition."), c("It cannot be parked overnight", False, "No overnight restriction is described."), c("It needs a visitor permit", False, "Visitor permits are for guests, not resident vehicles.")]},
            {"stem": "Why might a vehicle be towed on November 25?", "skill_focus": "inference", "evidence": "Underground spaces will be cleaned and line-painted ... Vehicles left in the garage ... may be towed", "explanation": "Cars left in the garage would interfere with the scheduled cleaning and painting work.", "choices": [c("Its owner forgot to upload insurance", False, "The towing notice concerns the cleaning period."), c("It is parked in the garage during the work", True, "Vehicles must be moved while the garage is serviced."), c("It stayed in the outdoor lot too long", False, "The warning is about the underground garage."), c("It belongs to a visitor", False, "The rule applies to vehicles left in the garage.")]},
            {"stem": "What is the visitor parking limit?", "skill_focus": "detail", "evidence": "Visitor parking remains limited to three consecutive nights", "explanation": "Visitors may stay no more than three nights in a row without a temporary permit.", "choices": [c("Three consecutive nights", True, "This is the stated limit."), c("Two nights in one month", False, "The limit is not monthly."), c("Seven nights", False, "That is too long."), c("There is no limit", False, "The email explicitly gives a limit.")]},
        ],
    },
    {
        "slug": "library-overdue-item-notice",
        "task_type": "reading_correspondence",
        "title": "Library Overdue Item Notice",
        "topic": "Public library services",
        "difficulty": 2,
        "estimated_level": 6,
        "instructions": "Read the email and answer the questions.",
        "stimulus": {
            "type": "email",
            "from": "Harbourview Public Library",
            "to": "Jin Park",
            "subject": "Overdue item reminder",
            "body": "Dear Jin,\n\nOur records show that two items checked out to your card are now overdue: 'Beginner Watercolour' (book) and 'Canadian Landscapes' (DVD). The due date for both was September 18.\n\nPlease return them to any branch book drop within seven days. Fines are 25 cents per item per day, up to a maximum of $8 per item. If the items are lost, the replacement fee is $28 for the book and $15 for the DVD.\n\nBorrowing privileges are not blocked yet. However, accounts with items more than 21 days overdue are sent to a collection agency, which adds a $10 service fee.\n\nIf you believe an item was already returned, reply to this email or call the circulation desk.\n\nThank you,\nHarbourview Public Library",
        },
        "learning_notes": "Note the difference between daily fines, maximum fines, and separate replacement or collection fees.",
        "questions": [
            {"stem": "Why was the email sent?", "skill_focus": "purpose", "evidence": "two items checked out to your card are now overdue", "explanation": "The library is reminding Jin to return the items and explaining the consequences.", "choices": [c("To announce a new branch opening", False, "No branch opening appears."), c("To remind Jin about overdue items and possible fees", True, "The overdue items and fees organize the message."), c("To cancel Jin's library card", False, "The email says borrowing privileges are not blocked yet."), c("To request a donation", False, "No donation is requested.")]},
            {"stem": "What is the maximum fine for one item?", "skill_focus": "detail", "evidence": "up to a maximum of $8 per item", "explanation": "Each item has a $8 cap on the daily fine.", "choices": [c("$2.50", False, "That is not the cap."), c("$8", True, "This matches the stated maximum."), c("$10", False, "That is the collection agency fee."), c("$28", False, "That is the book replacement fee.")]},
            {"stem": "What can be inferred about borrowing privileges?", "skill_focus": "inference", "evidence": "Borrowing privileges are not blocked yet. However, accounts with items more than 21 days overdue ...", "explanation": "Jin can still borrow, but the situation may escalate if items remain overdue.", "choices": [c("They are already permanently cancelled", False, "They are not blocked yet."), c("They may be affected later if the items stay overdue", True, "The escalation rule supports this."), c("They can only be used at one branch", False, "No branch restriction is stated."), c("They have no fees attached", False, "Fines and replacement fees are possible.")]},
            {"stem": "What is the replacement fee for the DVD?", "skill_focus": "detail", "evidence": "the replacement fee is $28 for the book and $15 for the DVD", "explanation": "The DVD replacement fee is $15.", "choices": [c("$8", False, "That is the maximum daily fine."), c("$10", False, "That is the collection fee."), c("$15", True, "This is the DVD replacement fee."), c("$28", False, "That is the book replacement fee.")]},
        ],
    },
    {
        "slug": "food-bank-volunteer-orientation",
        "task_type": "reading_correspondence",
        "title": "Food Bank Volunteer Orientation",
        "topic": "Community volunteering",
        "difficulty": 1,
        "estimated_level": 6,
        "instructions": "Read the email and answer the questions.",
        "stimulus": {
            "type": "email",
            "from": "Westside Food Bank",
            "to": "New volunteers",
            "subject": "Your first shift information",
            "body": "Hello and welcome,\n\nYour first volunteer shift is Saturday, October 5, from 9 a.m. to noon. Please arrive at 8:45 a.m. for a brief orientation and safety tour.\n\nWear closed-toe shoes and comfortable clothing. Lockers are available, but we suggest leaving valuables at home. All volunteers must sign in at the front desk and wear the provided apron while handling food.\n\nYou will be assigned to one of three stations: sorting, packing, or client welcome. Station assignments are posted at the desk on arrival. If you have a food allergy, tell the shift supervisor so we can assign tasks that do not require direct contact with that item.\n\nParking behind the building is free for volunteers, but spaces are limited. The number 12 bus stops directly outside.\n\nThank you for supporting your neighbours,\nWestside Food Bank Team",
        },
        "learning_notes": "Track arrival requirements, station choices, and the allergy safety exception.",
        "questions": [
            {"stem": "What is the main purpose of the email?", "skill_focus": "gist", "evidence": "Your first volunteer shift is Saturday ... Please arrive at 8:45 a.m. for a brief orientation", "explanation": "The message prepares new volunteers for their first shift.", "choices": [c("To collect money for a charity event", False, "No donation request appears."), c("To explain what to do and bring on the first shift", True, "Timing, clothing, sign-in, stations, and parking are covered."), c("To announce the food bank is closing", False, "The shift is still scheduled."), c("To recruit a shift supervisor", False, "Supervisors are already present.")]},
            {"stem": "What should a volunteer with a food allergy do?", "skill_focus": "detail", "evidence": "tell the shift supervisor so we can assign tasks that do not require direct contact with that item", "explanation": "Volunteers should disclose allergies so tasks can be assigned safely.", "choices": [c("Bring medication to the sorting station", False, "No medication instruction is given."), c("Tell the shift supervisor", True, "This is the requested action."), c("Choose the client welcome station", False, "Assignments are posted, not self-selected."), c("Stay home from the shift", False, "The email provides an accommodation instead.")]},
            {"stem": "Why are volunteers asked to arrive at 8:45?", "skill_focus": "inference", "evidence": "Your first volunteer shift ... from 9 a.m. ... Please arrive at 8:45 a.m. for a brief orientation", "explanation": "The early arrival allows orientation and safety training before the shift begins.", "choices": [c("To finish the shift early", False, "The shift still ends at noon."), c("To complete orientation before the shift starts", True, "The orientation is scheduled in the fifteen minutes before 9 a.m."), c("To claim a free parking space", False, "Parking is mentioned but is not the reason for early arrival."), c("To have a meal first", False, "No meal is mentioned.")]},
            {"stem": "Where are station assignments posted?", "skill_focus": "detail", "evidence": "Station assignments are posted at the desk on arrival", "explanation": "Volunteers find their assignment at the front desk.", "choices": [c("At the bus stop", False, "The bus stop is not a posting location."), c("In the parking lot", False, "No assignment board is placed there."), c("At the front desk", True, "This is stated directly."), c("In a morning email", False, "Assignments are posted on arrival, not emailed.")]},
        ],
    },
    {
        "slug": "public-pool-lane-schedule",
        "task_type": "reading_apply_diagram",
        "title": "Public Pool Lane Schedule",
        "topic": "Community recreation",
        "difficulty": 1,
        "estimated_level": 6,
        "instructions": "Use the schedule to answer the questions.",
        "stimulus": {
            "type": "table",
            "title": "Meadow Park pool lane schedule",
            "columns": ["Lane", "Time", "Activity", "Age or skill", "Notes"],
            "rows": [
                ["1", "6:00-7:30 a.m.", "Adult lap swim", "18+", "Two swimmers per lane"],
                ["2", "9:00-10:00 a.m.", "Aqua fitness", "All ages", "Equipment provided"],
                ["3", "10:30-11:30 a.m.", "Parent and tot swim", "Children 0-5 with adult", "Shallow area only"],
                ["4", "4:00-5:30 p.m.", "Youth swim club", "Ages 8-15", "Approved by coach"],
                ["5", "7:00-8:00 p.m.", "Adult lane swim", "16+", "Medium and fast lanes"],
            ],
            "notes": "The pool closes 15 minutes after each session. A family change room is beside lane 3.",
        },
        "learning_notes": "Match age, activity, and lane note together before choosing an answer.",
        "questions": [
            {"stem": "Which lane can a 12-year-old join without a parent?", "skill_focus": "detail", "evidence": "Lane 4: Youth swim club, Ages 8-15", "explanation": "A 12-year-old fits the youth swim club age range.", "choices": [c("Lane 1", False, "Lane 1 is for adults aged 18 and older."), c("Lane 3", False, "Lane 3 is for children aged 0 to 5 with an adult."), c("Lane 4", True, "The youth swim club serves ages 8 to 15."), c("Lane 5", False, "Lane 5 requires age 16 or older.")]},
            {"stem": "Which session should a parent with a three-year-old choose?", "skill_focus": "detail", "evidence": "Lane 3: Parent and tot swim, Children 0-5 with adult", "explanation": "The parent-and-tot session is designed for a child of that age accompanied by an adult.", "choices": [c("Adult lap swim", False, "That session is for adults only."), c("Aqua fitness", False, "Aqua fitness is for all ages but is not specifically for toddlers with a parent."), c("Parent and tot swim", True, "It accepts children aged 0 to 5 with an adult."), c("Youth swim club", False, "Youth swim club begins at age 8.")]},
            {"stem": "Why is the family change room placed beside lane 3?", "skill_focus": "inference", "evidence": "Lane 3 is the Parent and tot swim; the family change room is beside lane 3.", "explanation": "The location makes changing easier for adults with young children.", "choices": [c("To serve families using the parent-and-tot session", True, "The nearby room supports the needs of adults and young children."), c("To give lap swimmers extra storage", False, "Lap swimmers are not the focus of the family room."), c("To separate the aqua fitness equipment", False, "Equipment is kept in lane 2, not the change room."), c("To reduce the number of lanes", False, "The change room does not change the lane count.")]},
            {"stem": "When does the pool close after a session?", "skill_focus": "detail", "evidence": "The pool closes 15 minutes after each session.", "explanation": "The note states the closing time after each session.", "choices": [c("Immediately", False, "The pool remains open for 15 minutes."), c("15 minutes later", True, "This matches the note."), c("30 minutes later", False, "That is longer than stated."), c("At the next session start", False, "The pool closes before the next session.")]},
        ],
    },
    {
        "slug": "community-centre-room-rental-rates",
        "task_type": "reading_apply_diagram",
        "title": "Community Centre Room Rental Rates",
        "topic": "Facility rental",
        "difficulty": 2,
        "estimated_level": 7,
        "instructions": "Use the table to answer the questions.",
        "stimulus": {
            "type": "table",
            "title": "Riverside room rental rates",
            "columns": ["Room", "Half day", "Full day", "Seats", "Notes"],
            "rows": [
                ["Maple Room", "$90", "$150", "40", "Kitchen access add $25"],
                ["Cedar Hall", "$160", "$280", "90", "Includes AV system"],
                ["Studio B", "$70", "$110", "20", "Mirrors; no food allowed"],
                ["Boardroom", "$55", "$90", "12", "Whiteboard included"],
            ],
            "notes": "A full day is 8 hours. Non-profit groups receive 10% off Monday to Thursday. A $50 cleaning deposit is required for events with food.",
        },
        "learning_notes": "Check seating, food rules, and any add-on fees before selecting a room.",
        "questions": [
            {"stem": "Which room should a 15-person meeting choose?", "skill_focus": "inference", "evidence": "Studio B seats 20; the Boardroom seats only 12.", "explanation": "The meeting needs at least 15 seats, so Studio B is the smallest suitable room.", "choices": [c("Boardroom", False, "It seats only 12 people."), c("Studio B", True, "It seats 20, enough for the group."), c("Maple Room", False, "Maple Room works but is larger and more expensive than needed."), c("Cedar Hall", False, "Cedar Hall is the largest and most expensive option.")]},
            {"stem": "What extra charge applies to use the kitchen with Maple Room?", "skill_focus": "detail", "evidence": "Maple Room ... Kitchen access add $25", "explanation": "Kitchen access is an optional $25 add-on.", "choices": [c("$25", True, "This is the stated add-on."), c("$50", False, "That is the cleaning deposit for food events."), c("$90", False, "That is Maple Room's half-day rate."), c("No charge", False, "Kitchen access is not included.")]},
            {"stem": "Why is a cleaning deposit required for events with food?", "skill_focus": "inference", "evidence": "A $50 cleaning deposit is required for events with food.", "explanation": "Food increases the chance of spills and extra cleaning, so the centre protects against additional work.", "choices": [c("To pay for the food itself", False, "The deposit is not a food purchase."), c("To cover possible additional cleaning", True, "Food events create more cleaning risk."), c("To book kitchen access", False, "Kitchen access is a separate $25 charge."), c("To reserve more seating", False, "Seating is determined by room choice.")]},
            {"stem": "When do non-profit groups receive a discount?", "skill_focus": "detail", "evidence": "Non-profit groups receive 10% off Monday to Thursday", "explanation": "The discount is available only on weekdays from Monday through Thursday.", "choices": [c("Weekends", False, "Weekends are excluded."), c("Monday to Thursday", True, "This is the stated discount window."), c("Friday only", False, "Friday is not included."), c("Every day", False, "The note limits the discount to four weekdays.")]},
        ],
    },
    {
        "slug": "compost-pickup-schedule",
        "task_type": "reading_apply_diagram",
        "title": "Compost Pickup Schedule",
        "topic": "Municipal services",
        "difficulty": 2,
        "estimated_level": 6,
        "instructions": "Use the table to answer the questions.",
        "stimulus": {
            "type": "table",
            "title": "Greenfield compost collection",
            "columns": ["Zone", "Pickup day", "Bins out by", "Accepted", "Not accepted"],
            "rows": [
                ["Green Zone", "Tuesday", "7 a.m.", "Food scraps, leaves", "Plastic bags"],
                ["Blue Zone", "Wednesday", "7 a.m.", "Food scraps, paper liners", "Diapers"],
                ["Orange Zone", "Thursday", "6:30 a.m.", "Yard waste, food scraps", "Glass"],
                ["Red Zone", "Friday", "6:30 a.m.", "Leaves, food scraps", "Pet waste"],
            ],
            "notes": "During winter, collection starts one hour later. Extra compost goes in paper yard-waste bags only.",
        },
        "learning_notes": "Read across the correct zone row, then apply the winter and extra-compost notes.",
        "questions": [
            {"stem": "When is compost collected in Blue Zone?", "skill_focus": "detail", "evidence": "Blue Zone: Wednesday", "explanation": "Blue Zone pickup day is Wednesday.", "choices": [c("Tuesday", False, "Tuesday is Green Zone's day."), c("Wednesday", True, "This matches the Blue Zone row."), c("Thursday", False, "Thursday is Orange Zone's day."), c("Friday", False, "Friday is Red Zone's day.")]},
            {"stem": "Which item must not go in an Orange Zone compost bin?", "skill_focus": "detail", "evidence": "Orange Zone ... Not accepted: Glass", "explanation": "Glass is listed as not accepted in Orange Zone.", "choices": [c("Yard waste", False, "Yard waste is accepted in Orange Zone."), c("Food scraps", False, "Food scraps are accepted."), c("Glass", True, "Glass is listed as not accepted."), c("Leaves", False, "Leaves are accepted in Red Zone, but the question asks about Orange Zone.")]},
            {"stem": "Why might winter collection start one hour later?", "skill_focus": "inference", "evidence": "During winter, collection starts one hour later.", "explanation": "Later collection may allow for safer daylight or road conditions, although the table does not give an explicit reason.", "choices": [c("To give crews better conditions for working", True, "A later start is a reasonable adjustment for winter conditions."), c("To reduce the number of bins", False, "The number of bins is not changed."), c("To cancel collection that week", False, "Collection is delayed, not cancelled."), c("To accept plastic bags", False, "Plastic bags remain not accepted.")]},
            {"stem": "How should extra compost be put out?", "skill_focus": "detail", "evidence": "Extra compost goes in paper yard-waste bags only", "explanation": "Only paper yard-waste bags are permitted for extra compost.", "choices": [c("In plastic bags", False, "Plastic bags are not accepted."), c("In paper yard-waste bags", True, "This is the stated requirement."), c("In any closed container", False, "The note specifies one bag type."), c("Beside the blue bin", False, "No blue-bin instruction appears.")]},
        ],
    },
    {
        "slug": "city-parking-rates",
        "task_type": "reading_apply_diagram",
        "title": "City Parking Rates",
        "topic": "Parking and transit",
        "difficulty": 2,
        "estimated_level": 7,
        "instructions": "Use the table to answer the questions.",
        "stimulus": {
            "type": "table",
            "title": "Laketon public parking",
            "columns": ["Area", "Hourly rate", "Evening rate", "Daily max", "Notes"],
            "rows": [
                ["Downtown street", "$3.50", "$2.00 after 6 p.m.", "$18", "Free Sundays"],
                ["North lot", "$2.50", "$2.50", "$12", "No overnight"],
                ["Transit station", "$1.50", "$1.00", "$8", "Valid transit pass needed"],
                ["Hospital zone", "$3.00", "$3.00", "$15", "Max 4 hours"],
            ],
            "notes": "Rates apply until 10 p.m. Pay by app or at the machine. Accessible spaces are free with a valid permit.",
        },
        "learning_notes": "Compare daily cost, time limits, and special access rules rather than only the hourly rate.",
        "questions": [
            {"stem": "Which area requires a valid transit pass?", "skill_focus": "detail", "evidence": "Transit station ... Valid transit pass needed", "explanation": "The transit station has a pass requirement attached to its parking.", "choices": [c("Downtown street", False, "No pass requirement is listed for downtown."), c("North lot", False, "North lot has no pass requirement."), c("Transit station", True, "This is stated in the notes column."), c("Hospital zone", False, "Hospital zone has a time limit, not a pass requirement.")]},
            {"stem": "What is the evening rate for downtown street parking?", "skill_focus": "detail", "evidence": "Downtown street ... $2.00 after 6 p.m.", "explanation": "After 6 p.m. the rate drops to $2.00.", "choices": [c("$1.50", False, "That is the transit station hourly rate."), c("$2.00", True, "This matches the downtown evening rate."), c("$2.50", False, "That is the North lot rate."), c("$3.00", False, "That is the hospital zone rate.")]},
            {"stem": "Why does the hospital zone have a four-hour maximum?", "skill_focus": "inference", "evidence": "Hospital zone ... Max 4 hours", "explanation": "A short limit helps keep spaces available for the steady flow of patients and visitors.", "choices": [c("To keep spaces turning over for patients and visitors", True, "A time limit supports access to the hospital."), c("To allow overnight parking", False, "The opposite is true."), c("To increase the daily fee", False, "The limit does not mention raising fees."), c("To reserve spaces for city staff", False, "No staff reservation is mentioned.")]},
            {"stem": "When can someone park free in an accessible space?", "skill_focus": "detail", "evidence": "Accessible spaces are free with a valid permit", "explanation": "A valid accessible permit removes the fee.", "choices": [c("After 10 p.m.", False, "The note does not give a time-based free rule."), c("With a valid permit", True, "This is stated directly."), c("On Sundays only", False, "Sunday free parking is a separate downtown rule."), c("With a transit pass", False, "A transit pass is required at the transit station, not for accessible spaces.")]},
        ],
    },
    {
        "slug": "grocery-delivery-time-slots",
        "task_type": "reading_apply_diagram",
        "title": "Grocery Delivery Time Slots",
        "topic": "Online shopping",
        "difficulty": 2,
        "estimated_level": 7,
        "instructions": "Use the table to answer the questions.",
        "stimulus": {
            "type": "table",
            "title": "FreshCart delivery windows",
            "columns": ["Time slot", "Delivery fee", "Window", "Order by", "Notes"],
            "rows": [
                ["Early morning", "$4.99", "7:00-9:00 a.m.", "8 p.m. night before", "Limited area"],
                ["Midday", "$3.99", "11:00 a.m.-1:00 p.m.", "9 a.m. same day", "Popular"],
                ["Afternoon", "$2.99", "2:00-4:00 p.m.", "11 a.m. same day", "Best availability"],
                ["Evening", "$5.99", "6:00-9:00 p.m.", "2 p.m. same day", "Cold items packed separately"],
            ],
            "notes": "Orders over $75 receive free afternoon delivery. Missing items must be reported within 24 hours.",
        },
        "learning_notes": "Compare fees, deadlines, and restrictions across slots, then apply the free-delivery offer.",
        "questions": [
            {"stem": "Which delivery slot has the lowest fee?", "skill_focus": "detail", "evidence": "Afternoon: $2.99", "explanation": "The afternoon slot is the cheapest at $2.99.", "choices": [c("Early morning", False, "Early morning is $4.99."), c("Midday", False, "Midday is $3.99."), c("Afternoon", True, "Afternoon is $2.99."), c("Evening", False, "Evening is $5.99.")]},
            {"stem": "How can a customer get free delivery?", "skill_focus": "inference", "evidence": "Orders over $75 receive free afternoon delivery", "explanation": "Free delivery applies only to the afternoon slot when the order is over $75.", "choices": [c("Order before 9 a.m.", False, "A morning order does not guarantee free delivery."), c("Spend over $75 and choose afternoon delivery", True, "Both conditions are required."), c("Report a missing item", False, "Reporting a missing item is not linked to free delivery."), c("Choose the limited-area slot", False, "The early-morning slot has a fee.")]},
            {"stem": "Why are cold items packed separately for the evening slot?", "skill_focus": "inference", "evidence": "Evening ... Cold items packed separately", "explanation": "Separate packing helps protect cold items during the later delivery window.", "choices": [c("To keep them at the right temperature", True, "This is the likely reason for separate packing."), c("To charge an extra fee", False, "No extra packing fee is stated."), c("To make the order heavier", False, "Packing strategy does not change weight."), c("To reduce the number of bags", False, "Separate packing may add bags, not reduce them.")]},
            {"stem": "By what time must an evening order be placed?", "skill_focus": "detail", "evidence": "Evening ... Order by 2 p.m. same day", "explanation": "The evening slot requires an order by 2 p.m. that day.", "choices": [c("8 p.m. the night before", False, "That is the early-morning deadline."), c("9 a.m. same day", False, "That is the midday deadline."), c("11 a.m. same day", False, "That is the afternoon deadline."), c("2 p.m. same day", True, "This matches the evening slot.")]},
        ],
    },
    {
        "slug": "transit-fare-table",
        "task_type": "reading_apply_diagram",
        "title": "Transit Fare Table",
        "topic": "Public transit",
        "difficulty": 1,
        "estimated_level": 6,
        "instructions": "Use the table to answer the questions.",
        "stimulus": {
            "type": "table",
            "title": "Ridgedale Transit fares",
            "columns": ["Rider", "Single fare", "Monthly pass", "Notes"],
            "rows": [
                ["Adult", "$3.25", "$102", "Valid on bus and train"],
                ["Senior 65+", "$2.25", "$52", "ID may be requested"],
                ["Youth 6-18", "$2.25", "$52", "ID may be requested"],
                ["Child under 6", "Free", "Not needed", "Must travel with adult"],
            ],
            "notes": "A transfer is valid for 90 minutes in one direction. A reduced fare is also available to post-secondary students with a valid campus card.",
        },
        "learning_notes": "Check age, required identification, and transfer rules when choosing a fare.",
        "questions": [
            {"stem": "How much is a senior single fare?", "skill_focus": "detail", "evidence": "Senior 65+: $2.25", "explanation": "The senior single fare is $2.25.", "choices": [c("$1.50", False, "That amount is not listed."), c("$2.25", True, "This is the senior and youth fare."), c("$3.25", False, "That is the adult fare."), c("Free", False, "Free applies to children under six.")]},
            {"stem": "What must a post-secondary student show for a reduced fare?", "skill_focus": "detail", "evidence": "post-secondary students with a valid campus card", "explanation": "A valid campus card is required for the student discount.", "choices": [c("A birth certificate", False, "No birth certificate is requested."), c("A monthly pass", False, "The monthly pass is a payment option, not proof."), c("A valid campus card", True, "This is the stated requirement."), c("A transit transfer", False, "A transfer does not prove student status.")]},
            {"stem": "Why must a child under six travel with an adult?", "skill_focus": "inference", "evidence": "Child under 6: Free ... Must travel with adult", "explanation": "Very young children are not treated as independent riders and require adult supervision.", "choices": [c("Because they need adult supervision", True, "The adult rule reflects the child's age and safety needs."), c("Because they receive the adult fare", False, "They travel free."), c("Because they cannot use a transfer", False, "The transfer rule is not the reason."), c("Because they must sit in the front", False, "No seating rule is stated.")]},
            {"stem": "How long is a transfer valid?", "skill_focus": "detail", "evidence": "A transfer is valid for 90 minutes in one direction", "explanation": "The transfer lasts 90 minutes and cannot be used for a return trip.", "choices": [c("30 minutes", False, "That is too short."), c("60 minutes", False, "The table says 90 minutes."), c("90 minutes", True, "This matches the note."), c("Two hours", False, "That is longer than stated.")]},
        ],
    },
    {
        "slug": "winter-safety-guidelines-for-renters",
        "task_type": "reading_information",
        "title": "Winter Safety Guidelines for Renters",
        "topic": "Housing and safety",
        "difficulty": 1,
        "estimated_level": 5,
        "instructions": "Read the information and answer the questions.",
        "stimulus": {
            "type": "article",
            "title": "Cold-weather safety in your rental",
            "sections": [
                {"heading": "Heating", "body": "Keep the thermostat at least 18 degrees Celsius in all rooms. Do not use the oven or a portable outdoor heater to warm the apartment."},
                {"heading": "Pipes", "body": "During very cold weather, let a thin stream of water drip from the farthest tap. Leave cabinet doors under sinks open so warm air can reach the pipes."},
                {"heading": "Sidewalks", "body": "Tenants are responsible for clearing snow and ice from their private walkway within 24 hours after a snowfall. Use salt or sand sparingly to protect nearby plants."},
                {"heading": "Power outages", "body": "Keep flashlights, batteries, blankets, and non-perishable food ready. Do not bring outdoor cooking equipment indoors."},
            ],
        },
        "learning_notes": "Connect each rule to the winter problem it prevents.",
        "questions": [
            {"stem": "What is the main purpose of the guidelines?", "skill_focus": "gist", "evidence": "The sections describe heating, pipes, sidewalks, and outage preparation.", "explanation": "The notice gives tenants practical rules for staying safe in winter.", "choices": [c("To advertise a heating repair service", False, "No repair service is promoted."), c("To explain winter safety rules for tenants", True, "Every section provides a cold-weather rule."), c("To collect snow-removal fees", False, "No fees are mentioned."), c("To describe a recent power outage", False, "The notice is forward-looking preparation.")]},
            {"stem": "What should a tenant do to protect pipes in very cold weather?", "skill_focus": "detail", "evidence": "let a thin stream of water drip from the farthest tap. Leave cabinet doors under sinks open", "explanation": "Dripping water and open cabinet doors help prevent freezing.", "choices": [c("Turn the water off completely", False, "A thin stream should be left running."), c("Let water drip and open cabinet doors", True, "Both actions are recommended."), c("Use the oven to heat the kitchen", False, "Using the oven for heat is prohibited."), c("Close all sink cabinets tightly", False, "Cabinets should be left open.")]},
            {"stem": "Why does the notice say not to use an outdoor heater indoors?", "skill_focus": "inference", "evidence": "Do not use the oven or a portable outdoor heater to warm the apartment.", "explanation": "Outdoor heaters and ovens can create fire, carbon-monoxide, or ventilation risks indoors.", "choices": [c("It could create a safety or ventilation risk", True, "That is the likely concern with indoor use of outdoor equipment."), c("It would cool the apartment", False, "The concern is safety, not cooling."), c("It would use too little power", False, "Power use is not the stated concern."), c("It is not allowed to touch the thermostat", False, "The thermostat rule is separate.")]},
            {"stem": "How soon must tenants clear their private walkway?", "skill_focus": "detail", "evidence": "clearing snow and ice from their private walkway within 24 hours after a snowfall", "explanation": "The deadline is 24 hours after the snow stops falling.", "choices": [c("Within 12 hours", False, "That is shorter than stated."), c("Within 24 hours", True, "This matches the rule."), c("Within 48 hours", False, "That is longer than stated."), c("Before the next month", False, "The deadline is much sooner.")]},
        ],
    },
    {
        "slug": "summer-heat-emergency-centre",
        "task_type": "reading_information",
        "title": "Summer Heat Emergency Centre",
        "topic": "Public health and safety",
        "difficulty": 2,
        "estimated_level": 6,
        "instructions": "Read the notice and answer the questions.",
        "stimulus": {
            "type": "article",
            "title": "Community cooling centre",
            "sections": [
                {"heading": "Opening", "body": "The centre opens when the temperature reaches 34 degrees Celsius for two days in a row. It is located at 210 Elm Street and operates from 10 a.m. to 8 p.m."},
                {"heading": "Services", "body": "The centre provides drinking water, seating, showers, and nursing staff. Only service animals are permitted inside."},
                {"heading": "Transport", "body": "A free shuttle leaves the community centres at noon and 4 p.m. and returns at 6 p.m. and 8 p.m."},
                {"heading": "Health advice", "body": "Drink water regularly, avoid strenuous outdoor work between 11 a.m. and 3 p.m., and check on older neighbours during hot periods."},
            ],
        },
        "learning_notes": "Track the opening condition, permitted animals, shuttle times, and who needs checking.",
        "questions": [
            {"stem": "When does the cooling centre open?", "skill_focus": "detail", "evidence": "opens when the temperature reaches 34 degrees Celsius for two days in a row", "explanation": "The centre opens after two consecutive days at that temperature.", "choices": [c("After one hot afternoon", False, "Two consecutive days are required."), c("When it reaches 34 degrees for two consecutive days", True, "This is the opening condition."), c("Only when a power outage occurs", False, "Power outages are not the condition."), c("Every day in summer", False, "The centre opens only under the stated heat condition.")]},
            {"stem": "Which animals are allowed inside the centre?", "skill_focus": "detail", "evidence": "Only service animals are permitted inside.", "explanation": "The centre allows service animals but not pets.", "choices": [c("Any pet in a carrier", False, "Pets are not permitted."), c("Service animals only", True, "This is stated directly."), c("Dogs of any kind", False, "Only service animals qualify."), c("No animals at all", False, "Service animals are allowed.")]},
            {"stem": "Why does the notice recommend checking on older neighbours?", "skill_focus": "inference", "evidence": "check on older neighbours during hot periods", "explanation": "Older adults may be more vulnerable to heat-related illness.", "choices": [c("They may be at greater risk in the heat", True, "The recommendation targets a vulnerable group."), c("They must drive the shuttle", False, "Older neighbours are not asked to provide transport."), c("They cannot enter the centre", False, "The centre is open to the community."), c("They are required to volunteer", False, "No volunteering requirement appears.")]},
            {"stem": "At which time does the free shuttle leave the community centres?", "skill_focus": "detail", "evidence": "A free shuttle leaves the community centres at noon and 4 p.m.", "explanation": "The shuttle has two departure times.", "choices": [c("10 a.m. and 6 p.m.", False, "Those are not the departure times."), c("Noon and 4 p.m.", True, "These are the two listed departures."), c("6 p.m. and 8 p.m.", False, "Those are return times."), c("Noon only", False, "There are two departures.")]},
        ],
    },
    {
        "slug": "neighbourhood-watch-program",
        "task_type": "reading_information",
        "title": "Neighbourhood Watch Program",
        "topic": "Community safety",
        "difficulty": 1,
        "estimated_level": 6,
        "instructions": "Read the information and answer the questions.",
        "stimulus": {
            "type": "article",
            "title": "How our neighbourhood watch works",
            "sections": [
                {"heading": "Purpose", "body": "Members help keep the area safer by sharing information and reporting suspicious activity. The group does not enforce the law."},
                {"heading": "Meetings", "body": "General meetings are held on the first Tuesday of each month at 7 p.m. in the public library."},
                {"heading": "Signs and patrols", "body": "Metal watch signs are available for residents. Walking patrols always travel in pairs, and members should never approach a possible suspect."},
                {"heading": "Contact", "body": "Call 911 for emergencies. Use the police non-emergency line, 306-555-0100, for less urgent reports."},
            ],
        },
        "learning_notes": "Separate what members do from what police do.",
        "questions": [
            {"stem": "What is the main purpose of the program?", "skill_focus": "gist", "evidence": "Members help keep the area safer by sharing information and reporting suspicious activity.", "explanation": "The program organizes neighbours to report and share information, not to enforce laws.", "choices": [c("To arrest suspected criminals", False, "Members do not enforce the law."), c("To encourage residents to share information and report concerns", True, "This matches the stated purpose."), c("To replace the police service", False, "The group works alongside, not instead of, police."), c("To sell security signs", False, "Signs are available but are not the purpose.")]},
            {"stem": "What should members never do?", "skill_focus": "detail", "evidence": "members should never approach a possible suspect", "explanation": "Members are instructed to avoid approaching suspects.", "choices": [c("Call 911", False, "Calling 911 is appropriate in an emergency."), c("Walk in pairs", False, "Walking in pairs is required."), c("Approach a possible suspect", True, "This action is explicitly forbidden."), c("Attend the monthly meeting", False, "Meetings are open to members.")]},
            {"stem": "Why do patrols travel in pairs?", "skill_focus": "inference", "evidence": "Walking patrols always travel in pairs", "explanation": "Travelling together is a safety measure for the volunteers.", "choices": [c("To cover more streets at once", False, "A pair does not necessarily cover more area."), c("To keep patrol volunteers safer", True, "The pair rule is a standard safety precaution."), c("To reduce noise in the neighbourhood", False, "Noise is not the stated concern."), c("To meet the library's requirement", False, "The library is a meeting location, not a patrol rule.")]},
            {"stem": "When are general meetings held?", "skill_focus": "detail", "evidence": "held on the first Tuesday of each month at 7 p.m.", "explanation": "The meeting time is the first Tuesday at 7 p.m.", "choices": [c("Last Tuesday at 6 p.m.", False, "The date and time differ."), c("First Tuesday at 7 p.m.", True, "This matches the text."), c("Every Tuesday at noon", False, "Meetings are monthly, not weekly."), c("First Monday at 8 p.m.", False, "The day and time differ.")]},
        ],
    },
    {
        "slug": "public-health-clinic-services",
        "task_type": "reading_information",
        "title": "Public Health Clinic Services",
        "topic": "Health services",
        "difficulty": 2,
        "estimated_level": 7,
        "instructions": "Read the information and answer the questions.",
        "stimulus": {
            "type": "article",
            "title": "Downtown public health clinic",
            "sections": [
                {"heading": "Walk-in services", "body": "The clinic offers routine vaccinations, tuberculosis skin tests, and confidential STI testing on a walk-in basis."},
                {"heading": "Travel health", "body": "Travel vaccinations and advice require an appointment. Some travel vaccines have a fee that is not covered by the provincial health plan."},
                {"heading": "Records", "body": "Immunization records can be viewed online. Allow ten business days after a visit for the record to be updated."},
                {"heading": "Cancellations", "body": "If you need to cancel an appointment, call by 4 p.m. the day before so the time can be offered to another client."},
            ],
        },
        "learning_notes": "Distinguish walk-in services from those that require an appointment.",
        "questions": [
            {"stem": "Which service requires an appointment?", "skill_focus": "detail", "evidence": "Travel vaccinations and advice require an appointment", "explanation": "Travel health is the service that cannot be accessed as a walk-in.", "choices": [c("Routine vaccinations", False, "These are walk-in services."), c("Tuberculosis skin tests", False, "These are walk-in services."), c("Confidential STI testing", False, "This is a walk-in service."), c("Travel vaccinations and advice", True, "An appointment is required.")]},
            {"stem": "How can a client view immunization records?", "skill_focus": "detail", "evidence": "Immunization records can be viewed online", "explanation": "Records are available online after a processing delay.", "choices": [c("By visiting the clinic", False, "The text says online."), c("Online", True, "This is the stated method."), c("By mailing a request", False, "No mail request is mentioned."), c("Only through a family doctor", False, "The clinic provides online access.")]},
            {"stem": "Why does the clinic ask clients to cancel by 4 p.m. the day before?", "skill_focus": "inference", "evidence": "call by 4 p.m. the day before so the time can be offered to another client", "explanation": "The deadline allows the clinic to rebook the appointment.", "choices": [c("To charge a cancellation fee", False, "No fee is mentioned."), c("To give the appointment to someone else", True, "This is the stated reason."), c("To close the clinic early", False, "The deadline is not about closing."), c("To update immunization records", False, "Records are updated after a visit, not after cancellation.")]},
            {"stem": "What is true about some travel vaccines?", "skill_focus": "detail", "evidence": "Some travel vaccines have a fee that is not covered by the provincial health plan", "explanation": "Travel vaccines may involve an out-of-pocket cost.", "choices": [c("They are always free", False, "Some have a fee."), c("They may not be covered by the health plan", True, "This is stated directly."), c("They are available as walk-ins", False, "Travel services require an appointment."), c("They update records immediately", False, "Record updates take ten business days.")]},
        ],
    },
    {
        "slug": "recycling-depot-rules",
        "task_type": "reading_information",
        "title": "Recycling Depot Rules",
        "topic": "Waste and recycling",
        "difficulty": 1,
        "estimated_level": 5,
        "instructions": "Read the notice and answer the questions.",
        "stimulus": {
            "type": "article",
            "title": "Southgate recycling depot",
            "sections": [
                {"heading": "Hours", "body": "The depot is open Tuesday through Saturday from 8 a.m. to 4 p.m. It is closed on public holidays."},
                {"heading": "Accepted", "body": "The depot accepts paper, cardboard, glass bottles, metal cans, and household batteries."},
                {"heading": "Not accepted", "body": "Styrofoam, plastic bags, electronics, and hazardous waste cannot be dropped off at the depot."},
                {"heading": "Sorting", "body": "Separate materials by type, remove lids from bottles, and rinse containers before bringing them."},
            ],
        },
        "learning_notes": "Check the day, accepted materials, and preparation steps before making a trip.",
        "questions": [
            {"stem": "Which day is the depot open?", "skill_focus": "detail", "evidence": "open Tuesday through Saturday from 8 a.m. to 4 p.m.", "explanation": "Saturday is within the listed operating days.", "choices": [c("Sunday", False, "The depot is closed Sunday."), c("Monday", False, "The depot is closed Monday."), c("Saturday", True, "Saturday is an operating day."), c("Public holidays", False, "The depot is closed on public holidays.")]},
            {"stem": "Which item is not accepted at the depot?", "skill_focus": "detail", "evidence": "Styrofoam ... cannot be dropped off", "explanation": "Styrofoam is listed under not accepted.", "choices": [c("Cardboard", False, "Cardboard is accepted."), c("Metal cans", False, "Metal cans are accepted."), c("Household batteries", False, "Household batteries are accepted."), c("Styrofoam", True, "Styrofoam is not accepted.")]},
            {"stem": "Why should containers be rinsed before drop-off?", "skill_focus": "inference", "evidence": "rinse containers before bringing them", "explanation": "Rinsing reduces contamination, odours, and pests during storage and processing.", "choices": [c("To reduce contamination and odours", True, "Clean containers are easier to process and store."), c("To make them lighter to carry", False, "Rinsing does not significantly affect weight."), c("To remove the labels", False, "The notice does not mention labels."), c("To qualify for a refund", False, "No refund is described.")]},
            {"stem": "What should people do with bottle lids?", "skill_focus": "detail", "evidence": "remove lids from bottles", "explanation": "Lids should be removed before drop-off.", "choices": [c("Leave them on", False, "The notice says to remove them."), c("Remove them", True, "This is the instruction."), c("Recycle them separately as plastic bags", False, "Plastic bags are not accepted."), c("Throw them in the garbage", False, "No garbage instruction is given.")]},
        ],
    },
    {
        "slug": "community-garden-tool-library",
        "task_type": "reading_information",
        "title": "Community Garden Tool Library",
        "topic": "Community gardening",
        "difficulty": 2,
        "estimated_level": 6,
        "instructions": "Read the information and answer the questions.",
        "stimulus": {
            "type": "article",
            "title": "Borrowing from the garden tool library",
            "sections": [
                {"heading": "Membership", "body": "Membership is free for community garden members. A photo ID is required to borrow tools."},
                {"heading": "Borrowing", "body": "Most tools can be borrowed for up to seven days. The late fee is $1 per tool for each extra day."},
                {"heading": "Equipment", "body": "Hand tools, wheelbarrows, hoses, and seed-starting trays are available. Power tools require a short training session."},
                {"heading": "Returns", "body": "Return tools clean and dry before closing. Borrowers are charged for missing parts."},
            ],
        },
        "learning_notes": "Track loan length, fees, and the extra rule for power tools.",
        "questions": [
            {"stem": "What must a borrower show to use the tool library?", "skill_focus": "detail", "evidence": "A photo ID is required to borrow tools", "explanation": "A photo ID is the borrowing requirement.", "choices": [c("A garden plot map", False, "No map is required."), c("A photo ID", True, "This is stated directly."), c("A membership card only", False, "Membership is free but a photo ID is also required."), c("A written letter", False, "No letter is mentioned.")]},
            {"stem": "How long can most tools be borrowed?", "skill_focus": "detail", "evidence": "Most tools can be borrowed for up to seven days", "explanation": "The standard loan period is seven days.", "choices": [c("Three days", False, "That is shorter than stated."), c("Seven days", True, "This matches the loan period."), c("Ten days", False, "That is longer than stated."), c("One month", False, "That is much longer than stated.")]},
            {"stem": "Why do power tools require a training session?", "skill_focus": "inference", "evidence": "Power tools require a short training session", "explanation": "Training is likely required because power tools carry greater safety risks.", "choices": [c("To make sure borrowers use them safely", True, "Training reduces the risk of injury."), c("To charge a higher fee", False, "No training fee is mentioned."), c("To limit borrowing to seven days", False, "The loan length is separate from training."), c("To remove missing parts", False, "Missing parts are a return issue.")]},
            {"stem": "What is the late fee for one tool kept an extra day?", "skill_focus": "detail", "evidence": "The late fee is $1 per tool for each extra day", "explanation": "The fee is one dollar per tool per extra day.", "choices": [c("$0.50", False, "That is not the stated fee."), c("$1", True, "This matches the fee."), c("$2", False, "That is twice the stated fee."), c("$5", False, "That is too high.")]},
        ],
    },
    {
        "slug": "new-downtown-arena-debate",
        "task_type": "reading_viewpoints",
        "title": "Should the City Build a New Arena?",
        "topic": "Civic spending",
        "difficulty": 2,
        "estimated_level": 8,
        "instructions": "Compare the viewpoints and answer the questions.",
        "stimulus": {
            "type": "viewpoints",
            "title": "Should Riverside build a new downtown arena?",
            "background": "The city is considering using reserve funds and a new hotel tax to replace its aging arena.",
            "speakers": [
                {"name": "Maya Chen", "position": "Small business owner", "body": "I support the arena. A modern venue would bring concerts and tournaments downtown, filling nearby restaurants and hotels on weeknights. That foot traffic is exactly what our small businesses need."},
                {"name": "David Tremblay", "position": "Resident and taxpayer", "body": "I oppose it. Public arenas often cost more than expected, and a new hotel tax would fall on visitors and residents alike. The main benefit goes to a private sports team, not to ordinary taxpayers."},
            ],
        },
        "learning_notes": "Separate each speaker's prediction from their underlying concern about costs and benefits.",
        "questions": [
            {"stem": "What is the speakers' main disagreement?", "skill_focus": "gist", "evidence": "Maya predicts downtown visitors; David predicts high public costs and private benefit.", "explanation": "They disagree about whether the arena is worth the public cost.", "choices": [c("The arena's paint colour", False, "Colour is not discussed."), c("Whether the arena will benefit the city enough to justify public money", True, "Their predictions and concerns are opposite."), c("Whether concerts are enjoyable", False, "Both discuss the arena's effects, not concert quality."), c("Whether the arena is old", False, "Both understand the current arena is aging.")]},
            {"stem": "Why does David oppose the plan?", "skill_focus": "detail", "evidence": "Public arenas often cost more than expected ... the main benefit goes to a private sports team", "explanation": "David objects to cost risk and private benefit.", "choices": [c("He wants a larger hotel tax", False, "He opposes the tax."), c("He thinks the city cannot host concerts", False, "He does not question the ability to host events."), c("He is concerned about public cost and private gain", True, "Both concerns are explicit."), c("He owns a competing arena", False, "No competing ownership is mentioned.")]},
            {"stem": "What can be inferred about Maya's hopes for the arena?", "skill_focus": "inference", "evidence": "A modern venue would bring concerts and tournaments downtown, filling nearby restaurants and hotels", "explanation": "She expects events to increase customer traffic for local businesses.", "choices": [c("She expects more visitors to spend money downtown", True, "Her examples focus on filled restaurants and hotels."), c("She wants the arena kept private", False, "She supports the public plan."), c("She believes taxes should stay the same", False, "The hotel tax is part of the proposal she supports."), c("She plans to sell her business", False, "She hopes the arena will help her business.")]},
            {"stem": "What source of funding is mentioned for the arena?", "skill_focus": "detail", "evidence": "using reserve funds and a new hotel tax", "explanation": "The proposal combines reserve funds with a hotel tax.", "choices": [c("Reserve funds and a hotel tax", True, "Both are listed."), c("A parking levy only", False, "No parking levy is mentioned."), c("Private donations only", False, "The plan uses public funds."), c("A sales tax on food", False, "No food tax is mentioned.")]},
        ],
    },
    {
        "slug": "downtown-grocery-store-debate",
        "task_type": "reading_viewpoints",
        "title": "Should a Grocery Store Be Allowed Downtown?",
        "topic": "Urban retail",
        "difficulty": 2,
        "estimated_level": 7,
        "instructions": "Compare the viewpoints and answer the questions.",
        "stimulus": {
            "type": "viewpoints",
            "title": "Should a large grocery store open on Main Street?",
            "background": "A company wants to build a large grocery store in a downtown area that currently has only small corner stores.",
            "speakers": [
                {"name": "Sam Lee", "position": "Downtown resident", "body": "I support the store. Right now I need to drive several kilometres for fresh fruit and vegetables. A nearby grocery store would let me walk, carry less, and buy healthy food more often."},
                {"name": "Rosa Alvarez", "position": "Corner store owner", "body": "I oppose it. A large store would draw away the customers who now visit my shop for milk, bread, and snacks. The added delivery trucks would also make the narrow streets more congested."},
            ],
        },
        "learning_notes": "Connect each argument to the speaker's daily experience and role.",
        "questions": [
            {"stem": "What is the central conflict in these viewpoints?", "skill_focus": "gist", "evidence": "Sam wants nearby fresh food; Rosa fears losing customers and adding traffic.", "explanation": "The debate is between resident convenience and the effect on existing local businesses.", "choices": [c("Whether fresh food is healthy", False, "Both value food, but that is not the disagreement."), c("Whether a large store will help residents or harm local shops", True, "The two speakers weigh different effects."), c("Whether delivery trucks are electric", False, "Truck type is not discussed."), c("Whether the street is too wide", False, "Rosa says the streets are narrow.")]},
            {"stem": "Why does Rosa oppose the grocery store?", "skill_focus": "detail", "evidence": "It would draw away the customers who now visit my shop ... added delivery trucks would also make the narrow streets more congested", "explanation": "She fears losing customers and increased congestion.", "choices": [c("She believes the store will lower rents", False, "Rents are not mentioned."), c("She worries about losing customers and added traffic", True, "Both reasons are explicit."), c("She dislikes fruit and vegetables", False, "Her concern is about her shop."), c("She cannot afford to shop there", False, "Her objection is not about her own shopping.")]},
            {"stem": "What can be inferred about Sam?", "skill_focus": "inference", "evidence": "Right now I need to drive several kilometres for fresh fruit and vegetables ... let me walk", "explanation": "Sam lives downtown and wants to shop nearby on foot.", "choices": [c("Sam lives close to downtown and values walkable shopping", True, "The desire to walk and carry less supports this."), c("Sam owns a corner store", False, "Sam is a resident, not a shop owner."), c("Sam prefers driving for groceries", False, "Sam wants to avoid driving."), c("Sam lives far from the proposed site", False, "Sam identifies as a downtown resident.")]},
            {"stem": "What kind of business does Rosa operate?", "skill_focus": "detail", "evidence": "Rosa Alvarez ... Corner store owner", "explanation": "Rosa owns the existing corner store.", "choices": [c("A grocery chain", False, "She runs a small corner store."), c("A corner store", True, "This is her stated role."), c("A delivery company", False, "She is concerned about delivery trucks but does not own one."), c("A fruit stand outside the city", False, "Her shop sells milk, bread, and snacks downtown.")]},
        ],
    },
    {
        "slug": "public-ebike-trails-debate",
        "task_type": "reading_viewpoints",
        "title": "Should Public E-Bikes Be Allowed on Trails?",
        "topic": "Active transportation",
        "difficulty": 2,
        "estimated_level": 7,
        "instructions": "Compare the viewpoints and answer the questions.",
        "stimulus": {
            "type": "viewpoints",
            "title": "Should e-bikes be allowed on the riverside path?",
            "background": "The city is deciding whether to allow electric bicycles on its busy multi-use riverside path.",
            "speakers": [
                {"name": "Priya Nair", "position": "E-bike commuter", "body": "I support allowing them. An e-bike shortens my commute and keeps me off dangerous roads with fast traffic. Many riders are careful and simply want a safer, quicker way to get to work."},
                {"name": "Tom Wilson", "position": "Runner and path user", "body": "I oppose it. Faster e-bikes can surprise walkers and runners on a path that is already crowded. A narrow trail is not the right place to mix high speeds with children and strollers."},
            ],
        },
        "learning_notes": "Track who uses the path now and how each speaker predicts safety will change.",
        "questions": [
            {"stem": "What is the speakers' main disagreement?", "skill_focus": "gist", "evidence": "Priya sees a safer commute; Tom sees speed conflicts on a crowded path.", "explanation": "They disagree about whether e-bikes make the path safer or more dangerous.", "choices": [c("The cost of an e-bike", False, "Cost is not discussed."), c("Whether e-bikes belong on the crowded path", True, "The question is access and safety on the path."), c("Whether running is good exercise", False, "That is not the issue."), c("Whether roads are too wide", False, "Priya says roads feel dangerous.")]},
            {"stem": "Why does Tom oppose allowing e-bikes?", "skill_focus": "detail", "evidence": "Faster e-bikes can surprise walkers and runners ... not the right place to mix high speeds with children", "explanation": "Tom fears speed conflicts and crowding.", "choices": [c("He thinks e-bikes are too expensive", False, "Cost is not his concern."), c("He fears speed conflicts with pedestrians", True, "This is his stated reason."), c("He wants the path closed entirely", False, "He wants to keep e-bikes off, not close the path."), c("He dislikes commuting", False, "He is not discussing commuting.")]},
            {"stem": "What can be inferred about Priya's commute?", "skill_focus": "inference", "evidence": "An e-bike shortens my commute and keeps me off dangerous roads with fast traffic", "explanation": "Priya currently travels on roads she considers unsafe.", "choices": [c("She feels unsafe on the roads she uses now", True, "She describes avoiding dangerous roads."), c("She does not own an e-bike", False, "She identifies as an e-bike commuter."), c("She prefers running on the path", False, "She is a commuter, not a runner."), c("She wants to sell her e-bike", False, "She supports continued use.")]},
            {"stem": "What kind of path is under discussion?", "skill_focus": "detail", "evidence": "busy multi-use riverside path", "explanation": "The path is multi-use and already busy.", "choices": [c("A private bike lane", False, "It is a public multi-use path."), c("A busy multi-use riverside path", True, "This is stated in the background."), c("A road with fast traffic", False, "That describes the alternative to the path."), c("A children's playground", False, "Children are mentioned as users, not the setting.")]},
        ],
    },
    {
        "slug": "school-phone-ban-debate",
        "task_type": "reading_viewpoints",
        "title": "Should Schools Ban Phones?",
        "topic": "Education",
        "difficulty": 2,
        "estimated_level": 7,
        "instructions": "Compare the viewpoints and answer the questions.",
        "stimulus": {
            "type": "viewpoints",
            "title": "Should the district ban phones for the whole school day?",
            "background": "A school district is considering requiring students to store phones away from class all day.",
            "speakers": [
                {"name": "Maria Santos", "position": "Parent", "body": "I support a full-day ban. Phones distract students during lessons and increase social comparison during breaks. Removing them would help young people pay attention and talk with classmates in person."},
                {"name": "Jordan Lee", "position": "Student", "body": "I oppose it. Students sometimes need to contact family in an emergency, and many use phones to check school calendars and learning apps. A total ban feels more like punishment than a real solution."},
            ],
        },
        "learning_notes": "Identify the exact problem each speaker is trying to solve.",
        "questions": [
            {"stem": "What is the speakers' main disagreement?", "skill_focus": "gist", "evidence": "Maria wants fewer distractions; Jordan wants emergency access and learning tools.", "explanation": "They disagree about whether a full-day ban improves learning or removes useful access.", "choices": [c("Whether phones can make calls", False, "Phone capabilities are not disputed."), c("Whether a full-day ban helps or harms students", True, "The two speakers weigh different outcomes."), c("Whether school calendars exist", False, "Both likely accept the calendars exist."), c("Whether students should talk in person", False, "Maria supports it; Jordan does not directly object to talking.")]},
            {"stem": "Why does Jordan oppose the ban?", "skill_focus": "detail", "evidence": "contact family in an emergency ... check school calendars and learning apps", "explanation": "Jordan values emergency contact and phone-based learning tools.", "choices": [c("Students want more social media time", False, "Jordan does not mention social media."), c("Phones provide emergency contact and learning tools", True, "Both reasons are stated."), c("Teachers need phones in class", False, "The argument concerns students."), c("The district cannot enforce rules", False, "Enforcement is not discussed.")]},
            {"stem": "What can be inferred about Maria's view of phone use?", "skill_focus": "inference", "evidence": "Phones distract students during lessons and increase social comparison", "explanation": "Maria sees phones as a source of distraction and social pressure.", "choices": [c("She believes phones interfere with focus and social wellbeing", True, "Her examples support this."), c("She wants phones used only at lunch", False, "She supports a full-day ban."), c("She thinks phones are educational", False, "She emphasizes distraction rather than learning benefits."), c("She is a student", False, "She is identified as a parent.")]},
            {"stem": "What is the district considering?", "skill_focus": "detail", "evidence": "requiring students to store phones away from class all day", "explanation": "The proposal is a full-day phone storage policy.", "choices": [c("A one-hour phone break", False, "The proposal is more restrictive."), c("A full-day ban on phones", True, "This matches the stated policy."), c("A new phone app for students", False, "The district is not introducing an app."), c("No change to phone rules", False, "The district is considering a change.")]},
        ],
    },
    {
        "slug": "downtown-paid-parking-debate",
        "task_type": "reading_viewpoints",
        "title": "Should the Town Charge for Parking?",
        "topic": "Municipal finance",
        "difficulty": 2,
        "estimated_level": 8,
        "instructions": "Compare the viewpoints and answer the questions.",
        "stimulus": {
            "type": "viewpoints",
            "title": "Should downtown street parking become paid parking?",
            "background": "The town is considering charging for downtown street parking to fund road repairs.",
            "speakers": [
                {"name": "Hana Osei", "position": "Clothing shop owner", "body": "I oppose the fee. Free parking brings shoppers who might otherwise order online or drive to the mall. Adding a charge would reduce the small advantage our independent shops still have."},
                {"name": "Greg Novak", "position": "Resident", "body": "I support it. The town needs a steady source of money for potholes and sidewalks, and paid parking encourages people to stay only as long as they need to, freeing spaces for other visitors."},
            ],
        },
        "learning_notes": "Trace each speaker's claim from the fee to a predicted result for the downtown.",
        "questions": [
            {"stem": "What is the speakers' main disagreement?", "skill_focus": "gist", "evidence": "Hana predicts lost shoppers; Greg predicts needed revenue and better space turnover.", "explanation": "They disagree about whether the fee will help or hurt the downtown.", "choices": [c("The colour of the parking signs", False, "Sign colour is not mentioned."), c("Whether paid parking will benefit or harm the town", True, "Their predicted effects are opposite."), c("Whether potholes need repair", False, "Both likely agree roads need repair."), c("Whether shoppers use online stores", False, "Hana mentions online stores, but the disagreement is broader.")]},
            {"stem": "Why does Hana oppose the fee?", "skill_focus": "detail", "evidence": "Adding a charge would reduce the small advantage our independent shops still have", "explanation": "She fears the fee will drive customers away from independent shops.", "choices": [c("She wants potholes left unrepaired", False, "She does not oppose repairs."), c("She believes the fee may send shoppers elsewhere", True, "This is her central concern."), c("She owns a parking company", False, "She owns a clothing shop."), c("She wants higher parking fees", False, "She opposes the fee.")]},
            {"stem": "What can be inferred about Greg's view?", "skill_focus": "inference", "evidence": "paid parking encourages people to stay only as long as they need to, freeing spaces", "explanation": "Greg sees the fee as a tool to manage parking and fund maintenance.", "choices": [c("He sees parking fees as useful for revenue and space turnover", True, "Both ideas appear in his argument."), c("He owns a car repair shop", False, "His role is resident."), c("He wants to close downtown roads", False, "He wants paid parking, not closure."), c("He opposes road repairs", False, "He supports the revenue for repairs.")]},
            {"stem": "What would the parking revenue be used for?", "skill_focus": "detail", "evidence": "The town is considering charging for downtown street parking to fund road repairs", "explanation": "The stated purpose is road repair funding.", "choices": [c("Building a mall", False, "No mall is proposed."), c("Funding road repairs", True, "This is the background purpose."), c("Lowering shop rents", False, "Rents are not mentioned."), c("Hiring more parking officers", False, "No staffing plan is described.")]},
        ],
    },
    {
        "slug": "highway-widening-debate",
        "task_type": "reading_viewpoints",
        "title": "Should a Highway Be Widened?",
        "topic": "Transportation and environment",
        "difficulty": 3,
        "estimated_level": 9,
        "instructions": "Compare the viewpoints and answer the questions.",
        "stimulus": {
            "type": "viewpoints",
            "title": "Should the province widen Highway 9?",
            "background": "The province proposes widening a highway that runs beside a protected wetland to reduce rush-hour congestion.",
            "speakers": [
                {"name": "Nadia Khoury", "position": "Daily commuter", "body": "I support widening the highway. Traffic often barely moves at rush hour, adding nearly an hour to my day. More lanes would shorten travel times and reduce the pollution caused by vehicles idling in congestion."},
                {"name": "Robert Adams", "position": "Wildlife biologist", "body": "I oppose it. Construction would damage a wetland that filters water and supports migrating birds. Widening roads often encourages more driving, so the congestion relief may be temporary while the environmental loss is permanent."},
            ],
        },
        "learning_notes": "Weigh the immediacy of the commuter benefit against the longer-term environmental cost.",
        "questions": [
            {"stem": "What is the speakers' main disagreement?", "skill_focus": "gist", "evidence": "Nadia emphasizes shorter commutes; Robert emphasizes wetland loss and temporary relief.", "explanation": "They disagree about whether the travel benefit justifies the environmental cost.", "choices": [c("Whether birds migrate", False, "The migration itself is not disputed."), c("Whether widening the highway is worth its environmental cost", True, "The two speakers weigh different consequences."), c("Whether commuters use cars", False, "Both acknowledge commuter traffic."), c("Whether wetlands filter water", False, "Nadia does not contest that point.")]},
            {"stem": "Why does Robert oppose the plan?", "skill_focus": "detail", "evidence": "Construction would damage a wetland ... environmental loss is permanent", "explanation": "Robert objects to lasting harm to the wetland and wildlife.", "choices": [c("He wants longer commutes", False, "He does not want longer commutes."), c("He believes the environmental damage would be lasting", True, "This is his stated concern."), c("He thinks the road is too narrow", False, "He opposes widening."), c("He owns land near the highway", False, "No land ownership is mentioned.")]},
            {"stem": "What can be inferred about Nadia's current commute?", "skill_focus": "inference", "evidence": "Traffic often barely moves at rush hour, adding nearly an hour to my day", "explanation": "Nadia regularly loses significant time to congestion.", "choices": [c("She experiences serious rush-hour delays", True, "The added hour supports this."), c("She never drives on Highway 9", False, "She is a daily commuter on the route."), c("She prefers public transit", False, "She argues for more lanes."), c("She works as a wildlife biologist", False, "Robert is the biologist.")]},
            {"stem": "What does Robert predict about congestion relief?", "skill_focus": "detail", "evidence": "Widening roads often encourages more driving, so the congestion relief may be temporary", "explanation": "Robert believes more driving may eventually restore congestion.", "choices": [c("It will end all traffic", False, "He predicts the opposite."), c("It may be temporary", True, "This is his stated prediction."), c("It will reduce pollution permanently", False, "He does not make that claim."), c("It will protect the wetland", False, "He expects the wetland to be damaged.")]},
        ],
    },
]
