"""Advanced original Reading content for CELPIP levels 10-12."""


def c(text, correct, explanation):
    return {"text": text, "is_correct": correct, "explanation": explanation}


READING_SETS = [
    {
        "slug": "service-contract-change-notice",
        "task_type": "reading_correspondence",
        "title": "Service Contract Change Notice",
        "topic": "Business procurement",
        "difficulty": 3,
        "estimated_level": 11,
        "instructions": "Read the email and answer the questions.",
        "stimulus": {
            "type": "email",
            "from": "Provincial Procurement Office",
            "to": "Marta Osei, Operations Director",
            "subject": "Contract amendment effective November 1",
            "body": "Dear Ms. Osei,\n\nThis message confirms the negotiated amendment to your facility-services contract. Beginning November 1, evening cleaning shifts will be reduced from five nights to four nights per week, while daytime waste collection will be added Monday through Thursday.\n\nYour monthly fee will decrease by 12 percent from November 1 to April 30, then return to the original rate unless both parties agree to a new schedule. The amended agreement also introduces a quarterly performance review. If service hours are missed without an approved exemption, a credit equal to 1.5 times the daily rate will be applied to the following invoice.\n\nPlease sign and return the attached amendment by October 15. If we do not receive the signed document by that date, the current agreement will remain in effect until its natural expiry.\n\nRegards,\nProvincial Procurement Office",
        },
        "learning_notes": "Track the effective date, the fee change, and the consequence of not responding.",
        "questions": [
            {"stem": "What is the main purpose of the email?", "skill_focus": "gist", "evidence": "This message confirms the negotiated amendment", "explanation": "The email asks the reader to confirm a negotiated contract change.", "choices": [c("To cancel the current contract", False, "The current contract remains if the amendment is not signed."), c("To confirm a negotiated contract amendment", True, "The body explains the new terms and requests signature."), c("To dispute an invoice credit", False, "No current dispute is described."), c("To announce a new procurement office", False, "The sender is not changing offices.")]},
            {"stem": "What happens if the signed amendment is not returned by October 15?", "skill_focus": "detail", "evidence": "the current agreement will remain in effect", "explanation": "The existing terms continue if the deadline is missed.", "choices": [c("The contract is cancelled immediately", False, "The current agreement remains."), c("A penalty is applied", False, "No penalty is stated."), c("The current agreement remains in effect", True, "This is the stated fallback."), c("The monthly fee increases", False, "The fee change only takes effect under the amendment.")]},
            {"stem": "What is the financial consequence of an unapproved missed service?", "skill_focus": "detail", "evidence": "a credit equal to 1.5 times the daily rate will be applied", "explanation": "The buyer receives a credit above the daily rate.", "choices": [c("A 12 percent discount", False, "That is the monthly fee change."), c("A credit equal to 1.5 times the daily rate", True, "This is the stated remedy."), c("A quarterly review", False, "The review is not a financial remedy."), c("A termination notice", False, "No termination is described.")]},
            {"stem": "What can be inferred about the fee reduction?", "skill_focus": "inference", "evidence": "Your monthly fee will decrease ... then return to the original rate", "explanation": "The reduction is temporary and tied to the new reduced evening schedule.", "choices": [c("It is permanent", False, "It ends April 30 unless renegotiated."), c("It is temporary and linked to the revised service mix", True, "The reduction is limited to a defined period."), c("It applies only to daytime service", False, "It applies to the monthly fee."), c("It is paid back later", False, "The fee returns to the original rate, not a repayment.")]},
        ],
    },
    {
        "slug": "conference-reimbursement-decision",
        "task_type": "reading_correspondence",
        "title": "Conference Reimbursement Decision",
        "topic": "Workplace finance",
        "difficulty": 3,
        "estimated_level": 10,
        "instructions": "Read the email and answer the questions.",
        "stimulus": {
            "type": "email",
            "from": "Finance Services",
            "to": "Dr. Elena Varga",
            "subject": "Reimbursement request outcome",
            "body": "Dear Dr. Varga,\n\nWe have reviewed your request for reimbursement of the registration fee for the National Policy Conference. Your submission included the receipt and a copy of the event program, but it did not include the required prior-approval form.\n\nThe travel policy allows registration reimbursement without prior approval only when the conference is directly required for a current role. Because your current position description does not list conference attendance as a required activity, the fee cannot be reimbursed under the discretionary category.\n\nYou may submit a one-time exception request within ten business days. The exception form requires a written explanation of how the conference supports an approved professional-development plan. If the request is approved, you will be reimbursed at 85 percent of the registration fee rather than the full amount.\n\nPlease contact our office if you believe the missing approval form was submitted separately.\n\nRegards,\nFinance Services",
        },
        "learning_notes": "Distinguish the missing form from the policy reason for denial and the exception route.",
        "questions": [
            {"stem": "Why was the original reimbursement request denied?", "skill_focus": "detail", "evidence": "it did not include the required prior-approval form", "explanation": "The missing form is the stated reason.", "choices": [c("The receipt was invalid", False, "The receipt was included."), c("The prior-approval form was missing", True, "This is stated directly."), c("The event was not real", False, "The program was included."), c("The fee was too high", False, "No fee limit is mentioned.")]},
            {"stem": "What is the policy reason for the denial?", "skill_focus": "inference", "evidence": "attendance is not a required activity", "explanation": "The role does not require conference attendance, so the discretionary category does not apply.", "choices": [c("The conference was not useful", False, "Usefulness is not the criterion."), c("The role does not require conference attendance", True, "This is the underlying policy reason."), c("The employee did not attend", False, "Attendance is not disputed."), c("The event occurred outside the province", False, "Location is not mentioned.")]},
            {"stem": "What can Dr. Varga do next?", "skill_focus": "detail", "evidence": "submit a one-time exception request within ten business days", "explanation": "An exception request is available.", "choices": [c("Resubmit the same request", False, "The same request would still lack approval."), c("Submit an exception request within ten business days", True, "This is the stated option."), c("Ask for a refund from the conference", False, "The email does not suggest this."), c("Appeal to the travel office", False, "The exception is handled through Finance Services.")]},
            {"stem": "What amount would an approved exception provide?", "skill_focus": "detail", "evidence": "reimbursed at 85 percent of the registration fee", "explanation": "The exception covers 85 percent, not the full fee.", "choices": [c("85 percent", True, "This is the stated exception rate."), c("The full amount", False, "The full amount is not available under the exception."), c("50 percent", False, "That is lower than stated."), c("No reimbursement", False, "An approved exception provides partial reimbursement.")]},
        ],
    },
    {
        "slug": "utility-rate-comparison",
        "task_type": "reading_apply_diagram",
        "title": "Utility Rate Comparison",
        "topic": "Household finance",
        "difficulty": 3,
        "estimated_level": 10,
        "instructions": "Use the table to answer the questions.",
        "stimulus": {
            "type": "table",
            "title": "Home electricity plan comparison",
            "columns": ["Plan", "Fixed monthly fee", "Peak rate", "Off-peak rate", "Notes"],
            "rows": [
                ["Basic", "$12", "$0.28", "$0.10", "No renewable option"],
                ["Time-of-use", "$18", "$0.34", "$0.08", "Smart meter required"],
                ["Renewable", "$22", "$0.30", "$0.11", "100% wind or solar"],
                ["Overnight EV", "$25", "$0.36", "$0.05", "Electric-vehicle proof required"],
            ],
            "notes": "Rates are per kilowatt-hour and include tax. A household using most electricity at night may save with Time-of-use or Overnight EV.",
        },
        "learning_notes": "Combine the monthly fee with peak and off-peak use before choosing a plan.",
        "questions": [
            {"stem": "Which plan requires a smart meter?", "skill_focus": "detail", "evidence": "Time-of-use: Smart meter required", "explanation": "The smart meter is required for Time-of-use.", "choices": [c("Basic", False, "Basic has no smart-meter requirement."), c("Time-of-use", True, "This is listed in the notes."), c("Renewable", False, "Renewable does not require one."), c("Overnight EV", False, "Overnight EV requires vehicle proof.")]},
            {"stem": "A driver charges an electric vehicle every night. Which plan is most likely cheapest?", "skill_focus": "inference", "evidence": "Overnight EV off-peak rate is $0.05", "explanation": "The EV plan offers the lowest overnight rate for regular nighttime charging.", "choices": [c("Basic", False, "Basic has a higher off-peak rate."), c("Renewable", False, "Renewable has a much higher off-peak rate."), c("Overnight EV", True, "The low $0.05 off-peak rate supports night charging."), c("Time-of-use", False, "Time-of-use is cheaper than Basic but not as cheap as EV overnight.")]},
            {"stem": "What is the trade-off of the Renewable plan?", "skill_focus": "detail", "evidence": "Renewable has the highest fixed fee among renewable and higher off-peak rate than Time-of-use", "explanation": "The renewable option costs more in the fixed fee and off-peak rate.", "choices": [c("It has no peak pricing", False, "It has peak pricing."), c("It has a higher fixed fee and higher off-peak rate", True, "Both costs are higher than some alternatives."), c("It requires a smart meter", False, "Only Time-of-use requires that."), c("It is only for businesses", False, "No business-only rule is stated.")]},
            {"stem": "Which plan has the lowest fixed monthly fee?", "skill_focus": "detail", "evidence": "Basic: $12", "explanation": "Basic has the lowest fixed fee.", "choices": [c("Basic", True, "The $12 fee is lowest."), c("Time-of-use", False, "Time-of-use is $18."), c("Renewable", False, "Renewable is $22."), c("Overnight EV", False, "Overnight EV is $25.")]},
        ],
    },
    {
        "slug": "airport-parking-options",
        "task_type": "reading_apply_diagram",
        "title": "Airport Parking Options",
        "topic": "Travel planning",
        "difficulty": 3,
        "estimated_level": 12,
        "instructions": "Use the table to answer the questions.",
        "stimulus": {
            "type": "table",
            "title": "Maple International parking",
            "columns": ["Option", "Daily rate", "Distance to terminal", "Notes"],
            "rows": [
                ["Terminal garage", "$28", "2 minutes", "Height limit 2.1 m"],
                ["Economy lot", "$14", "8-minute shuttle", "Shuttle every 15 minutes"],
                ["Valet", "$42", "Door to door", "Booking required"],
                ["Off-site partner", "$10", "12-minute shuttle", "No covered parking"],
            ],
            "notes": "Prices include tax. Electric-vehicle charging is available only in the terminal garage and off-site partner lot. Pre-booking may reduce the economy-lot rate by 10 percent.",
        },
        "learning_notes": "Compare cost, time, vehicle height, and charging access together.",
        "questions": [
            {"stem": "Which option is closest to the terminal?", "skill_focus": "detail", "evidence": "Valet: Door to door", "explanation": "Valet is door to door, so it is closest.", "choices": [c("Terminal garage", False, "Terminal garage is a two-minute walk."), c("Valet", True, "Valet is door to door."), c("Economy lot", False, "Economy lot requires a shuttle."), c("Off-site partner", False, "Off-site partner requires a shuttle.")]},
            {"stem": "Which options offer electric-vehicle charging?", "skill_focus": "detail", "evidence": "charging is available only in the terminal garage and off-site partner lot", "explanation": "Two options have charging.", "choices": [c("Terminal garage and off-site partner lot", True, "Both are named."), c("Economy lot and valet", False, "Neither is named."), c("All options", False, "Only two are named."), c("Only the terminal garage", False, "The off-site partner also offers it.")]},
            {"stem": "A driver has a tall vehicle over 2.1 metres. Which garage option is unsuitable?", "skill_focus": "inference", "evidence": "Terminal garage height limit 2.1 m", "explanation": "The terminal garage cannot accommodate the tall vehicle.", "choices": [c("Terminal garage", True, "The height limit excludes the vehicle."), c("Economy lot", False, "No height limit is shown for the economy lot."), c("Valet", False, "Valet has no listed height limit."), c("Off-site partner", False, "No height limit is shown.")]},
            {"stem": "How can the economy-lot rate be reduced?", "skill_focus": "detail", "evidence": "Pre-booking may reduce the economy-lot rate by 10 percent", "explanation": "Pre-booking gives a 10 percent reduction.", "choices": [c("By using the shuttle", False, "The shuttle is free transportation, not a discount."), c("By pre-booking", True, "This is the stated discount condition."), c("By parking for one hour", False, "The discount is not time-based."), c("By paying cash", False, "No cash discount is stated.")]},
        ],
    },
    {
        "slug": "remote-work-eligibility-policy",
        "task_type": "reading_information",
        "title": "Remote Work Eligibility Policy",
        "topic": "Workplace policy",
        "difficulty": 3,
        "estimated_level": 11,
        "instructions": "Read the policy and answer the questions.",
        "stimulus": {
            "type": "article",
            "title": "Permanent remote-work eligibility",
            "sections": [
                {"heading": "Eligibility", "body": "Employees may request permanent remote work after completing twelve months in a role that can be performed without daily on-site presence. Client-facing and laboratory roles are excluded."},
                {"heading": "Equipment", "body": "The employer provides a laptop, monitor, and headset. Employees are responsible for maintaining a suitable internet connection and a quiet, private workspace."},
                {"heading": "Time zones", "body": "Remote employees must remain available during the core hours of ten to three in the employer's time zone, except for approved flexible arrangements."},
                {"heading": "Review", "body": "Remote status is reviewed every six months and may be withdrawn if performance or client-service standards decline. Employees receive thirty days' notice before a required return to the office."},
            ],
        },
        "learning_notes": "Identify who qualifies, what the employer provides, and what the employee must maintain.",
        "questions": [
            {"stem": "What is the main purpose of the policy?", "skill_focus": "gist", "evidence": "Employees may request permanent remote work after completing twelve months", "explanation": "The policy explains who can work remotely and under what conditions.", "choices": [c("To end all remote work", False, "The policy allows permanent remote work."), c("To explain remote-work eligibility and expectations", True, "All sections define the arrangement."), c("To provide free internet", False, "Employees provide their own internet."), c("To hire remote workers", False, "The policy concerns existing employees.")]},
            {"stem": "Which roles are excluded from remote work?", "skill_focus": "detail", "evidence": "Client-facing and laboratory roles are excluded", "explanation": "Those roles cannot be performed remotely.", "choices": [c("Administrative roles", False, "Administrative roles are not listed as excluded."), c("Client-facing and laboratory roles", True, "Both are named."), c("New employees", False, "New employees can request after twelve months."), c("Part-time employees", False, "Part-time status is not mentioned.")]},
            {"stem": "Why might remote status be withdrawn?", "skill_focus": "detail", "evidence": "may be withdrawn if performance or client-service standards decline", "explanation": "Declining standards can end the arrangement.", "choices": [c("If the employee moves to another city", False, "Location is not the stated reason."), c("If performance or client service declines", True, "This is the stated condition."), c("After twelve months", False, "Twelve months is the eligibility threshold, not a withdrawal."), c("If internet costs rise", False, "Internet cost is not a policy factor.")]},
            {"stem": "What notice is required before a return to the office?", "skill_focus": "detail", "evidence": "thirty days' notice", "explanation": "Employees receive thirty days before returning.", "choices": [c("Seven days", False, "That is too short."), c("Thirty days", True, "This matches the policy."), c("Sixty days", False, "That is longer than stated."), c("No notice", False, "Notice is required.")]},
        ],
    },
    {
        "slug": "residential-noise-bylaw",
        "task_type": "reading_information",
        "title": "Residential Noise Bylaw",
        "topic": "Municipal regulations",
        "difficulty": 3,
        "estimated_level": 10,
        "instructions": "Read the bylaw summary and answer the questions.",
        "stimulus": {
            "type": "article",
            "title": "Residential noise restrictions",
            "sections": [
                {"heading": "Quiet hours", "body": "Excessive noise is prohibited between 10 p.m. and 7 a.m. on weekdays and between 11 p.m. and 8 a.m. on weekends."},
                {"heading": "Construction", "body": "Construction noise is permitted from 7 a.m. to 6 p.m. on weekdays and from 9 a.m. to 4 p.m. on Saturdays. Construction is not permitted on Sundays or public holidays."},
                {"heading": "Exemptions", "body": "Emergency repairs, snow clearing, and permitted public events are exempt from quiet-hour restrictions. Exemptions for major projects require written notice to residents at least seven days in advance."},
                {"heading": "Enforcement", "body": "A first violation may result in a written warning. Repeated violations within twelve months may result in a fine of up to five hundred dollars."},
            ],
        },
        "learning_notes": "Match the day and time to the correct category, then apply exemptions and penalties.",
        "questions": [
            {"stem": "When do weekend quiet hours begin?", "skill_focus": "detail", "evidence": "11 p.m. on weekends", "explanation": "Weekend quiet hours begin at 11 p.m.", "choices": [c("10 p.m.", False, "That is weekdays."), c("11 p.m.", True, "This is the weekend start time."), c("8 a.m.", False, "That is when quiet hours end."), c("7 a.m.", False, "That is the weekday end time.")]},
            {"stem": "Which activity is exempt from quiet-hour rules?", "skill_focus": "detail", "evidence": "Emergency repairs ... are exempt", "explanation": "Emergency repairs are exempt.", "choices": [c("A private party", False, "Private events are not listed as exempt."), c("Emergency repairs", True, "This is listed as exempt."), c("Routine construction", False, "Routine construction is restricted."), c("A loud television", False, "No exemption applies.")]},
            {"stem": "What must happen before a major project receives a noise exemption?", "skill_focus": "detail", "evidence": "written notice to residents at least seven days in advance", "explanation": "Residents must receive written notice.", "choices": [c("A public hearing", False, "No hearing is mentioned."), c("Written notice seven days in advance", True, "This is the requirement."), c("A fine", False, "No fine is required for an exemption."), c("A police visit", False, "No police visit is mentioned.")]},
            {"stem": "What is the maximum fine for repeated violations within twelve months?", "skill_focus": "detail", "evidence": "a fine of up to five hundred dollars", "explanation": "The maximum is $500.", "choices": [c("$100", False, "That is lower than stated."), c("$250", False, "That is lower than stated."), c("$500", True, "This matches the bylaw."), c("$1,000", False, "That is higher than stated.")]},
        ],
    },
    {
        "slug": "congestion-pricing-debate",
        "task_type": "reading_viewpoints",
        "title": "Should the City Introduce Congestion Pricing?",
        "topic": "Transportation policy",
        "difficulty": 3,
        "estimated_level": 12,
        "instructions": "Compare the viewpoints and answer the questions.",
        "stimulus": {
            "type": "viewpoints",
            "title": "Should downtown driving require a congestion fee?",
            "background": "The city is considering a weekday fee for vehicles entering the central business district during rush hour.",
            "speakers": [
                {"name": "Dr. Imran Shah", "position": "Transport economist", "body": "I support the fee. Pricing the most crowded road space encourages some drivers to shift their trip, use transit, or travel outside peak hours. The revenue can be dedicated to more frequent buses and safer cycling, which benefits lower-income commuters who are least likely to own a car."},
                {"name": "Lena Brooks", "position": "Independent retailer", "body": "I oppose the fee. Many of our customers drive in from neighbourhoods with limited transit. A rush-hour charge will feel like a tax on those customers and may push them to suburban malls. The city should improve transit first, then consider pricing only if congestion remains severe."},
            ],
        },
        "learning_notes": "Identify the causal claims and the unstated assumptions behind each position.",
        "questions": [
            {"stem": "What is the main disagreement?", "skill_focus": "gist", "evidence": "Imran expects reduced congestion and better transit; Lena expects lost customers.", "explanation": "They disagree about whether the fee should come before transit improvements.", "choices": [c("Whether congestion exists", False, "Both accept congestion exists."), c("Whether pricing should be introduced before improving transit", True, "The timing and fairness of the fee are central."), c("Whether buses are affordable", False, "Bus fares are not the disagreement."), c("Whether cars are useful", False, "Both acknowledge car use.")]},
            {"stem": "Why does Lena oppose the fee?", "skill_focus": "detail", "evidence": "customers drive in from neighbourhoods with limited transit", "explanation": "She fears the fee will drive customers away.", "choices": [c("She believes the city has no congestion", False, "She implies congestion exists."), c("Customers may shop elsewhere", True, "This is her stated concern."), c("She wants higher transit fares", False, "No fare change is proposed."), c("She owns a parking company", False, "She is a retailer.")]},
            {"stem": "What assumption supports Imran's argument?", "skill_focus": "inference", "evidence": "encourages some drivers to shift their trip, use transit, or travel outside peak hours", "explanation": "He assumes drivers have alternative travel options.", "choices": [c("Every driver will pay without changing", False, "He predicts some will change."), c("Some drivers can choose another time or mode", True, "This is the basis for reduced congestion."), c("Transit is already perfect", False, "He proposes improving it."), c("Retailers will benefit immediately", False, "He does not make that claim.")]},
            {"stem": "What does Imran propose for the fee revenue?", "skill_focus": "detail", "evidence": "revenue can be dedicated to more frequent buses and safer cycling", "explanation": "He wants revenue to support transit and cycling.", "choices": [c("Suburban shopping malls", False, "That is Lena's concern."), c("More frequent buses and safer cycling", True, "Both are named."), c("Lower car taxes", False, "No car-tax cut is mentioned."), c("A new parking garage", False, "No garage is proposed.")]},
        ],
    },
    {
        "slug": "return-to-office-mandate",
        "task_type": "reading_viewpoints",
        "title": "Should the Return-to-Office Mandate Stand?",
        "topic": "Workplace policy",
        "difficulty": 3,
        "estimated_level": 11,
        "instructions": "Compare the viewpoints and answer the questions.",
        "stimulus": {
            "type": "viewpoints",
            "title": "Should employees return to the office three days a week?",
            "background": "A company is requiring most employees to work from the office three days each week, citing collaboration and training needs.",
            "speakers": [
                {"name": "Marcus Lee", "position": "Senior manager", "body": "I support the mandate. Newer employees learn faster when they can observe colleagues, and complex projects benefit from informal conversations that do not happen as easily online. A predictable three-day schedule still allows flexibility for focused home work."},
                {"name": "Sofia Patel", "position": "Software developer", "body": "I oppose the mandate. My team is spread across three offices, so most meetings are already virtual. Commuting three days a week adds time and cost without changing who I work with. Flexibility should be based on the role and team, not a single rule."},
            ],
        },
        "learning_notes": "Separate the manager's organizational goals from the employee's team-specific reality.",
        "questions": [
            {"stem": "What is the central conflict?", "skill_focus": "gist", "evidence": "Marcus values in-person learning; Sofia says her collaboration is already remote.", "explanation": "They disagree about whether a single in-office rule fits all roles.", "choices": [c("Whether the company should have offices", False, "Both accept offices exist."), c("Whether one return-to-office rule fits all roles", True, "This is the disagreement."), c("Whether software teams should exist", False, "The role is not the issue."), c("Whether meetings are useful", False, "Both use meetings.")]},
            {"stem": "Why does Marcus support the mandate?", "skill_focus": "detail", "evidence": "Newer employees learn faster ... complex projects benefit from informal conversations", "explanation": "He values learning and informal collaboration.", "choices": [c("To reduce office rent", False, "Rent is not mentioned."), c("To improve learning and informal collaboration", True, "Both reasons are explicit."), c("To force everyone to commute", False, "His goal is not commuting."), c("To replace virtual meetings", False, "He does not say meetings should stop.")]},
            {"stem": "Why does Sofia believe the mandate is unfair for her team?", "skill_focus": "inference", "evidence": "My team is spread across three offices, so most meetings are already virtual", "explanation": "In-office attendance would not increase face-to-face collaboration with her actual teammates.", "choices": [c("Her teammates are in different offices", True, "The mandate would not change her collaboration pattern."), c("She cannot afford to commute", False, "She mentions cost, but the core issue is team location."), c("Her manager is remote", False, "Manager location is not stated."), c("She dislikes working with others", False, "Her objection is structural, not personal.")]},
            {"stem": "What does Marcus acknowledge about the policy?", "skill_focus": "detail", "evidence": "A predictable three-day schedule still allows flexibility for focused home work", "explanation": "He acknowledges employees retain some home flexibility.", "choices": [c("It removes all flexibility", False, "He says it allows home work."), c("It still allows two days of home work", True, "Three office days imply two home days."), c("It applies only to managers", False, "It applies to most employees."), c("It will end virtual meetings", False, "No such claim is made.")]},
        ],
    },
]
