"""Original starter Reading content. Structural facts follow the public test format."""
# ruff: noqa: E501

TASK_TYPES = [
    {
        "code": "reading_correspondence",
        "skill": "reading",
        "title": "Reading Correspondence",
        "part_number": 1,
        "description": "Read everyday messages and identify purpose, detail, tone, and inference.",
        "strategy": ["Read the subject and opening first.", "Track names, dates, conditions, and requested actions.", "Check each answer against the wording."],
        "common_mistakes": ["Choosing a true detail instead of the main purpose.", "Missing a deadline or exception.", "Adding assumptions not supported by the message."],
    },
    {
        "code": "reading_apply_diagram",
        "skill": "reading",
        "title": "Reading to Apply a Diagram",
        "part_number": 2,
        "description": "Combine a table, schedule, notice, or diagram with a practical situation.",
        "strategy": ["Identify the relevant row and column before comparing options.", "Read notes and exceptions.", "Combine conditions such as age, day, fee, and location."],
        "common_mistakes": ["Reading the right row but wrong column.", "Ignoring a note below the table.", "Stopping after matching only one condition."],
    },
    {
        "code": "reading_information",
        "skill": "reading",
        "title": "Reading for Information",
        "part_number": 3,
        "description": "Read an organized informational text for main ideas, details, and vocabulary.",
        "strategy": ["Scan headings before reading closely.", "Map each question to the relevant section.", "Use surrounding sentences for vocabulary."],
        "common_mistakes": ["Searching the whole text instead of the relevant section.", "Confusing an example with the main idea.", "Choosing a familiar word meaning that does not fit the context."],
    },
    {
        "code": "reading_viewpoints",
        "skill": "reading",
        "title": "Reading for Viewpoints",
        "part_number": 4,
        "description": "Compare positions, supporting reasons, implications, and tone.",
        "strategy": ["State each speaker's position in a few words.", "Match reasons to the correct speaker.", "Distinguish stated claims from reasonable inference."],
        "common_mistakes": ["Mixing evidence from two speakers.", "Treating background information as an opinion.", "Choosing an extreme claim the speaker did not make."],
    },
]


def c(text, correct, explanation):
    return {"text": text, "is_correct": correct, "explanation": explanation}


READING_SETS = [
    {
        "slug": "garden-plot-renewal",
        "task_type": "reading_correspondence",
        "title": "Community Garden Plot Renewal",
        "topic": "Community recreation",
        "difficulty": 2,
        "estimated_level": 7,
        "instructions": "Read the email and answer the questions.",
        "stimulus": {"type": "email", "from": "Lakeshore Garden Association", "to": "Priya Sharma", "subject": "Your garden plot renewal", "body": "Dear Priya,\n\nRenewals for the coming growing season are open. Plot 14 will be held for you until March 31. To keep it, complete the online form and pay the $45 annual fee by that date. Unclaimed plots will then go to people on our waiting list.\n\nAll gardeners contribute six volunteer hours to shared maintenance. Sign-up opens April 5. Our spring cleanup is Saturday, April 12, from 9 a.m. to noon; bring gloves and a rake if possible.\n\nQuestions can be sent to volunteer coordinator Marcus Lee.\n\nHappy gardening,\nThe Lakeshore team"},
        "learning_notes": "Separate the message's central purpose from supporting dates and events.",
        "questions": [
            {"stem": "What is the main purpose of the email?", "skill_focus": "gist", "evidence": "Renewals for the coming growing season are open.", "explanation": "The message explains how Priya can keep her plot.", "choices": [c("To recruit staff for a seedling sale", False, "No staff recruitment is requested."), c("To explain how Priya can renew her plot", True, "Renewal steps and the deadline organize the message."), c("To cancel the spring cleanup", False, "The cleanup is scheduled, not cancelled."), c("To assign Priya a different plot", False, "Her existing plot is being held.")]},
            {"stem": "What must Priya do by March 31?", "skill_focus": "detail", "evidence": "complete the online form and pay the $45 annual fee by that date", "explanation": "Both the form and fee are required by the deadline.", "choices": [c("Finish six volunteer hours", False, "Those hours are seasonal, not due by March 31."), c("Attend the cleanup", False, "Attendance is not stated as a renewal condition."), c("Submit the form and pay $45", True, "Both actions are directly required."), c("Email Marcus to choose a plot", False, "Marcus answers questions; Plot 14 is already assigned.")]},
            {"stem": "What can be inferred from the waiting list?", "skill_focus": "inference", "evidence": "Unclaimed plots will then go to people on our waiting list.", "explanation": "A waiting list suggests demand for plots exceeds availability.", "choices": [c("Plots are unpopular", False, "A waiting list suggests the opposite."), c("The fee is waived for new gardeners", False, "No waiver is mentioned."), c("Many people want a limited number of plots", True, "That is why a waiting list is needed."), c("New gardeners receive priority", False, "The current gardener has priority until the deadline.")]},
            {"stem": "When does the spring cleanup take place?", "skill_focus": "detail", "evidence": "Our spring cleanup is Saturday, April 12, from 9 a.m. to noon", "explanation": "The cleanup is scheduled for a specific Saturday morning.", "choices": [c("Saturday, April 12, from 9 a.m. to noon", True, "This matches the message."), c("Friday, April 11, in the evening", False, "The date and time are different."), c("Sunday, April 13, all afternoon", False, "No Sunday cleanup is mentioned."), c("Saturday, April 5, from 9 a.m. to noon", False, "April 5 is the volunteer sign-up date.")]},
        ],
    },
    {
        "slug": "winter-storm-office-procedure",
        "task_type": "reading_correspondence",
        "title": "Winter Storm Office Procedure",
        "topic": "Workplace communication",
        "difficulty": 1,
        "estimated_level": 6,
        "instructions": "Read the email and answer the questions.",
        "stimulus": {"type": "email", "from": "Human Resources", "to": "All staff", "subject": "Winter storm advisory", "body": "Hello everyone,\n\nHeavy snow is forecast for Thursday. If a storm warning is active by 6:30 a.m., the office will close. Check the employee hotline or staff intranet before leaving home; please do not call reception.\n\nIf the office closes, employees able to work from home should continue regular duties and record those hours using code SNOW. If travel is unsafe while the office remains open, contact your supervisor promptly to arrange leave or remote work.\n\nStay safe,\nHuman Resources"},
        "learning_notes": "Track conditional language: a forecast is not the same as a confirmed closure.",
        "questions": [
            {"stem": "Why was the email sent?", "skill_focus": "purpose", "evidence": "If a storm warning is active ... the office will close.", "explanation": "It explains how staff should respond to a possible storm closure.", "choices": [c("To confirm Thursday's closure", False, "Closure is conditional."), c("To explain the storm closure procedure", True, "The message gives status-check and work instructions."), c("To require permanent remote work", False, "Remote work applies only in the described situation."), c("To change reception hours", False, "Reception is mentioned only as a line not to call.")]},
            {"stem": "How should staff check the office status?", "skill_focus": "detail", "evidence": "Check the employee hotline or staff intranet", "explanation": "The email provides two approved channels.", "choices": [c("Call reception", False, "The email says not to call reception."), c("Wait for local radio", False, "Radio is not listed."), c("Use the hotline or intranet", True, "Both are stated directly."), c("Travel to the office first", False, "Staff should check before leaving home.")]},
            {"stem": "In this email, 'active' most nearly means", "skill_focus": "vocabulary", "evidence": "If a storm warning is active by 6:30 a.m.", "explanation": "An active warning is officially in force at that time.", "choices": [c("officially in effect", True, "This fits the condition for closure."), c("being discussed", False, "Discussion is not an official warning."), c("causing damage", False, "The phrase describes warning status."), c("already cancelled", False, "That is the opposite meaning.")]},
            {"stem": "What should an employee do if the office closes but they can work from home?", "skill_focus": "detail", "evidence": "employees able to work from home should continue regular duties and record those hours using code SNOW", "explanation": "Home-working employees continue their duties and use the SNOW code for hours.", "choices": [c("Call reception for instructions", False, "The email says not to call reception."), c("Continue regular duties and record hours as SNOW", True, "Both actions are stated directly."), c("Take the day off without notice", False, "Employees should contact a supervisor if travel is unsafe."), c("Come to the office if possible", False, "The office is closed under that condition.")]},
        ],
    },
    {
        "slug": "waste-collection-schedule",
        "task_type": "reading_apply_diagram",
        "title": "Neighbourhood Waste Collection Schedule",
        "topic": "Municipal services",
        "difficulty": 2,
        "estimated_level": 6,
        "instructions": "Use the table to answer the questions.",
        "stimulus": {"type": "table", "title": "Westfield collection schedule", "columns": ["Zone", "Day", "Recycling", "Yard waste", "Notes"], "rows": [["A: east of Main Street", "Tuesday", "Blue bin weekly", "April–October", "Extra garbage bags need a $2 tag"], ["B: west of Main Street", "Thursday", "Blue bin weekly", "April–October", "Extra garbage bags need a $2 tag"], ["C: apartments and condos", "Monday", "Shared blue carts", "Not available", "Call 311 to book large-item pickup"]], "notes": "A statutory holiday delays collection by one day for the rest of that week. Put bins out by 7 a.m."},
        "learning_notes": "Match the location to its row, then read across and check the note below the table.",
        "questions": [
            {"stem": "When is recycling collected west of Main Street?", "skill_focus": "detail", "evidence": "Zone B: west of Main Street — Thursday — Blue bin weekly", "explanation": "Zone B's collection day is Thursday.", "choices": [c("Monday", False, "Monday belongs to Zone C."), c("Tuesday", False, "Tuesday belongs to Zone A."), c("Thursday", True, "The Zone B row lists Thursday."), c("Friday", False, "Friday is not listed.")]},
            {"stem": "What happens after a statutory holiday?", "skill_focus": "inference", "evidence": "delays collection by one day for the rest of that week", "explanation": "Residents should expect their collection one day later.", "choices": [c("Collection moves one day later", True, "That restates the note."), c("The entire week is cancelled", False, "The service is delayed, not cancelled."), c("Bins go out one day earlier", False, "A delay moves the service later."), c("Only apartment service changes", False, "The note applies to the schedule generally.")]},
            {"stem": "Who should call 311?", "skill_focus": "detail", "evidence": "Zone C ... Call 311 to book large-item pickup", "explanation": "The instruction is attached to apartment and condo service.", "choices": [c("A Zone A resident with a blue bin", False, "Zone A has no 311 instruction."), c("An apartment resident arranging a large-item pickup", True, "That matches Zone C's note."), c("A Zone B resident buying a bag tag", False, "Bag tags are separate from large-item booking."), c("Anyone reporting a holiday", False, "The note does not ask residents to report holidays.")]},
            {"stem": "By what time should bins be put out?", "skill_focus": "detail", "evidence": "Put bins out by 7 a.m.", "explanation": "The table note gives a 7 a.m. deadline for placing bins out.", "choices": [c("By 6 a.m.", False, "The note says 7 a.m."), c("By 7 a.m.", True, "This matches the instruction."), c("By 8 a.m.", False, "That is later than stated."), c("The night before", False, "No night-before instruction is given.")]},
        ],
    },
    {
        "slug": "recreation-drop-in-schedule",
        "task_type": "reading_apply_diagram",
        "title": "Recreation Centre Drop-In Schedule",
        "topic": "Community recreation",
        "difficulty": 3,
        "estimated_level": 8,
        "instructions": "Use the schedule to answer the questions.",
        "stimulus": {"type": "table", "title": "Maple Ridge drop-in programs", "columns": ["Program", "Days", "Time", "Fee", "Notes"], "rows": [["Open Swim", "Mon/Wed/Fri", "7:00–8:30 a.m.", "$5.50", "Ages 16+"], ["Family Swim", "Sat/Sun", "1:00–3:00 p.m.", "$3 per person", "Children under 12 need an adult"], ["Pickleball", "Tue/Thu", "9:00–10:30 a.m.", "$4", "Paddles available"], ["Yoga Basics", "Tuesday", "6:30–7:30 p.m.", "$6", "Bring a mat"]], "notes": "Fees include tax. Members enter free. Arrive ten minutes early."},
        "learning_notes": "Check every condition: activity, age, day, time, fee, and special note.",
        "questions": [
            {"stem": "Which program has the longest session?", "skill_focus": "detail", "evidence": "Family Swim runs 1:00–3:00 p.m.; the others last 60 or 90 minutes.", "explanation": "Family Swim lasts two hours.", "choices": [c("Open Swim", False, "It lasts 90 minutes."), c("Family Swim", True, "It lasts 120 minutes."), c("Pickleball", False, "It lasts 90 minutes."), c("Yoga Basics", False, "It lasts 60 minutes.")]},
            {"stem": "Which swim option can a 13-year-old attend?", "skill_focus": "inference", "evidence": "Open Swim is ages 16+; only children under 12 need an adult at Family Swim.", "explanation": "A 13-year-old is too young for Open Swim but may attend Family Swim.", "choices": [c("Open Swim only", False, "Open Swim requires age 16 or older."), c("Family Swim", True, "The under-12 adult rule does not exclude a 13-year-old."), c("Neither swim", False, "Family Swim remains available."), c("Yoga Basics only", False, "The question asks about swimming.")]},
            {"stem": "What does 'drop-in' most likely mean here?", "skill_focus": "vocabulary", "evidence": "Per-visit fees are listed and members enter free.", "explanation": "Participants can attend an individual session rather than enrol for a season.", "choices": [c("Attend casually by the visit", True, "The per-session schedule and fees support this."), c("Register for a full year", False, "That conflicts with drop-in use."), c("Receive a first-visit discount", False, "No discount is stated."), c("Arrive after the start time", False, "The note says to arrive early.")]},
            {"stem": "Which program takes place on both Tuesday and Thursday?", "skill_focus": "detail", "evidence": "Pickleball: Tue/Thu, 9:00-10:30 a.m.", "explanation": "Pickleball is listed on two weekday mornings.", "choices": [c("Open Swim", False, "Open Swim is Monday, Wednesday, and Friday."), c("Family Swim", False, "Family Swim is on weekends."), c("Pickleball", True, "Pickleball runs on Tuesday and Thursday."), c("Yoga Basics", False, "Yoga Basics is Tuesday only.")]},
        ],
    },
    {
        "slug": "cedar-hill-garden-guidelines",
        "task_type": "reading_information",
        "title": "Cedar Hill Garden Guidelines",
        "topic": "Community gardening rules",
        "difficulty": 1,
        "estimated_level": 5,
        "instructions": "Read the information and answer the questions.",
        "stimulus": {"type": "article", "title": "Cedar Hill Community Garden", "sections": [{"heading": "Plot assignments", "body": "Plots are assigned each spring on a first-come basis. The $40 annual fee covers water and shared tools. Keep the provided plot-number sign visible."}, {"heading": "Watering and maintenance", "body": "Central taps operate from 6 a.m. to 9 p.m. Weed your plot weekly, keep shared paths clear, and return borrowed tools by sunset."}, {"heading": "Plant restrictions", "body": "Invasive plants are prohibited. Plants taller than 1.5 metres must stay away from the centre so they do not shade neighbouring plots."}, {"heading": "Renewal", "body": "Submit a renewal form by October 15 to keep the same plot. Unrenewed plots go to the waiting list in November."}]},
        "learning_notes": "Scan headings first, then match exact rules and dates to the question.",
        "questions": [
            {"stem": "What is the main purpose of the guidelines?", "skill_focus": "gist", "evidence": "The sections describe assignments, maintenance, restrictions, and renewal.", "explanation": "The article sets expectations for garden members.", "choices": [c("To tell the garden's history", False, "No history is provided."), c("To explain rules members must follow", True, "All sections contain rules or procedures."), c("To sell plots as property", False, "Plots are assigned, not sold."), c("To advertise a festival", False, "No festival appears.")]},
            {"stem": "How can a gardener keep the same plot?", "skill_focus": "detail", "evidence": "Submit a renewal form by October 15", "explanation": "The renewal section states the required action and deadline.", "choices": [c("Pay in November", False, "November concerns the waiting list."), c("Move plants to the centre", False, "Tall plants should stay away from the centre."), c("Submit a form by October 15", True, "This is stated directly."), c("Return every tool by October", False, "Tools are returned by sunset after use.")]},
            {"stem": "The word 'prohibited' most nearly means", "skill_focus": "vocabulary", "evidence": "Invasive plants are prohibited.", "explanation": "The restriction means those plants are not allowed.", "choices": [c("encouraged", False, "That is the opposite."), c("measured", False, "Measurement is unrelated."), c("forbidden", True, "Forbidden means not allowed."), c("delayed", False, "Timing is not the issue.")]},
            {"stem": "When do the central water taps operate?", "skill_focus": "detail", "evidence": "Central taps operate from 6 a.m. to 9 p.m.", "explanation": "The taps are available during those hours.", "choices": [c("From 6 a.m. to 9 p.m.", True, "This matches the maintenance section."), c("From 9 a.m. to 6 p.m.", False, "Those hours are reversed."), c("Only on weekends", False, "No weekend restriction is stated."), c("After sunset only", False, "Tools, not taps, must be returned by sunset.")]},
        ],
    },
    {
        "slug": "northgate-library-closure",
        "task_type": "reading_information",
        "title": "Northgate Library Service Changes",
        "topic": "Public library services",
        "difficulty": 2,
        "estimated_level": 6,
        "instructions": "Read the notice and answer the questions.",
        "stimulus": {"type": "article", "title": "Temporary closure and service changes", "sections": [{"heading": "Closure", "body": "Northgate branch closes September 5 through November 30 for roof repairs and accessibility upgrades, including a rebuilt ramp and accessible washroom."}, {"heading": "Temporary services", "body": "The outdoor book drop stays open. Holds move to Southview branch. A mobile library van visits the Northgate lot Wednesdays from 10 a.m. to 2 p.m."}, {"heading": "Programs", "body": "Children's story time moves to Northgate Community Centre on Tuesday mornings. Public computers are unavailable at Northgate, but staff can book time at other branches."}, {"heading": "Contact", "body": "The service desk answers account and program questions weekdays from 9 a.m. to 5 p.m."}]},
        "learning_notes": "Notice how the text pairs each unavailable service with a temporary alternative.",
        "questions": [
            {"stem": "Where can patrons collect items on hold?", "skill_focus": "detail", "evidence": "Holds move to Southview branch.", "explanation": "Southview is the temporary pickup location.", "choices": [c("The community centre", False, "It hosts story time."), c("Southview branch", True, "The notice assigns holds there."), c("The outdoor book drop", False, "The drop accepts returns."), c("The rebuilt ramp", False, "The ramp is construction work.")]},
            {"stem": "Why is the branch closing?", "skill_focus": "inference", "evidence": "roof repairs and accessibility upgrades", "explanation": "The building needs repair and improved access.", "choices": [c("Staff are on strike", False, "No labour action is mentioned."), c("It is moving permanently", False, "The dates show a temporary closure."), c("The building needs repairs and accessibility work", True, "Both reasons are explicit."), c("The book budget was reduced", False, "Budgets are not discussed.")]},
            {"stem": "What is the notice mainly intended to do?", "skill_focus": "purpose", "evidence": "It lists closure dates, available services, and relocated programs.", "explanation": "It helps patrons use alternatives during the closure.", "choices": [c("Request donations", False, "No donation request appears."), c("Describe library history", False, "There is no history."), c("Promote a new permanent branch", False, "The changes are temporary."), c("Explain temporary changes and alternatives", True, "That summarizes the sections.")]},
            {"stem": "When does the mobile library van visit the Northgate lot?", "skill_focus": "detail", "evidence": "A mobile library van visits the Northgate lot Wednesdays from 10 a.m. to 2 p.m.", "explanation": "The van visits once a week during the closure.", "choices": [c("Weekdays from 9 a.m. to 5 p.m.", False, "That is the service desk's phone hours."), c("Wednesdays from 10 a.m. to 2 p.m.", True, "This matches the temporary services section."), c("Tuesday mornings only", False, "Tuesday is story time at the community centre."), c("Saturdays all day", False, "No Saturday van service is mentioned.")]},
        ],
    },
    {
        "slug": "king-street-bike-lanes",
        "task_type": "reading_viewpoints",
        "title": "Protected Bike Lanes on King Street",
        "topic": "Cycling infrastructure",
        "difficulty": 2,
        "estimated_level": 7,
        "instructions": "Compare the viewpoints and answer the questions.",
        "stimulus": {"type": "viewpoints", "title": "Should Riverside add protected bike lanes?", "background": "Council is considering replacing two car lanes and about sixty parking spaces with protected bike lanes.", "speakers": [{"name": "Maya Chen", "position": "Bookshop owner", "body": "I support the lanes. Many customers walk or cycle, but sharing the road with cars feels dangerous. Safer cycling would encourage people to stop downtown and browse longer."}, {"name": "David Tremblay", "position": "Courier driver", "body": "I oppose the plan. Fewer car lanes will worsen rush-hour traffic, and lost parking will hurt businesses. Deliveries will take longer if drivers must park farther away and carry packages down the block."}]},
        "learning_notes": "Write each speaker's position and reasons separately before comparing them.",
        "questions": [
            {"stem": "What is the speakers' main disagreement?", "skill_focus": "gist", "evidence": "Maya predicts safer access and more visits; David predicts congestion and business harm.", "explanation": "They disagree about whether the lane conversion will benefit King Street.", "choices": [c("The colour of the lanes", False, "Colour is not discussed."), c("The date of the council vote", False, "No view about timing is given."), c("Whether the conversion will benefit the street", True, "Their predicted outcomes are opposite."), c("Whether bicycles should be banned downtown", False, "David opposes this plan, not all bicycles.")]},
            {"stem": "Why does David expect deliveries to take longer?", "skill_focus": "detail", "evidence": "drivers must park farther away and carry packages down the block", "explanation": "He connects lost nearby parking with slower deliveries.", "choices": [c("The courier company will shrink", False, "Fleet size is not mentioned."), c("Drivers will park farther away", True, "David states this directly."), c("Roads will close at rush hour", False, "He predicts traffic, not closure."), c("Cyclists will carry the packages", False, "That is not suggested.")]},
            {"stem": "What can be inferred about Maya's customers?", "skill_focus": "inference", "evidence": "Many customers walk or cycle ... Safer cycling would encourage people to stop.", "explanation": "She believes improved safety could attract more cycling visits.", "choices": [c("Most require parking", False, "She emphasizes walking and cycling."), c("They avoid all downtown shops", False, "They already visit her shop."), c("More may cycle if the route feels safer", True, "That follows from her argument."), c("They oppose protected lanes", False, "She provides no such claim.")]},
            {"stem": "What does Maya believe safer cycling would encourage?", "skill_focus": "detail", "evidence": "Safer cycling would encourage people to stop downtown and browse longer.", "explanation": "Maya expects safer routes to bring customers who stay and browse.", "choices": [c("People to stop downtown and browse longer", True, "This is her stated prediction."), c("Drivers to park farther away", False, "That is David's concern."), c("Businesses to close earlier", False, "She expects the opposite effect."), c("Fewer cyclists to visit shops", False, "She predicts more cycling visits.")]},
        ],
    },
    {
        "slug": "municipal-remote-work",
        "task_type": "reading_viewpoints",
        "title": "Municipal Remote Work",
        "topic": "Workplace policy",
        "difficulty": 3,
        "estimated_level": 9,
        "instructions": "Compare the viewpoints and answer the questions.",
        "stimulus": {"type": "viewpoints", "title": "Should remote work remain?", "background": "Lakeland is deciding whether remote work should remain permanent for many administrative employees.", "speakers": [{"name": "Priya Sharma", "position": "Planning analyst", "body": "I support permanent remote work. Removing my two-hour commute gives me energy and family time. My team finished its last project early, and fewer cars help the city's climate goals."}, {"name": "Robert Levesque", "position": "Cafe owner", "body": "Employees should return. City workers once filled nearby cafes at lunch, but the street is now quiet. Downtown shops rely on those customers. Some services, such as permits, are also easier at an in-person counter."}]},
        "learning_notes": "For inference, identify the repeated concern behind a speaker's examples.",
        "questions": [
            {"stem": "The word 'commute' most nearly means", "skill_focus": "vocabulary", "evidence": "Removing my two-hour commute gives me energy and family time.", "explanation": "Commute means regular travel between home and work.", "choices": [c("a work assignment", False, "That is a task, not travel."), c("a trip between home and work", True, "The time and removal of travel support this."), c("a team meeting", False, "Meetings are not described."), c("a performance review", False, "Evaluation is unrelated.")]},
            {"stem": "What is Priya's main purpose?", "skill_focus": "purpose", "evidence": "She lists personal, productivity, and environmental benefits.", "explanation": "She argues that remote work benefits employees and the city.", "choices": [c("Explain how to apply for a job", False, "No application steps appear."), c("Complain that her team is late", False, "She says it finished early."), c("Describe her home office", False, "The room is not described."), c("Argue for keeping remote work", True, "Her examples support that position.")]},
            {"stem": "What is Robert's central concern?", "skill_focus": "inference", "evidence": "Downtown shops rely on those customers ... the street is now quiet.", "explanation": "He worries that reduced worker traffic threatens downtown businesses.", "choices": [c("City employees need higher pay", False, "Pay is not discussed."), c("Downtown businesses may lose customers and close", True, "His cafe example supports this concern."), c("Remote work improves counter service", False, "He argues some in-person services are easier."), c("His cafe is too far from city hall", False, "It is described as nearby.")]},
            {"stem": "What evidence does Robert give for downtown decline?", "skill_focus": "detail", "evidence": "City workers once filled nearby cafes at lunch, but the street is now quiet.", "explanation": "Robert points to quieter lunchtime streets as evidence.", "choices": [c("His cafe has lowered its prices", False, "He does not mention prices."), c("The street is now quiet at lunchtime", True, "This is his observed evidence."), c("The city has closed all permits", False, "No permit closure is described."), c("More workers now commute by car", False, "He does not mention commuting mode.")]},
        ],
    },
]
