"""Expanded original Speaking prompts for the full practice bank."""

from apps.content.speaking_seed_data import (
    SCENE_MARKET,
    SCENE_RECREATION,
    UNUSUAL_INSTRUMENT,
    UNUSUAL_TRICYCLE,
)


def _prompt(
    *,
    slug,
    task_type,
    title,
    topic,
    difficulty,
    level,
    task_kind,
    scenario,
    prompt,
    prep_seconds,
    response_seconds,
    guidance,
    audience=None,
    tone=None,
    image_url=None,
    **extra,
):
    stimulus = {
        "type": "speaking_prompt",
        "task_kind": task_kind,
        "scenario": scenario,
        "prompt": prompt,
        "prep_seconds": prep_seconds,
        "response_seconds": response_seconds,
        "guidance": guidance,
    }
    if audience:
        stimulus["audience"] = audience
    if tone:
        stimulus["tone"] = tone
    if image_url:
        stimulus["image_url"] = image_url
    stimulus.update(extra)
    return {
        "slug": slug,
        "task_type": task_type,
        "title": title,
        "topic": topic,
        "difficulty": difficulty,
        "estimated_level": level,
        "instructions": "Use the preparation time to plan, then record one complete response.",
        "stimulus": stimulus,
        "learning_notes": (
            "Replay your recording once and review it for Content/Coherence, Vocabulary, "
            "Listenability, and Task Fulfillment. Focus on one improvement for your next attempt."
        ),
    }


SPEAKING_SETS = [
    _prompt(
        slug="advice-new-parent-budget",
        task_type="speaking_advice",
        title="Budget Advice for a New Parent",
        topic="Family and finance",
        difficulty=2,
        level=7,
        task_kind="advice",
        scenario="Your friend Jordan is becoming a parent soon and is worried about managing household costs on one income.",
        prompt="Give Jordan practical advice about budgeting, saving on baby costs, and preparing for unexpected expenses.",
        prep_seconds=30,
        response_seconds=90,
        audience="Your friend Jordan",
        tone="Reassuring and practical",
        guidance=["Offer three specific strategies.", "Explain how each one reduces stress."],
    ),
    _prompt(
        slug="advice-public-speaking-nerves",
        task_type="speaking_advice",
        title="Advice for Public Speaking Nerves",
        topic="Workplace communication",
        difficulty=2,
        level=8,
        task_kind="advice",
        scenario="Your coworker Sam must give a presentation next week and is nervous about speaking in front of the team.",
        prompt="Advise Sam on preparing the talk, managing nerves, and handling questions.",
        prep_seconds=30,
        response_seconds=90,
        audience="Your coworker Sam",
        tone="Supportive and encouraging",
        guidance=["Be specific about preparation.", "Include one relaxation technique."],
    ),
    _prompt(
        slug="advice-small-town-move",
        task_type="speaking_advice",
        title="Advice for Moving to a Small Town",
        topic="Settling in Canada",
        difficulty=2,
        level=8,
        task_kind="advice",
        scenario="Your friend Ana is moving from a large city to a small town and is unsure how to make friends and settle in.",
        prompt="Advise Ana on meeting people, learning about local services, and making the most of small-town life.",
        prep_seconds=30,
        response_seconds=90,
        audience="Your friend Ana",
        tone="Friendly and realistic",
        guidance=["Give at least three suggestions.", "Acknowledge one challenge and offer a response."],
    ),
    _prompt(
        slug="advice-starting-university",
        task_type="speaking_advice",
        title="Advice for Starting University",
        topic="Education",
        difficulty=1,
        level=6,
        task_kind="advice",
        scenario="Your younger sibling is starting university next month and feels nervous about managing classes, money, and a new city.",
        prompt="Give your sibling advice about staying organized, finding support, and balancing study with rest.",
        prep_seconds=30,
        response_seconds=90,
        audience="Your younger sibling",
        tone="Warm and practical",
        guidance=["Use a direct and encouraging tone.", "Provide a concrete weekly example."],
    ),
    _prompt(
        slug="experience-helping-neighbour",
        task_type="speaking_experience",
        title="A Time You Helped a Neighbour",
        topic="Community life",
        difficulty=1,
        level=6,
        task_kind="experience",
        scenario="Think of a time when you helped a neighbour solve a problem.",
        prompt="Describe what happened, what you did, and how the experience affected your relationship.",
        prep_seconds=30,
        response_seconds=60,
        guidance=["Choose one clear event.", "Use a beginning, middle, and end."],
    ),
    _prompt(
        slug="experience-last-minute-plan-change",
        task_type="speaking_experience",
        title="A Time Your Plans Changed Suddenly",
        topic="Personal experiences",
        difficulty=2,
        level=7,
        task_kind="experience",
        scenario="Think of a time when your plans changed suddenly and you had to adapt.",
        prompt="Tell the story of what happened, how you responded, and what you learned.",
        prep_seconds=30,
        response_seconds=60,
        guidance=["Keep the chronology clear.", "Explain your feelings at key moments."],
    ),
    _prompt(
        slug="experience-new-food",
        task_type="speaking_experience",
        title="A Time You Tried a New Food",
        topic="Food and culture",
        difficulty=1,
        level=6,
        task_kind="experience",
        scenario="Think of a time when you tried a food you had never eaten before.",
        prompt="Describe where you were, what the food was, and how you reacted.",
        prep_seconds=30,
        response_seconds=60,
        guidance=["Use sensory details.", "Explain whether you would try it again."],
    ),
    _prompt(
        slug="experience-team-project",
        task_type="speaking_experience",
        title="A Time You Worked in a Team",
        topic="Work and education",
        difficulty=2,
        level=8,
        task_kind="experience",
        scenario="Think of a time when you worked with others to finish a difficult project.",
        prompt="Describe the project, your role, and how the team overcame a problem.",
        prep_seconds=30,
        response_seconds=60,
        guidance=["Mention your own contribution.", "Use past tenses consistently."],
    ),
    _prompt(
        slug="scene-summer-park-picnic",
        task_type="speaking_scene",
        title="Summer Park Picnic",
        topic="Parks and recreation",
        difficulty=2,
        level=7,
        task_kind="scene",
        scenario="You are looking at a busy park where families are enjoying a summer afternoon.",
        prompt="Describe the people, the setting, and the important actions to someone who cannot see the scene.",
        prep_seconds=30,
        response_seconds=60,
        image_url=SCENE_MARKET,
        guidance=["Start with the overall setting.", "Move from foreground to background."],
    ),
    _prompt(
        slug="scene-community-skating-rink",
        task_type="speaking_scene",
        title="Community Skating Rink",
        topic="Community recreation",
        difficulty=2,
        level=8,
        task_kind="scene",
        scenario="You are looking at an indoor community rink with skaters of different ages.",
        prompt="Describe the rink, the people, and what is happening so the listener can picture it.",
        prep_seconds=30,
        response_seconds=60,
        image_url=SCENE_RECREATION,
        guidance=["Identify distinct groups of people.", "Use precise action words."],
    ),
    _prompt(
        slug="scene-harvest-market",
        task_type="speaking_scene",
        title="Harvest Farmers Market",
        topic="Food and community",
        difficulty=2,
        level=8,
        task_kind="scene",
        scenario="You are looking at a busy covered market during the autumn harvest.",
        prompt="Describe the market stalls, the people, and the important actions in the scene.",
        prep_seconds=30,
        response_seconds=60,
        image_url=SCENE_MARKET,
        guidance=["Group related details.", "Describe actions as well as objects."],
    ),
    _prompt(
        slug="scene-evening-recreation-centre",
        task_type="speaking_scene",
        title="Evening Recreation Centre",
        topic="Community facilities",
        difficulty=2,
        level=8,
        task_kind="scene",
        scenario="You are looking at a recreation centre lobby during a busy evening.",
        prompt="Describe where people are, what they are doing, and the mood of the scene.",
        prep_seconds=30,
        response_seconds=60,
        image_url=SCENE_RECREATION,
        guidance=["Begin with an overview.", "Use location language such as near, beside, and behind."],
    ),
    _prompt(
        slug="predictions-summer-park",
        task_type="speaking_predictions",
        title="What Will Happen at the Park?",
        topic="Parks and weather",
        difficulty=2,
        level=7,
        task_kind="predictions",
        scenario="Look at the park scene and consider what is likely to happen in the next few minutes.",
        prompt="Make several predictions and connect each one to visible evidence.",
        prep_seconds=30,
        response_seconds=60,
        image_url=SCENE_MARKET,
        guidance=["Predict outcomes for different people.", "Use may, might, and likely."],
    ),
    _prompt(
        slug="predictions-skating-rink",
        task_type="speaking_predictions",
        title="What Will Happen at the Rink?",
        topic="Community recreation",
        difficulty=2,
        level=8,
        task_kind="predictions",
        scenario="Look at the rink scene and think about what is likely to happen next.",
        prompt="Predict what several skaters will do and how the session may end.",
        prep_seconds=30,
        response_seconds=60,
        image_url=SCENE_RECREATION,
        guidance=["Base predictions on visible details.", "Vary your probability language."],
    ),
    _prompt(
        slug="predictions-harvest-market",
        task_type="speaking_predictions",
        title="What Will Happen at the Harvest Market?",
        topic="Food and community",
        difficulty=3,
        level=9,
        task_kind="predictions",
        scenario="Look at the market scene and consider how the approaching closing time may affect the shoppers.",
        prompt="Predict what several people will do before the market closes.",
        prep_seconds=30,
        response_seconds=60,
        image_url=SCENE_MARKET,
        guidance=["Connect each prediction to evidence.", "Use a range of future expressions."],
    ),
    _prompt(
        slug="predictions-recreation-centre-evening",
        task_type="speaking_predictions",
        title="What Will Happen at the Recreation Centre?",
        topic="Community facilities",
        difficulty=2,
        level=8,
        task_kind="predictions",
        scenario="Look at the evening recreation-centre scene and consider what is likely to happen next.",
        prompt="Predict how several visitors will continue their evening and what may occur at the desk.",
        prep_seconds=30,
        response_seconds=60,
        image_url=SCENE_RECREATION,
        guidance=["Focus on visible actions and queues.", "Explain the evidence for each prediction."],
    ),
    _prompt(
        slug="compare-birthday-gift",
        task_type="speaking_compare_persuade",
        title="Choose a Birthday Gift",
        topic="Social planning",
        difficulty=2,
        level=8,
        task_kind="compare_persuade",
        scenario="You and your sibling are choosing one birthday gift for your cousin.",
        prompt="First choose between a best-selling novel and a strategy board game. Then persuade your sibling, who suggests concert tickets, that your choice is better.",
        prep_seconds=120,
        response_seconds=60,
        audience="Your sibling",
        tone="Friendly and persuasive",
        guidance=["Use stage one to choose the novel or board game.", "In stage two compare your choice with concert tickets."],
        prep_stages=[{"label": "Choose", "seconds": 60}, {"label": "Prepare to persuade", "seconds": 60}],
        initial_options=[
            {"key": "novel", "label": "Best-selling novel", "details": ["$28", "Can be enjoyed repeatedly", "Easy to wrap"]},
            {"key": "board_game", "label": "Strategy board game", "details": ["$45", "Playable by four people", "Long replay value"]},
        ],
        competing_option={"key": "concert", "label": "Concert tickets", "details": ["$90", "One evening only", "Subject to scheduling"]},
    ),
    _prompt(
        slug="compare-home-upgrade",
        task_type="speaking_compare_persuade",
        title="Choose a Home Upgrade",
        topic="Home and budgeting",
        difficulty=3,
        level=9,
        task_kind="compare_persuade",
        scenario="You and your partner have a small budget for one home improvement.",
        prompt="First choose between a new dishwasher and a comfortable sofa. Then persuade your partner, who suggests a larger television, that your choice is better.",
        prep_seconds=120,
        response_seconds=60,
        audience="Your partner",
        tone="Reasonable and persuasive",
        guidance=["Compare usefulness, cost, and daily value.", "Acknowledge one benefit of the television."],
        prep_stages=[{"label": "Choose", "seconds": 60}, {"label": "Prepare to persuade", "seconds": 60}],
        initial_options=[
            {"key": "dishwasher", "label": "New dishwasher", "details": ["$620", "Saves time daily", "Lower water use"]},
            {"key": "sofa", "label": "Comfortable sofa", "details": ["$580", "Improves shared space", "Seats five"]},
        ],
        competing_option={"key": "television", "label": "Larger television", "details": ["$700", "Great for movies", "Requires wall mounting"]},
    ),
    _prompt(
        slug="compare-volunteer-activity",
        task_type="speaking_compare_persuade",
        title="Choose a Volunteer Activity",
        topic="Community volunteering",
        difficulty=2,
        level=8,
        task_kind="compare_persuade",
        scenario="You and a friend want to volunteer together for one afternoon a month.",
        prompt="First choose between tutoring students and helping at an animal shelter. Then persuade your friend, who suggests a food bank, that your choice is better.",
        prep_seconds=120,
        response_seconds=60,
        audience="A close friend",
        tone="Enthusiastic and fair",
        guidance=["Compare the skills and impact of each option.", "Acknowledge one benefit of the food bank."],
        prep_stages=[{"label": "Choose", "seconds": 60}, {"label": "Prepare to persuade", "seconds": 60}],
        initial_options=[
            {"key": "tutoring", "label": "Tutoring students", "details": ["Weekly commitment", "Use your skills", "Builds relationships"]},
            {"key": "animal_shelter", "label": "Animal shelter", "details": ["Active work", "Help animals", "Weekend shifts"]},
        ],
        competing_option={"key": "food_bank", "label": "Food bank", "details": ["Flexible shifts", "Immediate impact", "Physical work"]},
    ),
    _prompt(
        slug="compare-weekend-course",
        task_type="speaking_compare_persuade",
        title="Choose a Weekend Course",
        topic="Leisure and learning",
        difficulty=2,
        level=8,
        task_kind="compare_persuade",
        scenario="You and your sibling want to take one weekend course together.",
        prompt="First choose between first aid and basic cooking. Then persuade your sibling, who suggests yoga, that your choice is better.",
        prep_seconds=120,
        response_seconds=60,
        audience="Your sibling",
        tone="Friendly and persuasive",
        guidance=["Use stage one to choose first aid or cooking.", "Compare your choice with yoga in stage two."],
        prep_stages=[{"label": "Choose", "seconds": 60}, {"label": "Prepare to persuade", "seconds": 60}],
        initial_options=[
            {"key": "first_aid", "label": "First aid", "details": ["$85", "Certification included", "Practical skill"]},
            {"key": "cooking", "label": "Basic cooking", "details": ["$75", "Six classes", "Ingredients included"]},
        ],
        competing_option={"key": "yoga", "label": "Yoga", "details": ["$90", "Eight classes", "Relaxing and active"]},
    ),
    _prompt(
        slug="difficult-broken-borrowed-item",
        task_type="speaking_difficult_situation",
        title="A Broken Borrowed Item",
        topic="Friendship and honesty",
        difficulty=2,
        level=8,
        task_kind="difficult_situation",
        scenario="You borrowed a friend's blender and accidentally broke it. You are not sure whether to tell them before they ask or wait until they notice.",
        prompt="Decide how to handle the situation. Speak to your friend, explain what happened, and propose a fair solution.",
        prep_seconds=60,
        response_seconds=60,
        audience="Your friend",
        tone="Honest and apologetic",
        guidance=["State your decision clearly.", "Offer a realistic repair or replacement."],
        choices=["Tell your friend immediately", "Wait until they ask"],
    ),
    _prompt(
        slug="difficult-cancel-dinner",
        task_type="speaking_difficult_situation",
        title="Cancelling a Long-Standing Dinner",
        topic="Social obligations",
        difficulty=2,
        level=8,
        task_kind="difficult_situation",
        scenario="You promised to attend a friend's monthly dinner, but an important work event was moved to the same evening.",
        prompt="Decide whether to attend the dinner or the work event. Speak to the person affected and propose a solution.",
        prep_seconds=60,
        response_seconds=60,
        audience="Either your friend or your manager",
        tone="Apologetic and solution-focused",
        guidance=["Make your choice explicit.", "Offer a concrete alternative."],
        choices=["Attend the dinner", "Attend the work event"],
    ),
    _prompt(
        slug="difficult-neighbour-tree",
        task_type="speaking_difficult_situation",
        title="A Neighbour's Overgrown Tree",
        topic="Neighbourhood relationships",
        difficulty=3,
        level=9,
        task_kind="difficult_situation",
        scenario="Your neighbour's tree now blocks most of the light into your garden, and several branches hang over your roof.",
        prompt="Decide how to raise the issue. Speak to your neighbour, explain the problem tactfully, and propose a fair plan.",
        prep_seconds=60,
        response_seconds=60,
        audience="Your neighbour",
        tone="Respectful and constructive",
        guidance=["Acknowledge that they may not have noticed.", "Suggest a shared or clear solution."],
        choices=["Ask them to trim the tree", "Offer to share trimming costs"],
    ),
    _prompt(
        slug="difficult-returning-gift",
        task_type="speaking_difficult_situation",
        title="Returning an Unwanted Gift",
        topic="Social relationships",
        difficulty=2,
        level=8,
        task_kind="difficult_situation",
        scenario="A relative gave you an expensive kitchen appliance you already own. You want to return it but do not want to hurt their feelings.",
        prompt="Decide whether to return the gift or keep it. Speak to your relative and explain your decision kindly.",
        prep_seconds=60,
        response_seconds=60,
        audience="Your relative",
        tone="Grateful and gentle",
        guidance=["Lead with appreciation.", "Be clear about your decision."],
        choices=["Return the gift", "Keep the gift"],
    ),
    _prompt(
        slug="opinion-school-uniforms",
        task_type="speaking_opinions",
        title="Should Schools Require Uniforms?",
        topic="Education",
        difficulty=2,
        level=8,
        task_kind="opinions",
        scenario="Your local school district is considering a mandatory uniform policy for all students.",
        prompt="Do you think schools should require uniforms? Give reasons and examples for your opinion.",
        prep_seconds=30,
        response_seconds=90,
        audience="Parents at a school meeting",
        tone="Clear and considered",
        guidance=["Take a clear position immediately.", "Consider cost, identity, and school climate."],
    ),
    _prompt(
        slug="opinion-plastic-bag-ban",
        task_type="speaking_opinions",
        title="Should the City Ban Plastic Bags?",
        topic="Environment and public policy",
        difficulty=2,
        level=8,
        task_kind="opinions",
        scenario="Your city is considering a complete ban on single-use plastic shopping bags.",
        prompt="Do you think the city should ban plastic bags? Support your view with specific reasons.",
        prep_seconds=30,
        response_seconds=90,
        audience="Residents at a public consultation",
        tone="Clear and reasoned",
        guidance=["Consider businesses, shoppers, and the environment.", "Answer one likely objection."],
    ),
    _prompt(
        slug="opinion-employer-commute-pay",
        task_type="speaking_opinions",
        title="Should Employers Pay for Commutes?",
        topic="Workplace policy",
        difficulty=3,
        level=9,
        task_kind="opinions",
        scenario="Some employers are considering a monthly payment to cover part of employees' commuting costs.",
        prompt="Do you think employers should help pay for commuting? Give reasons and examples.",
        prep_seconds=30,
        response_seconds=90,
        audience="A workplace discussion group",
        tone="Professional and balanced",
        guidance=["Think about fairness and cost.", "Respond to a possible objection."],
    ),
    _prompt(
        slug="opinion-service-fees",
        task_type="speaking_opinions",
        title="Should Restaurants Include Service Fees?",
        topic="Consumer services",
        difficulty=2,
        level=8,
        task_kind="opinions",
        scenario="Some restaurants are replacing tipping with a fixed service fee added to every bill.",
        prompt="Do you think restaurants should include a service fee instead of tipping? Explain your opinion.",
        prep_seconds=30,
        response_seconds=90,
        audience="Fellow diners and restaurant workers",
        tone="Fair and practical",
        guidance=["Consider workers, customers, and restaurant owners.", "Use everyday examples."],
    ),
    _prompt(
        slug="unusual-plant-covered-vehicle",
        task_type="speaking_unusual",
        title="A Plant-Covered Delivery Vehicle",
        topic="Urban environment",
        difficulty=2,
        level=8,
        task_kind="unusual",
        scenario="You call a friend because an extraordinary delivery vehicle covered with living plants has stopped outside your building.",
        prompt="Describe the vehicle, its unusual covering, and what the people around it are doing.",
        prep_seconds=30,
        response_seconds=60,
        audience="A friend on a phone call",
        tone="Surprised and descriptive",
        image_url=UNUSUAL_TRICYCLE,
        guidance=["Describe the overall shape first.", "Compare the unusual parts with familiar objects."],
    ),
    _prompt(
        slug="unusual-oversized-park-instrument",
        task_type="speaking_unusual",
        title="An Oversized Park Instrument",
        topic="Arts and public spaces",
        difficulty=2,
        level=8,
        task_kind="unusual",
        scenario="You are video-calling a family member, but their video is not working. In front of you, a musician is playing an enormous instrument in the park.",
        prompt="Describe the instrument, how it appears to work, and the reactions of people nearby.",
        prep_seconds=30,
        response_seconds=60,
        audience="A family member on the phone",
        tone="Amazed and vivid",
        image_url=UNUSUAL_INSTRUMENT,
        guidance=["Start with size and shape.", "Use comparisons for unfamiliar parts."],
    ),
    _prompt(
        slug="unusual-floating-bicycle",
        task_type="speaking_unusual",
        title="A Floating Bicycle Display",
        topic="Urban design",
        difficulty=3,
        level=9,
        task_kind="unusual",
        scenario="You call a coworker because an unusual bicycle appears to float above the sidewalk outside a gallery.",
        prompt="Describe the bicycle, how it seems to float, and what passers-by are doing.",
        prep_seconds=30,
        response_seconds=60,
        audience="A coworker on the phone",
        tone="Surprised and precise",
        image_url=UNUSUAL_TRICYCLE,
        guidance=["Explain position and materials.", "Clarify what you can and cannot see."],
    ),
    _prompt(
        slug="unusual-water-powered-sculpture",
        task_type="speaking_unusual",
        title="A Water-Powered Sculpture",
        topic="Arts and public spaces",
        difficulty=3,
        level=9,
        task_kind="unusual",
        scenario="You are on a phone call with a friend while standing beside a remarkable sculpture that uses water to create sound.",
        prompt="Describe the sculpture, how the water moves through it, and how people are interacting with it.",
        prep_seconds=30,
        response_seconds=60,
        audience="A friend on a phone call",
        tone="Engaging and descriptive",
        image_url=UNUSUAL_INSTRUMENT,
        guidance=["Describe movement and sound.", "Use familiar comparisons."],
    ),
]
