"""Advanced original Speaking prompts for CELPIP levels 10-12."""

from apps.content.speaking_seed_data import (
    SCENE_MARKET,
    SCENE_RECREATION,
    UNUSUAL_INSTRUMENT,
    UNUSUAL_TRICYCLE,
)


def _prompt(
    *,
    slug,
    task_type,
    title,
    topic,
    difficulty,
    level,
    task_kind,
    scenario,
    prompt,
    prep_seconds,
    response_seconds,
    guidance,
    audience=None,
    tone=None,
    image_url=None,
    **extra,
):
    stimulus = {
        "type": "speaking_prompt",
        "task_kind": task_kind,
        "scenario": scenario,
        "prompt": prompt,
        "prep_seconds": prep_seconds,
        "response_seconds": response_seconds,
        "guidance": guidance,
    }
    if audience:
        stimulus["audience"] = audience
    if tone:
        stimulus["tone"] = tone
    if image_url:
        stimulus["image_url"] = image_url
    stimulus.update(extra)
    return {
        "slug": slug,
        "task_type": task_type,
        "title": title,
        "topic": topic,
        "difficulty": difficulty,
        "estimated_level": level,
        "instructions": "Use the preparation time to plan, then record one complete response.",
        "stimulus": stimulus,
        "learning_notes": (
            "Replay your recording once and review it for Content/Coherence, Vocabulary, "
            "Listenability, and Task Fulfillment. Focus on one improvement for your next attempt."
        ),
    }


SPEAKING_SETS = [
    _prompt(
        slug="advice-career-transition",
        task_type="speaking_advice",
        title="Advice for a Career Transition",
        topic="Career planning",
        difficulty=3,
        level=11,
        task_kind="advice",
        scenario="Your friend has worked in accounting for eight years but wants to move into health-care administration, a field where they have no direct experience.",
        prompt="Give your friend advice about researching the field, gaining relevant experience, and presenting transferable skills.",
        prep_seconds=30,
        response_seconds=90,
        audience="Your friend",
        tone="Encouraging and strategic",
        guidance=["Give at least three concrete steps.", "Connect each step to a likely concern."],
    ),
    _prompt(
        slug="experience-leading-difficult-change",
        task_type="speaking_experience",
        title="Leading a Difficult Change",
        topic="Leadership and work",
        difficulty=3,
        level=11,
        task_kind="experience",
        scenario="Think of a time when you introduced a change that others resisted at first.",
        prompt="Describe the change, the resistance you faced, and how you eventually gained support.",
        prep_seconds=30,
        response_seconds=60,
        guidance=["Use past tenses consistently.", "Explain the turning point clearly."],
    ),
    _prompt(
        slug="scene-multi-generation-market",
        task_type="speaking_scene",
        title="A Multi-Generation Market Scene",
        topic="Community life",
        difficulty=3,
        level=10,
        task_kind="scene",
        scenario="You are looking at a busy covered market where people of several generations are interacting.",
        prompt="Describe the setting, the different groups, and the important actions without naming people.",
        prep_seconds=30,
        response_seconds=60,
        image_url=SCENE_MARKET,
        guidance=["Group related details.", "Use precise location and relationship language."],
    ),
    _prompt(
        slug="predictions-transit-disruption",
        task_type="speaking_predictions",
        title="Predicting Transit Disruption Effects",
        topic="Transportation",
        difficulty=3,
        level=12,
        task_kind="predictions",
        scenario="Look at a busy public space and consider how an announced transit delay is likely to change people's behaviour.",
        prompt="Make several predictions about what different people will do and how the situation may develop.",
        prep_seconds=30,
        response_seconds=60,
        image_url=SCENE_RECREATION,
        guidance=["Use varied probability language.", "Base each prediction on visible evidence."],
    ),
    _prompt(
        slug="compare-community-energy-investment",
        task_type="speaking_compare_persuade",
        title="Choose a Community Energy Investment",
        topic="Environment and budgeting",
        difficulty=3,
        level=12,
        task_kind="compare_persuade",
        scenario="Your residents' association has a budget for one environmental upgrade. A neighbour has a different preferred option.",
        prompt="First choose between rooftop solar panels and a community heat pump. Then persuade your neighbour, who prefers electric-vehicle chargers, that your choice is better.",
        prep_seconds=120,
        response_seconds=60,
        audience="A neighbour",
        tone="Reasoned and collaborative",
        guidance=["Compare cost, climate benefit, and long-term value.", "Acknowledge one benefit of chargers."],
        prep_stages=[{"label": "Choose", "seconds": 60}, {"label": "Prepare to persuade", "seconds": 60}],
        initial_options=[
            {"key": "solar", "label": "Rooftop solar panels", "details": ["$18,000", "Reduces shared electricity", "25-year life"]},
            {"key": "heat_pump", "label": "Community heat pump", "details": ["$15,000", "Efficient heating", "Requires shared maintenance"]},
        ],
        competing_option={"key": "ev_chargers", "label": "EV chargers", "details": ["$12,000", "Serves car owners", "Annual software cost"]},
    ),
    _prompt(
        slug="difficult-shared-expense-decision",
        task_type="speaking_difficult_situation",
        title="A Shared Expense Decision",
        topic="Financial relationships",
        difficulty=3,
        level=11,
        task_kind="difficult_situation",
        scenario="A roommate wants to split the cost of an expensive shared item, but you cannot afford it right now.",
        prompt="Decide whether to contribute or decline. Speak to your roommate tactfully and propose a fair alternative.",
        prep_seconds=60,
        response_seconds=60,
        audience="Your roommate",
        tone="Respectful and firm",
        guidance=["Show you understand the request.", "Set a clear financial boundary."],
        choices=["Contribute to the purchase", "Decline for now"],
    ),
    _prompt(
        slug="opinion-universal-basic-income",
        task_type="speaking_opinions",
        title="Should the Region Pilot a Basic Income?",
        topic="Public policy",
        difficulty=3,
        level=12,
        task_kind="opinions",
        scenario="Your region is considering a small pilot project that would give selected low-income residents a regular guaranteed payment.",
        prompt="Do you think the region should run the pilot? Support your view with reasons and examples.",
        prep_seconds=30,
        response_seconds=90,
        audience="Residents at a consultation",
        tone="Analytical and clear",
        guidance=["Consider cost, dignity, and work incentives.", "Answer one common objection."],
    ),
    _prompt(
        slug="unusual-robotic-delivery-device",
        task_type="speaking_unusual",
        title="A Robotic Delivery Device",
        topic="Technology and public spaces",
        difficulty=3,
        level=12,
        task_kind="unusual",
        scenario="You call a friend because an unusual delivery robot has stopped outside a busy store.",
        prompt="Describe the device, its parts and movement, and how people around it are reacting.",
        prep_seconds=30,
        response_seconds=60,
        audience="A friend on the phone",
        tone="Precise and curious",
        image_url=UNUSUAL_TRICYCLE,
        guidance=["Compare unfamiliar parts to familiar objects.", "Explain what the machine appears to be doing."],
    ),
]
