"""Original CELPIP-General Speaking prompts for editorial review.

The public task structure and timing come from CELPIP's 2026 Speaking Pro
materials. Every scenario and all wording below are original to this project.
"""
# ruff: noqa: E501

# WebP rather than PNG: these are photographic scenes, where PNG's lossless
# encoding cost ~3 MB each (~12 MB for the set). WebP holds the same 1536x1024
# detail at roughly a tenth of the bytes, which matters most on mobile data
# where the image gates the start of a Speaking task.
SCENE_RECREATION = "/speaking/scene-recreation-centre.webp"
SCENE_MARKET = "/speaking/scene-farmers-market.webp"
UNUSUAL_INSTRUMENT = "/speaking/unusual-water-instrument.webp"
UNUSUAL_TRICYCLE = "/speaking/unusual-greenhouse-tricycle.webp"


SPEAKING_TASK_TYPES = [
    {
        "code": "speaking_advice",
        "skill": "speaking",
        "title": "Giving Advice",
        "part_number": 1,
        "description": "Speak directly to someone who needs practical advice.",
        "strategy": [
            "Address the person directly and show that you understand the situation.",
            "Give at least three practical suggestions with a reason or example for each.",
            "Use clear transitions and finish with encouragement.",
        ],
        "common_mistakes": [
            "Listing suggestions without explaining why they would help.",
            "Speaking about the person instead of speaking to them.",
            "Using a tone that is too forceful for friendly advice.",
        ],
    },
    {
        "code": "speaking_experience",
        "skill": "speaking",
        "title": "Talking about a Personal Experience",
        "part_number": 2,
        "description": "Tell a clear, engaging story about a past experience.",
        "strategy": [
            "Choose one specific event quickly and establish when, where, and who.",
            "Tell events in a logical order using past tenses and sensory details.",
            "Explain how you felt and why the experience mattered.",
        ],
        "common_mistakes": [
            "Describing a general habit instead of one event.",
            "Changing tense or chronology so the story is difficult to follow.",
            "Ending without explaining the result or feeling.",
        ],
    },
    {
        "code": "speaking_scene",
        "skill": "speaking",
        "title": "Describing a Scene",
        "part_number": 3,
        "description": "Describe the important people, actions, and setting in an illustration.",
        "strategy": [
            "Begin with a general overview of the place and mood.",
            "Move through the image systematically using location language.",
            "Select several clear actions and add precise visual details.",
        ],
        "common_mistakes": [
            "Trying to mention every object without organizing the description.",
            "Listing nouns instead of describing actions and relationships.",
            "Guessing a story rather than describing visible evidence.",
        ],
    },
    {
        "code": "speaking_predictions",
        "skill": "speaking",
        "title": "Making Predictions",
        "part_number": 4,
        "description": "Use evidence in a familiar scene to predict what will happen next.",
        "strategy": [
            "Make several distinct predictions about different people or events.",
            "Connect each prediction to something visible in the scene.",
            "Use varied future and probability language.",
        ],
        "common_mistakes": [
            "Describing only what is happening now.",
            "Making predictions that have no visible evidence.",
            "Repeating 'will' without varied probability language.",
        ],
    },
    {
        "code": "speaking_compare_persuade",
        "skill": "speaking",
        "title": "Comparing and Persuading",
        "part_number": 5,
        "description": "Choose between two options, then persuade someone who prefers a third.",
        "strategy": [
            "Use the first stage to compare the two original options and choose one.",
            "Use the second stage to compare your choice with the other person's option.",
            "Acknowledge one advantage of their option, then give specific reasons for yours.",
        ],
        "common_mistakes": [
            "Changing the selected option after the second-stage choice appears.",
            "Repeating card details without explaining their importance.",
            "Sounding dismissive instead of friendly and persuasive.",
        ],
    },
    {
        "code": "speaking_difficult_situation",
        "skill": "speaking",
        "title": "Dealing with a Difficult Situation",
        "part_number": 6,
        "description": "Choose a course of action and explain it tactfully to another person.",
        "strategy": [
            "Choose one option and identify the listener before planning.",
            "State the decision clearly, then give two or three convincing reasons.",
            "Recognize the listener's concern and offer a constructive next step.",
        ],
        "common_mistakes": [
            "Trying to take both incompatible options.",
            "Avoiding the difficult message until the response is nearly over.",
            "Using an insensitive tone or failing to offer a solution.",
        ],
    },
    {
        "code": "speaking_opinions",
        "skill": "speaking",
        "title": "Expressing Opinions",
        "part_number": 7,
        "description": "Take a clear position on an everyday issue and support it.",
        "strategy": [
            "State a clear yes/no position immediately.",
            "Develop two or three reasons with specific examples or consequences.",
            "Address a likely objection and end by restating the position.",
        ],
        "common_mistakes": [
            "Discussing both sides without choosing one.",
            "Giving broad claims without examples.",
            "Drifting from the exact question.",
        ],
    },
    {
        "code": "speaking_unusual",
        "skill": "speaking",
        "title": "Describing an Unusual Situation",
        "part_number": 8,
        "description": "Describe an unusual image to a person who cannot see it.",
        "strategy": [
            "Set up the phone-call role and identify what is unusual.",
            "Describe shape, materials, parts, position, and actions with familiar words.",
            "Use comparisons when an exact word is unavailable and close the call naturally.",
        ],
        "common_mistakes": [
            "Forgetting that the listener cannot see the image.",
            "Focusing on ordinary background details before the unusual subject.",
            "Stopping at an unknown word instead of paraphrasing it.",
        ],
    },
]


def _prompt(
    *,
    slug,
    task_type,
    title,
    topic,
    difficulty,
    level,
    task_kind,
    scenario,
    prompt,
    prep_seconds,
    response_seconds,
    guidance,
    audience=None,
    tone=None,
    image_url=None,
    **extra,
):
    stimulus = {
        "type": "speaking_prompt",
        "task_kind": task_kind,
        "scenario": scenario,
        "prompt": prompt,
        "prep_seconds": prep_seconds,
        "response_seconds": response_seconds,
        "guidance": guidance,
    }
    if audience:
        stimulus["audience"] = audience
    if tone:
        stimulus["tone"] = tone
    if image_url:
        stimulus["image_url"] = image_url
    stimulus.update(extra)
    return {
        "slug": slug,
        "task_type": task_type,
        "title": title,
        "topic": topic,
        "difficulty": difficulty,
        "estimated_level": level,
        "instructions": "Use the preparation time to plan, then record one complete response.",
        "stimulus": stimulus,
        "learning_notes": (
            "Replay your recording once and review it for Content/Coherence, Vocabulary, "
            "Listenability, and Task Fulfillment. Focus on one improvement for your next attempt."
        ),
    }


SPEAKING_SETS = [
    _prompt(
        slug="advice-first-canadian-winter",
        task_type="speaking_advice",
        title="Advice for a First Canadian Winter",
        topic="Settling in Canada",
        difficulty=1,
        level=6,
        task_kind="advice",
        scenario="Your cousin Amir has recently moved to Canada and is worried about managing his first very cold winter.",
        prompt="Give Amir practical advice about clothing, travel, and staying comfortable during winter.",
        prep_seconds=30,
        response_seconds=90,
        audience="Your cousin Amir",
        tone="Friendly, reassuring, and practical",
        guidance=["Offer at least three suggestions.", "Explain why each suggestion matters."],
    ),
    _prompt(
        slug="advice-balancing-work-study",
        task_type="speaking_advice",
        title="Advice on Balancing Work and Study",
        topic="Work and education",
        difficulty=2,
        level=8,
        task_kind="advice",
        scenario="Your friend Priya has started evening college classes while working full-time and feels overwhelmed.",
        prompt="Advise Priya on organizing her week, protecting her wellbeing, and asking others for support.",
        prep_seconds=30,
        response_seconds=90,
        audience="Your friend Priya",
        tone="Supportive and realistic",
        guidance=["Prioritize the advice.", "Include a concrete weekly example."],
    ),
    _prompt(
        slug="experience-helpful-stranger",
        task_type="speaking_experience",
        title="A Time a Stranger Helped You",
        topic="Community life",
        difficulty=1,
        level=6,
        task_kind="experience",
        scenario="Think of a time when someone you did not know helped you solve a problem.",
        prompt="Describe what happened, what the person did, and how the experience made you feel.",
        prep_seconds=30,
        response_seconds=60,
        guidance=["Choose one event.", "Use a clear beginning, middle, and end."],
    ),
    _prompt(
        slug="experience-learning-new-skill",
        task_type="speaking_experience",
        title="Learning a Challenging New Skill",
        topic="Personal development",
        difficulty=2,
        level=8,
        task_kind="experience",
        scenario="Think of a time when you learned a skill that was difficult at first.",
        prompt="Tell the story of how you learned it, the challenge you faced, and the moment you noticed progress.",
        prep_seconds=30,
        response_seconds=60,
        guidance=["Use past tenses consistently.", "Include specific actions and feelings."],
    ),
    _prompt(
        slug="scene-winter-recreation-centre",
        task_type="speaking_scene",
        title="Winter Recreation Centre Lobby",
        topic="Community facilities",
        difficulty=1,
        level=6,
        task_kind="scene",
        scenario="You are looking at a busy recreation-centre lobby on a winter afternoon.",
        prompt="Describe the scene to someone who cannot see it. Explain where people are and what they are doing.",
        prep_seconds=30,
        response_seconds=60,
        image_url=SCENE_RECREATION,
        guidance=["Start with an overview.", "Move from foreground to background."],
    ),
    _prompt(
        slug="scene-spring-farmers-market",
        task_type="speaking_scene",
        title="Spring Farmers' Market",
        topic="Shopping and community",
        difficulty=2,
        level=8,
        task_kind="scene",
        scenario="You are looking at a covered farmers' market just before the weather changes.",
        prompt="Describe the market, the people, and the important actions in the scene.",
        prep_seconds=30,
        response_seconds=60,
        image_url=SCENE_MARKET,
        guidance=["Group related details.", "Use precise action and location words."],
    ),
    _prompt(
        slug="predictions-winter-recreation-centre",
        task_type="speaking_predictions",
        title="What Will Happen at the Recreation Centre?",
        topic="Community facilities",
        difficulty=2,
        level=7,
        task_kind="predictions",
        scenario="Look at the recreation-centre scene and consider what is likely to happen in the next few minutes.",
        prompt="Make several predictions and connect each one to visible evidence in the image.",
        prep_seconds=30,
        response_seconds=60,
        image_url=SCENE_RECREATION,
        guidance=["Predict outcomes for different people.", "Explain the evidence for each prediction."],
    ),
    _prompt(
        slug="predictions-spring-farmers-market",
        task_type="speaking_predictions",
        title="What Will Happen at the Market?",
        topic="Shopping and weather",
        difficulty=2,
        level=8,
        task_kind="predictions",
        scenario="Look at the farmers' market scene and consider what is likely to happen next.",
        prompt="Predict what several people will do and how the approaching weather may affect the market.",
        prep_seconds=30,
        response_seconds=60,
        image_url=SCENE_MARKET,
        guidance=["Use may, might, likely, and probably naturally.", "Base predictions on details in the image."],
    ),
    _prompt(
        slug="compare-community-class",
        task_type="speaking_compare_persuade",
        title="Choose a Weekend Community Class",
        topic="Leisure and learning",
        difficulty=2,
        level=8,
        task_kind="compare_persuade",
        scenario="You and your roommate want to take one weekend class together this autumn.",
        prompt="First choose between pottery and beginner photography. Then persuade your roommate, who suggests indoor rock climbing, that your choice is better.",
        prep_seconds=120,
        response_seconds=60,
        audience="Your roommate",
        tone="Friendly and persuasive",
        guidance=["Use stage one to choose pottery or photography.", "In stage two compare your choice with climbing."],
        prep_stages=[
            {"label": "Choose", "seconds": 60},
            {"label": "Prepare to persuade", "seconds": 60},
        ],
        initial_options=[
            {"key": "pottery", "label": "Pottery", "details": ["$145 for six classes", "Materials included", "Saturday morning"]},
            {"key": "photography", "label": "Beginner photography", "details": ["$110 for four walks", "Use any camera", "Sunday afternoon"]},
        ],
        competing_option={"key": "climbing", "label": "Indoor rock climbing", "details": ["$160 for five sessions", "Equipment included", "Friday evening"]},
    ),
    _prompt(
        slug="compare-short-holiday",
        task_type="speaking_compare_persuade",
        title="Choose a Short Holiday",
        topic="Travel planning",
        difficulty=3,
        level=9,
        task_kind="compare_persuade",
        scenario="You and a friend have three days for a nearby holiday and a limited budget.",
        prompt="First choose between a lakeside cabin and a city culture pass. Then persuade your friend, who suggests a guided cycling tour, that your choice is better.",
        prep_seconds=120,
        response_seconds=60,
        audience="A close friend",
        tone="Enthusiastic but reasonable",
        guidance=["Compare cost, activities, and convenience.", "Acknowledge one benefit of cycling before persuading."],
        prep_stages=[
            {"label": "Choose", "seconds": 60},
            {"label": "Prepare to persuade", "seconds": 60},
        ],
        initial_options=[
            {"key": "cabin", "label": "Lakeside cabin", "details": ["$390 total", "Canoe included", "Cook your own meals"]},
            {"key": "city", "label": "City culture pass", "details": ["$210 total", "Museums and transit", "Hotel not included"]},
        ],
        competing_option={"key": "cycling", "label": "Guided cycling tour", "details": ["$330 total", "Meals included", "Moderate fitness needed"]},
    ),
    _prompt(
        slug="difficult-double-booked-volunteer",
        task_type="speaking_difficult_situation",
        title="A Double-Booked Volunteer Shift",
        topic="Community volunteering",
        difficulty=2,
        level=8,
        task_kind="difficult_situation",
        scenario="You promised to lead a food-bank shift, but your sibling's graduation ceremony was unexpectedly moved to the same time.",
        prompt="Choose one commitment. Speak to the person affected by your decision, explain it tactfully, and propose a solution.",
        prep_seconds=60,
        response_seconds=60,
        audience="Either the volunteer coordinator or your sibling",
        tone="Apologetic, clear, and solution-focused",
        guidance=["Make the decision explicit.", "Offer a realistic alternative or repair."],
        choices=["Keep the volunteer shift", "Attend the graduation"],
    ),
    _prompt(
        slug="difficult-neighbour-parking",
        task_type="speaking_difficult_situation",
        title="A Neighbour's Parking Request",
        topic="Neighbourhood relationships",
        difficulty=2,
        level=8,
        task_kind="difficult_situation",
        scenario="A neighbour asks to use your assigned parking space for a month, but a visiting relative may need it several times each week.",
        prompt="Decide whether to agree or refuse. Explain your decision to the neighbour and suggest a fair alternative.",
        prep_seconds=60,
        response_seconds=60,
        audience="Your neighbour",
        tone="Respectful and firm",
        guidance=["Show that you understand the request.", "Set a clear boundary and offer an alternative."],
        choices=["Lend the space for the month", "Keep the space available"],
    ),
    _prompt(
        slug="opinion-free-public-transit-youth",
        task_type="speaking_opinions",
        title="Free Transit for Young People",
        topic="Public services",
        difficulty=2,
        level=8,
        task_kind="opinions",
        scenario="Your city is considering making public transit free for everyone under eighteen.",
        prompt="Do you think the city should adopt this policy? Give reasons and examples for your opinion.",
        prep_seconds=30,
        response_seconds=90,
        audience="Residents at a public consultation",
        tone="Clear and considered",
        guidance=["Take a position immediately.", "Discuss practical effects on families, traffic, or cost."],
    ),
    _prompt(
        slug="opinion-four-day-workweek",
        task_type="speaking_opinions",
        title="A Four-Day Workweek",
        topic="Workplace policy",
        difficulty=3,
        level=9,
        task_kind="opinions",
        scenario="Some employers are considering a four-day workweek while keeping the same weekly pay and productivity targets.",
        prompt="Do you think most workplaces should adopt a four-day week? Support your view with specific reasons.",
        prep_seconds=30,
        response_seconds=90,
        audience="A workplace discussion group",
        tone="Professional and persuasive",
        guidance=["Consider both employees and employers.", "Answer one likely objection."],
    ),
    _prompt(
        slug="unusual-water-instrument",
        task_type="speaking_unusual",
        title="An Unusual Park Instrument",
        topic="Arts and public spaces",
        difficulty=2,
        level=8,
        task_kind="unusual",
        scenario="You are video-calling a friend, but their video is not working. In front of you, a musician is playing a remarkable homemade instrument.",
        prompt="Describe the unusual instrument, how it appears to work, and what the people around it are doing.",
        prep_seconds=30,
        response_seconds=60,
        audience="A friend on a phone call",
        tone="Amazed and descriptive",
        image_url=UNUSUAL_INSTRUMENT,
        guidance=["Describe the overall shape first.", "Compare unfamiliar parts with familiar objects."],
    ),
    _prompt(
        slug="unusual-greenhouse-tricycle",
        task_type="speaking_unusual",
        title="A Greenhouse Delivery Tricycle",
        topic="Urban delivery",
        difficulty=2,
        level=8,
        task_kind="unusual",
        scenario="You call a family member because an extraordinary delivery vehicle has stopped outside your building.",
        prompt="Describe the vehicle, what it carries, and the delivery taking place so the listener can imagine it.",
        prep_seconds=30,
        response_seconds=60,
        audience="A family member on the phone",
        tone="Surprised and engaging",
        image_url=UNUSUAL_TRICYCLE,
        guidance=["Explain how it resembles and differs from a normal bicycle.", "Use position and material words."],
    ),
]
