"""Advanced original Writing prompts for CELPIP levels 10-12."""

TARGET_WORDS = {"min": 150, "max": 200}
EMAIL_DURATION_SECONDS = 27 * 60
SURVEY_DURATION_SECONDS = 26 * 60


def _email(
    *,
    slug,
    title,
    topic,
    difficulty,
    level,
    scenario,
    audience,
    requested_points,
    guidance,
    learning_notes,
):
    return {
        "slug": slug,
        "task_type": "writing_email",
        "title": title,
        "topic": topic,
        "difficulty": difficulty,
        "estimated_level": level,
        "instructions": "Read the situation and write an email of about 150 to 200 words.",
        "stimulus": {
            "type": "writing_prompt",
            "task_kind": "email",
            "scenario": scenario,
            "audience": audience,
            "requested_points": requested_points,
            "target_words": TARGET_WORDS,
            "suggested_duration_seconds": EMAIL_DURATION_SECONDS,
            "guidance": guidance,
        },
        "learning_notes": learning_notes,
    }


def _survey(
    *,
    slug,
    title,
    topic,
    difficulty,
    level,
    scenario,
    survey_question,
    options,
    requested_points,
    guidance,
    learning_notes,
):
    return {
        "slug": slug,
        "task_type": "writing_survey",
        "title": title,
        "topic": topic,
        "difficulty": difficulty,
        "estimated_level": level,
        "instructions": "Read the survey and write a response of about 150 to 200 words. Choose one option and explain your choice.",
        "stimulus": {
            "type": "writing_prompt",
            "task_kind": "survey",
            "scenario": scenario,
            "survey_question": survey_question,
            "options": options,
            "requested_points": requested_points,
            "target_words": TARGET_WORDS,
            "suggested_duration_seconds": SURVEY_DURATION_SECONDS,
            "guidance": guidance,
        },
        "learning_notes": learning_notes,
    }


WRITING_SETS = [
    _email(
        slug="email-zoning-change",
        title="Email Opposing a Proposed Zoning Change",
        topic="Civic engagement",
        difficulty=3,
        level=11,
        scenario="Your city is considering a zoning change that would allow a large warehouse beside a residential street. You want to write to the planning committee before the public meeting.",
        audience="Planning committee (formal)",
        requested_points=["State your concern clearly.", "Explain the likely impact on residents.", "Propose a balanced alternative or condition."],
        guidance=["Use specific local impacts such as traffic, noise, or safety.", "Keep the tone respectful and evidence-based."],
        learning_notes="Effective civic letters link a clear position to concrete effects and a realistic alternative rather than only opposing the proposal.",
    ),
    _email(
        slug="email-insurance-dispute",
        title="Email Disputing an Insurance Decision",
        topic="Insurance and consumer rights",
        difficulty=3,
        level=12,
        scenario="Your home insurance claim for water damage was partially denied because the insurer says maintenance caused the leak. You believe the policy and your inspection record support full coverage. Write to the claims manager.",
        audience="Insurance claims manager (formal)",
        requested_points=["Identify the decision and policy basis.", "Present your evidence calmly and clearly.", "Request a specific review or appeal step."],
        guidance=["Refer to dates and policy terms.", "Avoid emotional language while remaining firm."],
        learning_notes="A strong dispute restates the decision accurately, counters the reason with evidence, and names the specific remedy or next step.",
    ),
    _email(
        slug="email-remote-work-proposal",
        title="Email Proposing a Remote Work Arrangement",
        topic="Workplace communication",
        difficulty=3,
        level=10,
        scenario="You want to propose working remotely two days a week to reduce a long commute while maintaining your current duties. Write to your supervisor.",
        audience="Your supervisor (professional)",
        requested_points=["Explain the proposed schedule.", "Show how your work will remain effective.", "Suggest a trial period and success measures."],
        guidance=["Focus on productivity and communication.", "Acknowledge any concerns about collaboration."],
        learning_notes="Remote-work proposals succeed when they connect the request to measurable work outcomes and include a trial or review.",
    ),
    _survey(
        slug="survey-affordable-housing-vs-transit",
        title="Survey: Affordable Housing or Transit Investment",
        topic="Urban policy",
        difficulty=3,
        level=12,
        scenario="A city has one large capital grant and can fund either a major affordable-housing development or a major transit expansion, but not both.",
        survey_question="Which investment should the city prioritize?",
        options=[{"key": "housing", "label": "Affordable-housing development"}, {"key": "transit", "label": "Transit expansion"}],
        requested_points=["State your choice.", "Weigh long-term social and economic effects.", "Acknowledge the strongest argument for the other option."],
        guidance=["Consider different income groups and future growth.", "Avoid presenting the other option as worthless."],
        learning_notes="High-level policy responses recognize competing valid goals and justify the chosen trade-off with specific outcomes.",
    ),
    _survey(
        slug="survey-flexible-hours-vs-four-day-week",
        title="Survey: Flexible Hours or a Four-Day Week",
        topic="Workplace policy",
        difficulty=3,
        level=11,
        scenario="An employer can offer one schedule change: fully flexible daily hours or a compressed four-day workweek.",
        survey_question="Which schedule change should the employer offer?",
        options=[{"key": "flexible_hours", "label": "Flexible daily hours"}, {"key": "four_day", "label": "A four-day workweek"}],
        requested_points=["Choose one option.", "Compare the effect on productivity and wellbeing.", "Respond to a likely objection."],
        guidance=["Consider both employees and customers.", "Address fairness or coverage concerns."],
        learning_notes="Workplace schedule arguments are stronger when they include operational feasibility, not only personal convenience.",
    ),
    _survey(
        slug="survey-digital-literacy-vs-maker-space",
        title="Survey: Digital Literacy or Maker Space",
        topic="Community services",
        difficulty=3,
        level=10,
        scenario="A public library can create one new service: a digital-literacy program for seniors and job seekers or a community maker space with creative technology.",
        survey_question="Which service should the library add?",
        options=[{"key": "digital_literacy", "label": "A digital-literacy program"}, {"key": "maker_space", "label": "A community maker space"}],
        requested_points=["State your choice.", "Explain who benefits most.", "Acknowledge the opportunity cost of the other option."],
        guidance=["Use concrete examples of skills or projects.", "Think about equity and long-term value."],
        learning_notes="Good library responses weigh immediate practical skills against long-term creative capacity and explain who is served by each.",
    ),
]
