"""Expanded original Writing prompt bank for the full practice app."""

TARGET_WORDS = {"min": 150, "max": 200}
EMAIL_DURATION_SECONDS = 27 * 60
SURVEY_DURATION_SECONDS = 26 * 60


def _email(
    *,
    slug,
    title,
    topic,
    difficulty,
    level,
    scenario,
    audience,
    requested_points,
    guidance,
    learning_notes,
):
    return {
        "slug": slug,
        "task_type": "writing_email",
        "title": title,
        "topic": topic,
        "difficulty": difficulty,
        "estimated_level": level,
        "instructions": "Read the situation and write an email of about 150 to 200 words.",
        "stimulus": {
            "type": "writing_prompt",
            "task_kind": "email",
            "scenario": scenario,
            "audience": audience,
            "requested_points": requested_points,
            "target_words": TARGET_WORDS,
            "suggested_duration_seconds": EMAIL_DURATION_SECONDS,
            "guidance": guidance,
        },
        "learning_notes": learning_notes,
    }


def _survey(
    *,
    slug,
    title,
    topic,
    difficulty,
    level,
    scenario,
    survey_question,
    options,
    requested_points,
    guidance,
    learning_notes,
):
    return {
        "slug": slug,
        "task_type": "writing_survey",
        "title": title,
        "topic": topic,
        "difficulty": difficulty,
        "estimated_level": level,
        "instructions": "Read the survey and write a response of about 150 to 200 words. Choose one option and explain your choice.",
        "stimulus": {
            "type": "writing_prompt",
            "task_kind": "survey",
            "scenario": scenario,
            "survey_question": survey_question,
            "options": options,
            "requested_points": requested_points,
            "target_words": TARGET_WORDS,
            "suggested_duration_seconds": SURVEY_DURATION_SECONDS,
            "guidance": guidance,
        },
        "learning_notes": learning_notes,
    }


WRITING_SETS = [
    _email(
        slug="email-broken-fridge",
        title="Email About a Broken Fridge",
        topic="Housing and tenancy",
        difficulty=1,
        level=6,
        scenario="The fridge in your rented apartment stopped keeping food cold three days ago. You have already adjusted the temperature and checked the door seal, but the problem continues. Write to your landlord, Ms. Chen.",
        audience="Your landlord (semi-formal)",
        requested_points=["Describe the problem and what you have already tried.", "Explain how it is affecting you.", "Request a repair and suggest a convenient time."],
        guidance=["Stay polite and specific about the appliance and dates.", "Offer access for a technician."],
        learning_notes="A strong repair request names the problem, shows the reasonable steps already tried, and makes it easy for the reader to act.",
    ),
    _email(
        slug="email-deadline-extension",
        title="Email Requesting a Deadline Extension",
        topic="Education",
        difficulty=2,
        level=8,
        scenario="You have a major assignment due Friday, but a family emergency and two shifts at work have left you unable to finish on time. Write to your course instructor, Professor Amin.",
        audience="A course instructor (formal)",
        requested_points=["Explain the situation without oversharing.", "State the extension you are requesting and why it is fair.", "Propose a concrete new date and how you will complete the work."],
        guidance=["Be respectful and accountable.", "Do not blame the instructor or the course."],
        learning_notes="A convincing extension request balances a brief reason with ownership of the work and a realistic plan.",
    ),
    _email(
        slug="email-work-handover",
        title="Email About a Work Handover",
        topic="Workplace communication",
        difficulty=2,
        level=7,
        scenario="You will be away on leave for two weeks, and a coworker, Jamie, will cover your main responsibilities. Write to Jamie before you leave.",
        audience="A coworker (semi-formal)",
        requested_points=["Outline the tasks that need coverage.", "Identify urgent deadlines and key contacts.", "Offer to answer questions before you leave."],
        guidance=["Use clear headings or a short bulleted list.", "Keep the tone helpful rather than bossy."],
        learning_notes="Effective handovers make priorities and contact information easy to scan, not buried in long paragraphs.",
    ),
    _email(
        slug="email-cancel-gym-membership",
        title="Email to Cancel a Gym Membership",
        topic="Consumer situations",
        difficulty=2,
        level=7,
        scenario="You need to cancel your gym membership because you are moving to a different city next month. The contract says written notice is required. Write to the membership team.",
        audience="A gym's membership team (formal)",
        requested_points=["State clearly that you want to cancel.", "Give the effective date and your reason.", "Confirm what final payment or refund you expect."],
        guidance=["Include your account or membership number as a placeholder.", "Be firm but courteous about the terms."],
        learning_notes="Cancellation emails should leave no doubt about the requested action, date, and expected financial outcome.",
    ),
    _email(
        slug="email-damaged-sidewalk",
        title="Email About a Damaged Sidewalk",
        topic="Municipal services",
        difficulty=2,
        level=7,
        scenario="The sidewalk outside your home has cracked and lifted, creating a trip hazard, especially for older neighbours. Write to the city's public works department.",
        audience="Public works department (formal)",
        requested_points=["Describe the location and the hazard.", "Explain who is affected.", "Request an inspection and repair timeline."],
        guidance=["Give a precise address or nearby intersection.", "Mention weather and safety consequences."],
        learning_notes="Requests to a public office are more effective when they are factual, specific, and focused on safety.",
    ),
    _email(
        slug="email-neighbour-noise",
        title="Email to a Neighbour About Noise",
        topic="Neighbourhood relationships",
        difficulty=2,
        level=7,
        scenario="Your neighbour has been playing loud music late on weeknights. You have spoken briefly once, but the problem has continued. Write a friendly but clear email.",
        audience="Your neighbour (semi-formal)",
        requested_points=["Describe the pattern without accusing them.", "Explain how the noise affects your sleep or work.", "Suggest a fair solution."],
        guidance=["Lead with respect and acknowledge that they may not realize the effect.", "Avoid making threats or involving authorities in the message."],
        learning_notes="Neighbour complaints are more likely to succeed when the writer stays calm, factual, and solution-focused.",
    ),
    _email(
        slug="email-lost-luggage",
        title="Email About Lost Luggage",
        topic="Travel and consumer service",
        difficulty=2,
        level=8,
        scenario="Your checked bag did not arrive with your flight three days ago. You have already filed a report at the airport. Write to the airline's baggage services team.",
        audience="Airline baggage services (formal)",
        requested_points=["Give your flight and report details.", "List the bag's appearance and important contents.", "Request an update and the compensation you expect."],
        guidance=["Stay organized and factual.", "Set a reasonable expectation for a response."],
        learning_notes="For lost property, a strong email matches the reported details with a clear request and contact information.",
    ),
    _email(
        slug="email-child-school-absence",
        title="Email About a Child's School Absence",
        topic="Education and family",
        difficulty=1,
        level=6,
        scenario="Your child was absent from school for three days due to a fever and will return tomorrow. Write to the classroom teacher.",
        audience="A classroom teacher (semi-formal)",
        requested_points=["Explain the absence and provide dates.", "Ask about missed work and how your child can catch up.", "Offer to support the return to school."],
        guidance=["Be concise and appreciative.", "State when the child will return."],
        learning_notes="A short, clear school message shows responsibility and helps the teacher prepare for the child's return.",
    ),
    _email(
        slug="email-internet-outage-credit",
        title="Email About an Internet Outage",
        topic="Consumer services",
        difficulty=2,
        level=7,
        scenario="Your home internet was down for four days this month, disrupting your remote work. Write to your internet provider's customer service team to request a credit.",
        audience="Internet provider customer service (formal)",
        requested_points=["Give the dates and account details.", "Describe the impact on your work or household.", "Request a credit or other reasonable remedy."],
        guidance=["Keep the tone professional.", "Be specific about dates and losses."],
        learning_notes="A persuasive service complaint connects the factual outage to a concrete remedy rather than relying on anger.",
    ),
    _email(
        slug="email-volunteer-step-down",
        title="Email About Stepping Down From a Volunteer Role",
        topic="Community volunteering",
        difficulty=2,
        level=7,
        scenario="You have coordinated a weekly community dinner for two years, but a new work schedule means you must step down. Write to the organization's director.",
        audience="Organization director (semi-formal)",
        requested_points=["Thank the director and explain your decision.", "Give a clear final date and offer to help with transition.", "Suggest how your duties could be covered."],
        guidance=["Express gratitude before the difficult news.", "Be specific about the transition offer."],
        learning_notes="Leaving a role with a clear notice period and transition offer preserves the relationship and helps the organization.",
    ),
    _email(
        slug="email-restaurant-reservation-change",
        title="Email Requesting a Restaurant Reservation Change",
        topic="Social and dining",
        difficulty=1,
        level=6,
        scenario="You booked a restaurant table for six people on Saturday evening, but two guests can no longer come and you need to move the reservation 30 minutes earlier. Write to the restaurant.",
        audience="Restaurant reservations team (semi-formal)",
        requested_points=["Give the current booking details.", "Explain the changes you need.", "Ask them to confirm the new arrangement."],
        guidance=["Make the requested time and party size unambiguous.", "Thank them for their help."],
        learning_notes="Reservation changes are easiest when the original details and the requested change are both stated clearly.",
    ),
    _email(
        slug="email-package-theft",
        title="Email About a Missing Package",
        topic="Housing and security",
        difficulty=2,
        level=7,
        scenario="A package delivered to your building's lobby is missing. The tracking page says it was delivered yesterday. Write to the property manager, Mr. Rossi.",
        audience="Property manager (semi-formal)",
        requested_points=["Describe the package and delivery information.", "Explain where it was left and when you noticed it missing.", "Ask what can be done or whether security footage is available."],
        guidance=["Stick to facts and avoid accusing anyone.", "Request a clear next step."],
        learning_notes="A missing-package message is most useful when it gives the manager enough detail to check records without making accusations.",
    ),
    _email(
        slug="email-workplace-accommodation",
        title="Email Requesting a Workplace Accommodation",
        topic="Workplace communication",
        difficulty=3,
        level=9,
        scenario="A recent injury makes it painful to sit for long periods. You need a standing desk and more frequent short breaks for the next month. Write to your supervisor.",
        audience="Your supervisor (professional)",
        requested_points=["Explain the medical limitation in general terms.", "State the specific accommodation you need.", "Propose how your work will remain on schedule."],
        guidance=["Be professional and collaborative.", "Focus on your ability to keep performing the role."],
        learning_notes="Workplace accommodation requests are strongest when they frame the adjustment as a way to maintain productivity, not a list of demands.",
    ),
    _survey(
        slug="survey-library-digital-vs-physical",
        title="Survey: Digital or Physical Library Resources",
        topic="Community services",
        difficulty=1,
        level=6,
        scenario="Your public library has a limited budget and must choose between adding more e-books and digital audiobooks or buying more physical books and magazines.",
        survey_question="Which type of library resource should receive the extra funding?",
        options=[{"key": "digital", "label": "More e-books and digital audiobooks"}, {"key": "physical", "label": "More physical books and magazines"}],
        requested_points=["State which option you prefer.", "Give reasons based on access, cost, or community needs.", "Explain one trade-off you are willing to accept."],
        guidance=["Consider a variety of library users.", "Commit clearly to one option."],
        learning_notes="Good survey answers show that the writer understands who else uses the service, not only their own preference.",
    ),
    _survey(
        slug="survey-community-garden-vs-playground",
        title="Survey: Community Garden or Playground",
        topic="Urban planning",
        difficulty=2,
        level=7,
        scenario="A vacant city-owned lot can be developed as either a community garden or a new children's playground. The city is asking residents which use to support.",
        survey_question="Which use should the city choose for the vacant lot?",
        options=[{"key": "garden", "label": "A community garden"}, {"key": "playground", "label": "A children's playground"}],
        requested_points=["State your choice.", "Support it with reasons about neighbourhood needs.", "Acknowledge the other option briefly."],
        guidance=["Think about who lives nearby.", "Give concrete examples of how residents would benefit."],
        learning_notes="A balanced response states a preference early and then uses evidence rather than repeating the choice.",
    ),
    _survey(
        slug="survey-extra-vacation-vs-wellness",
        title="Survey: Extra Vacation or Wellness Stipend",
        topic="Workplace policy",
        difficulty=3,
        level=9,
        scenario="Your employer can offer one new benefit this year: an extra week of paid vacation or a wellness stipend for gym memberships and mental-health services.",
        survey_question="Which employee benefit should the company offer?",
        options=[{"key": "vacation", "label": "One extra week of paid vacation"}, {"key": "wellness", "label": "A wellness stipend"}],
        requested_points=["State which benefit you support.", "Explain how it affects employees and the employer.", "Respond to a likely objection."],
        guidance=["Use reasons that would persuade an employer.", "Consider both immediate and long-term effects."],
        learning_notes="Higher-level workplace responses connect personal wellbeing to measurable outcomes such as retention or focus.",
    ),
    _survey(
        slug="survey-transit-frequency-vs-fare-freeze",
        title="Survey: Transit Frequency or Fare Freeze",
        topic="Public transit",
        difficulty=2,
        level=8,
        scenario="Your city has funding to improve transit. It can either run buses and trains more frequently or keep fares at their current level for two years.",
        survey_question="How should the city improve transit?",
        options=[{"key": "frequency", "label": "Run buses and trains more frequently"}, {"key": "fare_freeze", "label": "Freeze fares for two years"}],
        requested_points=["Choose one option.", "Give reasons based on convenience, cost, or ridership.", "Explain who benefits most from your choice."],
        guidance=["Connect the option to daily transit use.", "Be specific about the trade-off."],
        learning_notes="A persuasive transit answer links the choice to real ridership effects, not only personal cost.",
    ),
    _survey(
        slug="survey-longer-recess-vs-shorter-year",
        title="Survey: Longer Recess or Shorter School Year",
        topic="Education",
        difficulty=2,
        level=7,
        scenario="A school district is considering either adding an extra 15 minutes of outdoor recess each day or shortening the school year by two days.",
        survey_question="Which change should the district make?",
        options=[{"key": "recess", "label": "Add 15 minutes of daily recess"}, {"key": "shorter_year", "label": "Shorten the school year by two days"}],
        requested_points=["State your preferred option.", "Explain the effect on students, families, and teachers.", "Address one concern about your choice."],
        guidance=["Consider learning and wellbeing together.", "Use realistic examples."],
        learning_notes="Responses about education are stronger when they consider families and teachers, not just one group.",
    ),
    _survey(
        slug="survey-outdoor-pool-vs-splash-pad",
        title="Survey: Outdoor Pool or Splash Pad",
        topic="Community recreation",
        difficulty=1,
        level=6,
        scenario="A town can build either an outdoor swimming pool or a low-maintenance splash pad in a central park.",
        survey_question="Which facility should the town build?",
        options=[{"key": "pool", "label": "An outdoor swimming pool"}, {"key": "splash_pad", "label": "A splash pad"}],
        requested_points=["Choose one facility.", "Give reasons based on cost, use, or accessibility.", "Acknowledge one drawback of your choice."],
        guidance=["Think about different ages and abilities.", "Keep the response practical."],
        learning_notes="A clear choice plus a named drawback shows balanced judgement rather than overselling an option.",
    ),
    _survey(
        slug="survey-free-delivery-vs-loyalty-discount",
        title="Survey: Free Delivery or Loyalty Discount",
        topic="Consumer services",
        difficulty=2,
        level=7,
        scenario="An online grocery store is asking customers which reward is better: free delivery on every order over $50 or a five percent loyalty discount on all orders.",
        survey_question="Which customer reward should the store offer?",
        options=[{"key": "delivery", "label": "Free delivery over $50"}, {"key": "discount", "label": "A five percent loyalty discount"}],
        requested_points=["State which reward you prefer.", "Explain who benefits from each option.", "Support your choice with a practical example."],
        guidance=["Think about shopping frequency and household size.", "Avoid listing both options without choosing."],
        learning_notes="Consumer survey answers should connect the reward to actual shopping behaviour.",
    ),
    _survey(
        slug="survey-cooking-vs-fitness-classes",
        title="Survey: Cooking Classes or Fitness Classes",
        topic="Community programs",
        difficulty=2,
        level=7,
        scenario="A community centre has room for one new program: a series of healthy cooking classes or an expanded schedule of fitness classes.",
        survey_question="Which program should the community centre add?",
        options=[{"key": "cooking", "label": "Healthy cooking classes"}, {"key": "fitness", "label": "Expanded fitness classes"}],
        requested_points=["State your choice.", "Give reasons based on health, community, or cost.", "Consider who may be left out by your choice."],
        guidance=["Connect the program to everyday community needs.", "Be specific about benefits."],
        learning_notes="Strong answers show awareness of access and inclusion, not only popularity.",
    ),
    _survey(
        slug="survey-bike-share-vs-electric-buses",
        title="Survey: Bike Share Expansion or Electric Buses",
        topic="Transportation and environment",
        difficulty=3,
        level=9,
        scenario="A city wants to reduce transportation emissions. It can either expand its bike-share network into more neighbourhoods or replace older diesel buses with electric buses.",
        survey_question="Which investment should the city prioritize?",
        options=[{"key": "bike_share", "label": "Expand the bike-share network"}, {"key": "electric_buses", "label": "Replace buses with electric models"}],
        requested_points=["Choose one investment.", "Compare the environmental and access effects.", "Explain a limitation you are willing to accept."],
        guidance=["Consider cost, reach, and who can use each option.", "Acknowledge the trade-off explicitly."],
        learning_notes="Complex policy answers are more convincing when they weigh both environmental benefit and equitable access.",
    ),
    _survey(
        slug="survey-off-leash-vs-sports-field",
        title="Survey: Off-Leash Area or Sports Field",
        topic="Parks and recreation",
        difficulty=2,
        level=7,
        scenario="A large park has space for one new feature: a fenced off-leash dog area or an additional soccer field.",
        survey_question="Which park feature should be built?",
        options=[{"key": "off_leash", "label": "A fenced off-leash dog area"}, {"key": "sports_field", "label": "An additional soccer field"}],
        requested_points=["State your preferred feature.", "Give reasons about park use and community needs.", "Acknowledge the other group's interests."],
        guidance=["Think about different park users.", "Keep the tone balanced."],
        learning_notes="A good park-use response recognizes that public space serves several groups with competing needs.",
    ),
    _survey(
        slug="survey-seniors-vs-youth-program",
        title="Survey: Seniors Program or Youth Program",
        topic="Community services",
        difficulty=2,
        level=8,
        scenario="A community centre has one new part-time coordinator position and can use it for a seniors' social program or a youth after-school program.",
        survey_question="Which age group should receive the new program?",
        options=[{"key": "seniors", "label": "A seniors' social program"}, {"key": "youth", "label": "A youth after-school program"}],
        requested_points=["Choose one program.", "Explain the community need it addresses.", "Acknowledge why the other program is also valuable."],
        guidance=["Avoid stereotypes about either age group.", "Use concrete examples of isolation, safety, or learning."],
        learning_notes="Sensitive responses avoid ranking one group as more deserving and instead focus on the specific need the program meets.",
    ),
    _survey(
        slug="survey-festival-vs-public-art",
        title="Survey: Festival Funding or Public Art",
        topic="Arts and culture",
        difficulty=2,
        level=8,
        scenario="A city arts budget can either fund a free weekend street festival or commission several permanent public artworks.",
        survey_question="How should the city spend its arts budget?",
        options=[{"key": "festival", "label": "Fund a free weekend street festival"}, {"key": "public_art", "label": "Commission permanent public artworks"}],
        requested_points=["State your choice.", "Explain the cultural or economic benefits.", "Consider which residents benefit most."],
        guidance=["Compare short-term and long-term value.", "Use specific examples."],
        learning_notes="Arts responses work best when they consider both immediate participation and lasting public benefit.",
    ),
    _survey(
        slug="survey-daycare-vs-transit-subsidy",
        title="Survey: Daycare Subsidy or Transit Subsidy",
        topic="Workplace policy",
        difficulty=3,
        level=9,
        scenario="An employer can help employees with one new support: a monthly childcare subsidy or a monthly public-transit subsidy.",
        survey_question="Which support should the employer offer?",
        options=[{"key": "daycare", "label": "A monthly childcare subsidy"}, {"key": "transit", "label": "A monthly public-transit subsidy"}],
        requested_points=["Choose one support.", "Explain how it helps employees with different circumstances.", "Acknowledge a fairness concern."],
        guidance=["Consider fairness and employee diversity.", "Connect the choice to attendance or retention."],
        learning_notes="High-level answers weigh fairness carefully and avoid assuming every employee has the same needs.",
    ),
]
