# Generated by Django 5.2.17 on 2026-08-29 00:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_key', models.CharField(max_length=240, unique=True)),
                ('mime_type', models.CharField(max_length=80)),
                ('byte_size', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(20971520)])),
                ('duration_ms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(600000)])),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('transcript', models.TextField()),
                ('voice_label', models.CharField(blank=True, max_length=120)),
                ('provenance', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending validation'), ('ready', 'Ready'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='audio_asset', to='content.contentversion')),
            ],
            options={
                'ordering': ['content_version__item__task_type__part_number'],
            },
        ),
        migrations.CreateModel(
            name='MediaPlaybackGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grants_issued', models.PositiveSmallIntegerField(default=0)),
                ('last_granted_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_grants', to='media_assets.mediaasset')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_playback_grants', to='assessments.assessmentsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'asset'), name='media_unique_session_asset_grant')],
            },
        ),
    ]
