# Generated by Django 5.2.17 on 2026-08-30 10:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRendition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('azure', 'Azure')], max_length=12)),
                ('storage_key', models.CharField(max_length=240, unique=True)),
                ('mime_type', models.CharField(max_length=80)),
                ('byte_size', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(20971520)])),
                ('duration_ms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(600000)])),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('model_name', models.CharField(max_length=120)),
                ('voice_label', models.CharField(blank=True, max_length=120)),
                ('provenance', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending validation'), ('ready', 'Ready'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='media_assets.mediaasset')),
            ],
            options={
                'ordering': ['canonical_asset_id', 'provider'],
                'indexes': [models.Index(fields=['provider', 'status'], name='media_rendition_prov_status')],
                'constraints': [models.UniqueConstraint(fields=('canonical_asset', 'provider'), name='media_unique_rendition_asset_provider')],
            },
        ),
    ]
