# Generated by Django 5.2.17 on 2026-08-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0002_audiorendition'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='speaker_genders',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
