# Generated by Django 5.2.17 on 2026-08-29 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('reason_summary', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='StudyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('order', models.PositiveSmallIntegerField()),
                ('skill', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking')], max_length=16)),
                ('title', models.CharField(max_length=180)),
                ('minutes', models.PositiveSmallIntegerField()),
                ('reason', models.TextField()),
                ('destination', models.CharField(max_length=180)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='learning.studyplan')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_tasks', to='content.tasktype')),
            ],
            options={
                'ordering': ['scheduled_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MistakeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking')], max_length=16)),
                ('stem_snapshot', models.TextField()),
                ('selected_snapshot', models.TextField(blank=True)),
                ('correct_snapshot', models.TextField()),
                ('explanation_snapshot', models.TextField()),
                ('occurrences', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=12)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learner_mistakes', to='content.question')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learner_mistakes', to='content.tasktype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurrences', '-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'state', '-last_seen_at'], name='learning_mi_user_id_7e1aa6_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'question'), name='learning_unique_user_question_mistake')],
            },
        ),
        migrations.AddConstraint(
            model_name='studyplan',
            constraint=models.UniqueConstraint(fields=('user', 'version'), name='learning_unique_user_plan_version'),
        ),
        migrations.AddConstraint(
            model_name='studyplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='learning_one_active_plan_per_user'),
        ),
        migrations.AddConstraint(
            model_name='studytask',
            constraint=models.UniqueConstraint(fields=('plan', 'scheduled_date', 'order'), name='learning_unique_plan_day_order'),
        ),
    ]
