# Generated by Django 5.2.17 on 2026-09-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_mistake_review_schedule'),
        ('learning', '0003_studyplan_difficulty_preference'),
    ]

    operations = [
    ]
