# Generated by Django 5.2.17 on 2026-09-26 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_speaking_unique_scene_images'),
        ('learning', '0004_merge_20260901_1121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternDrillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('correct', models.PositiveIntegerField(default=0)),
                ('streak', models.PositiveSmallIntegerField(default=0)),
                ('last_drilled_at', models.DateTimeField()),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pattern_drills', to='content.tasktype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_drills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['task_type_id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'task_type'), name='learning_unique_user_pattern_drill')],
            },
        ),
    ]
