# Generated by Django 5.2.17 on 2026-08-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_identifier_ci_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='practice_narration_voice',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('voice_1', 'Voice 1'), ('voice_2', 'Voice 2')], default='automatic', help_text='Preferred narrator for future generated single-narrator practice narration. A presentation preference only — never a speech provider, key, or provider order. Does not change authored/scored Listening dialogues, which keep their reviewed multi-speaker mix.', max_length=16),
        ),
    ]
