# Generated by Django 5.2.17 on 2026-08-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_learnerprofile_practice_narration_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='preferred_audio_provider',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('openai', 'OpenAI'), ('azure', 'Azure'), ('local', 'Local')], default='automatic', help_text="Preferred speech vendor for generated audio renditions. A presentation preference only — never an API key or provider order. 'local' prefers the existing locally produced recording; 'automatic' lets the app decide.", max_length=16),
        ),
    ]
