# Generated by Django 5.2.17 on 2026-08-29 00:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_token_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('guest_expires_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('mode', models.CharField(choices=[('learn', 'Learn'), ('practice', 'Practice')], max_length=12)),
                ('state', models.CharField(choices=[('active', 'Active'), ('submitted', 'Submitted')], default='active', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ObjectiveResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_correct', models.PositiveIntegerField()),
                ('raw_possible', models.PositiveIntegerField()),
                ('outcomes', models.JSONField(default=list)),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='objective_result', to='assessments.assessmentsession')),
            ],
        ),
        migrations.CreateModel(
            name='SessionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('snapshot', models.JSONField()),
                ('content_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_items', to='content.contentversion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assessments.assessmentsession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(default=0)),
                ('last_idempotency_key', models.UUIDField(blank=True, null=True)),
                ('last_payload_hash', models.CharField(blank=True, max_length=64)),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_responses', to='content.question')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_responses', to='content.choice')),
                ('session_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.sessionitem')),
            ],
            options={
                'ordering': ['question__order'],
            },
        ),
        migrations.AddIndex(
            model_name='assessmentsession',
            index=models.Index(fields=['user', 'state', '-started_at'], name='assessments_user_id_454f05_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentsession',
            index=models.Index(fields=['state', 'deadline_at'], name='assessments_state_abe36a_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentsession',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), models.Q(models.Q(('guest_token_hash', ''), _negated=True), ('guest_expires_at__isnull', False)), _connector='OR'), name='assessments_session_has_owner'),
        ),
        migrations.AddConstraint(
            model_name='assessmentsession',
            constraint=models.CheckConstraint(condition=models.Q(('mode', 'practice'), ('deadline_at__isnull', True), _connector='OR'), name='assessments_only_practice_has_deadline'),
        ),
        migrations.AddConstraint(
            model_name='sessionitem',
            constraint=models.UniqueConstraint(fields=('session', 'order'), name='assessments_unique_session_item_order'),
        ),
        migrations.AddConstraint(
            model_name='sessionitem',
            constraint=models.UniqueConstraint(fields=('session', 'content_version'), name='assessments_unique_session_content'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('session_item', 'question'), name='assessments_unique_item_question_response'),
        ),
    ]
