# Generated by Django 5.2.17 on 2026-08-29 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('last_idempotency_key', models.UUIDField(blank=True, null=True)),
                ('last_payload_hash', models.CharField(blank=True, max_length=64)),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('session_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='writing_submission', to='assessments.sessionitem')),
            ],
        ),
    ]
