# Generated by Django 5.2.17 on 2026-08-29 07:48

import apps.assessments.models
import apps.assessments.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_writingsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(max_length=240, storage=apps.assessments.storage.PrivateRecordingStorage(), upload_to=apps.assessments.models.speaking_recording_path)),
                ('mime_type', models.CharField(max_length=40)),
                ('container', models.CharField(max_length=8)),
                ('byte_size', models.PositiveIntegerField()),
                ('duration_ms', models.PositiveIntegerField()),
                ('revision', models.PositiveIntegerField(default=0)),
                ('last_idempotency_key', models.UUIDField(blank=True, null=True)),
                ('last_payload_hash', models.CharField(blank=True, max_length=64)),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('session_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_submission', to='assessments.sessionitem')),
            ],
        ),
    ]
