# Generated by Django 5.2.17 on 2026-08-29 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_speakingsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assessmentsession',
            name='assessments_only_practice_has_deadline',
        ),
        migrations.AlterField(
            model_name='assessmentsession',
            name='mode',
            field=models.CharField(choices=[('learn', 'Learn'), ('practice', 'Practice'), ('mock', 'Mock')], max_length=12),
        ),
        migrations.AddConstraint(
            model_name='assessmentsession',
            constraint=models.CheckConstraint(condition=models.Q(('mode__in', ['practice', 'mock']), ('deadline_at__isnull', True), _connector='OR'), name='assessments_timed_modes_have_deadline'),
        ),
    ]
