# Generated by Django 5.2.17 on 2026-08-29 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_remove_assessmentsession_assessments_only_practice_has_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='SpeakingRetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_retry_of', to='assessments.assessmentsession')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_retry', to='assessments.assessmentsession')),
            ],
            options={
                'verbose_name': 'Speaking retry',
                'verbose_name_plural': 'Speaking retries',
            },
        ),
    ]
