# Generated by Django 5.2.17 on 2026-08-29 22:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_assessmentsession_attempt_number_speakingretry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assessmentsession',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__in', [1, 2])), name='assessments_session_attempt_in_range'),
        ),
        migrations.AddConstraint(
            model_name='speakingretry',
            constraint=models.CheckConstraint(condition=models.Q(('source', models.F('retry')), _negated=True), name='assessments_speaking_retry_distinct_sessions'),
        ),
    ]
