# Generated by Django 5.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("assessments", "0007_contentissue")]

    operations = [
        migrations.CreateModel(
            name="WritingRetry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "retry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writing_retry_of",
                        to="assessments.assessmentsession",
                    ),
                ),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writing_retry",
                        to="assessments.assessmentsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Writing retry",
                "verbose_name_plural": "Writing retries",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("source", models.F("retry")), _negated=True),
                        name="assessments_writing_retry_distinct_sessions",
                    )
                ],
            },
        )
    ]
