# Generated by Django 5.2.17 on 2026-08-29 08:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0003_speakingsubmission'),
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('writing_feedback', 'Writing feedback'), ('speaking_feedback', 'Speaking feedback'), ('content_draft', 'Content draft'), ('image_draft', 'Image draft'), ('speech_draft', 'Speech draft')], max_length=24)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=12)),
                ('provider', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=80)),
                ('prompt_version', models.CharField(max_length=40)),
                ('schema_version', models.CharField(default='1', max_length=20)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('run_after', models.DateTimeField()),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('content_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='content.contentversion')),
                ('session_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='assessments.sessionitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('writing_feedback', 'Writing feedback'), ('speaking_feedback', 'Speaking feedback')], max_length=24)),
                ('provider', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=80)),
                ('prompt_version', models.CharField(max_length=40)),
                ('transcript', models.TextField(blank=True)),
                ('assessment', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to='assessments.sessionitem')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to='ai_services.aijob')),
            ],
        ),
        migrations.AddIndex(
            model_name='aijob',
            index=models.Index(fields=['status', 'run_after', 'created_at'], name='ai_services_status_2dfcf8_idx'),
        ),
        migrations.AddIndex(
            model_name='aijob',
            index=models.Index(fields=['session_item', 'kind', '-created_at'], name='ai_services_session_48f4b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='aijob',
            constraint=models.CheckConstraint(condition=models.Q(('session_item__isnull', False), ('content_version__isnull', False), ('kind', 'content_draft'), _connector='OR'), name='ai_job_has_subject'),
        ),
    ]
