# Generated by Django 5.2.17 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("ai_services", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="aijob",
            name="kind",
            field=models.CharField(
                choices=[
                    ("writing_feedback", "Writing feedback"),
                    ("speaking_feedback", "Speaking feedback"),
                    ("response_exemplar", "Response exemplar"),
                    ("content_draft", "Content draft"),
                    ("image_draft", "Image draft"),
                    ("speech_draft", "Speech draft"),
                ],
                max_length=24,
            ),
        ),
    ]
