# Generated by Django 5.2.17 on 2026-09-26 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def group_existing_messages(apps, schema_editor):
    """Keep each learner's pre-history chat as one saved conversation."""
    Conversation = apps.get_model("ai_services", "AICoachConversation")
    Message = apps.get_model("ai_services", "AICoachMessage")
    user_ids = (
        Message.objects.filter(conversation__isnull=True)
        .order_by()
        .values_list("user_id", flat=True)
        .distinct()
    )
    for user_id in list(user_ids):
        messages = Message.objects.filter(user_id=user_id, conversation__isnull=True)
        ordered = messages.order_by("created_at", "id")
        first, last = ordered.first(), ordered.last()
        opener = ordered.filter(role="user").first() or first
        conversation = Conversation.objects.create(
            user_id=user_id,
            title=" ".join(opener.content.split())[:120] or "AI Coach chat",
            skill=last.skill or "general",
        )
        Conversation.objects.filter(pk=conversation.pk).update(
            created_at=first.created_at, updated_at=last.created_at
        )
        messages.update(conversation=conversation)


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0003_aicoachmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICoachConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('skill', models.CharField(blank=True, default='general', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_coach_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='aicoachmessage',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_services.aicoachconversation'),
        ),
        migrations.RunPython(group_existing_messages, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='aicoachconversation',
            index=models.Index(fields=['user', '-updated_at'], name='ai_services_user_id_9e6a36_idx'),
        ),
    ]
