# Generated by Django 5.2.17 on 2026-09-26 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0004_aicoachconversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicoachmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_services.aicoachconversation'),
        ),
    ]
